#include "3dgs.hlsl"

#include "ssrt.hlsl"

float3 SH3Evaluate(float3 ViewDirection, SHCoefficents3 SH3, int Degree)
{
	const float SH_C0 = 0.28209479177387814f;
	const float SH_C1 = 0.4886025119029199f;
	const float SH_C2[] = {
		1.0925484305920792f,
		-1.0925484305920792f,
		0.31539156525252005f,
		-1.0925484305920792f,
		0.5462742152960396f
	};
	const float SH_C3[] = {
		-0.5900435899266435f,
		2.890611442640554f,
		-0.4570457994644658f,
		0.3731763325901154f,
		-0.4570457994644658f,
		1.445305721320277f,
		-0.5900435899266435f
	};
	// The SH stored in the gaussians is "flipped" compared to ordinary computer graphics
	// conventions.
	float3 NViewDirection = -ViewDirection;

	float3 result = SH_C0 * SH3.Low.Color;

	if(Degree >= 1) {
		float x = NViewDirection.x;
		float y = NViewDirection.y;
		float z = NViewDirection.z;
		result = result - SH_C1 * y * SH3.Low.SH1[0] + SH_C1 * z * SH3.Low.SH1[1] - SH_C1 * x * SH3.Low.SH1[2];

		if(Degree >= 2) {
			float xx = x * x, yy = y * y, zz = z * z;
			float xy = x * y, yz = y * z, xz = x * z;
			result = result +
				SH_C2[0] * xy * SH3.Low.SH2[0] +
				SH_C2[1] * yz * SH3.Low.SH2[1] +
				SH_C2[2] * (2.0f * zz - xx - yy) * SH3.Low.SH2[2] +
				SH_C2[3] * xz * SH3.Low.SH2[3] +
				SH_C2[4] * (xx - yy) * SH3.Low.SH2[4];

			if(Degree >= 3) {
				result = result +
					SH_C3[0] * y * (3.0f * xx - yy) * SH3.SH3[0] +
					SH_C3[1] * xy * z * SH3.SH3[1] +
					SH_C3[2] * y * (4.0f * zz - xx - yy) * SH3.SH3[2] +
					SH_C3[3] * z * (2.0f * zz - 3.0f * xx - 3.0f * yy) * SH3.SH3[3] +
					SH_C3[4] * x * (4.0f * zz - xx - yy) * SH3.SH3[4] +
					SH_C3[5] * z * (xx - yy) * SH3.SH3[5] +
					SH_C3[6] * x * (xx - 3.0f * yy) * SH3.SH3[6];
			}
		}
	}
	// Seems that 3DGS padded the SH (maybe this made optimization easier?)
	result += 0.5f;
	return max(result, 0.0f);
}


#ifndef USING_3DGS_RT
[numthreads(1, 1, 1)]
void GenerateDispatchIndirect () {
	DispatchIndirectCommand Cmd = (DispatchIndirectCommand)0;

	Cmd.ThreadGroupCountX = (g_ThreadsToDispatchCountBuffer[0] + UB.IndirectThreadGroupSize - 1) / UB.IndirectThreadGroupSize;
	Cmd.ThreadGroupCountY = 1;
	Cmd.ThreadGroupCountZ = 1;
	g_RWDispatchIndirectCommandBuffer[0] = Cmd;
}

[numthreads(1, 1, 1)]
void GenerateDrawIndirect () {
	DrawIndirectCommand Cmd = (DrawIndirectCommand)0;
	Cmd.VertexCount = g_VertexToDrawCountBuffer[0];
	Cmd.InstanceCount = 1;
	Cmd.StartVertex = 0;
	Cmd.StartInstance = 0;
	g_RWDrawIndirectCommandBuffer[0] = Cmd;
}

uint4 GetOverlappingTiles (float2 ScreenPosition, float Radius) {
	float2 MinTexCoords = ScreenPosition - Radius;
	float2 MaxTexCoords = ScreenPosition + Radius;
	// Convert to tile coords
	int2 MinTileCoords = floor(MinTexCoords / TILE_SIZE);
	int2 MaxTileCoords = ceil(MaxTexCoords  / TILE_SIZE);
	MinTileCoords = clamp(MinTileCoords, 0, UB.TileDimensions);
	MaxTileCoords = clamp(MaxTileCoords, 0, UB.TileDimensions);
	return uint4(MinTileCoords, MaxTileCoords);
}

[numthreads(WAVE_SIZE, 1, 1)]
void ClearCounters () {
	g_RWActiveGaussianCountBuffer[0] = 0;
}

// Filter the active gaussians that are visible in the view frustrum
[numthreads(WAVE_SIZE, 1, 1)]
void FilterActiveGaussians (uint DispatchID : SV_DispatchThreadID) {

	uint GaussianIndex = DispatchID;
	
	if(GaussianIndex >= UB.NumGaussians) return ;

    Gaussian G = FetchGaussian(GaussianIndex);

	float3 ViewSpacePosition = 0;
	if(IsPointInFrustrum(UB.MainCamera, G.Position, ViewSpacePosition, false, 0.2f, 0.2f)) {
		int GaussianCount = WaveActiveCountBits(1);
		int GaussianRank  = WavePrefixCountBits(1);
		int GaussianBaseIndex = 0;
		if(WaveIsFirstLane()) {
			InterlockedAdd(g_RWActiveGaussianCountBuffer[0], GaussianCount, GaussianBaseIndex);
		}
		GaussianBaseIndex = WaveReadLaneFirst(GaussianBaseIndex);
		// Store the indices of active gaussians into a list.
		int ActiveListIndex = GaussianBaseIndex + GaussianRank;

		g_RWActiveGaussianListSrcBuffer[ActiveListIndex] = GaussianIndex;
		// The view space align the view direction with the negative z axis
		float LinearDepth = -ViewSpacePosition.z;
		g_RWActiveGaussianLinearDepthSrcBuffer[ActiveListIndex] = LinearDepth;
	}
}

// The active indices are sorted according to their linear depth

[numthreads(WAVE_SIZE, 1, 1)]
void ProjectActiveGaussians (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= g_RWActiveGaussianCountBuffer[0]) return;
	int GaussianIndex = g_RWActiveGaussianListBuffer[DispatchID];
    
    CameraDescription C = GetCameraDescription();
    Gaussian G = FetchGaussian(GaussianIndex);
    SymmetricMatrix Cov3D = ComputeCovarianceMatrix(G.Scale, G.Rotation);
    // Project to 2D covariance
    float3x3 J = float3x3(
        1, 0, 0,
        0, 1, 0,
        0, 0, 0
    );
#if !(RASTERIZATION_IS_ORTHO_CAMERA)
    J = EWAJacobian(G.Position, C.FieldOfView, C.View);
#endif
    float4 HomogeneousW = mul(C.ProjectionView, float4(G.Position, 1.f));
    float3 Homogeneous = HomogeneousW.xyz / HomogeneousW.w;

    // Get the covariance matrix in NDC space ([-1, 1] ^ 2)
    float3 Cov2D = ProjectCovarianceMatrixToNDC(
        J, Cov3D, C.View
    );

    float  Det           = Cov2D.x * Cov2D.z - Cov2D.y * Cov2D.y;

#ifdef OUTPUT_COLORED_GAUSSIANS
	SHCoefficents3 SH3 = FetchGaussianSHCoefficients(GaussianIndex, 3);
	float3 ViewDirection = normalize(C.Position - G.Position);
	float3 Color = SH3Evaluate(ViewDirection, SH3, 3);
	g_RWActiveGaussianColorBuffer[DispatchID] = Color;
#endif

    // Compute extent in screen space (by finding eigenvalues of
    // 2D covariance matrix). Use extent to compute a bounding rectangle
    // of screen-space tiles that this Gaussian overlaps with. Quit if
    // rectangle covers 0 tiles. 
    // Eigenvalues of 2D covariance matrix denotes the variance of the 
    // Gaussian in the directions of the eigenvectors, which are the
    // principal axes of the Gaussian. 
    float Mean    = 0.5f * (Cov2D.x + Cov2D.z);
	float Discriminant = sqrt(max(0.0f, Mean * Mean - Det));
    float Lambda1 = Mean + Discriminant;
    float Lambda2 = Mean - Discriminant;
    // Find the eigenvectors of the covariance matrix
    float2 Eigenvector1 = float2(Cov2D.y, Lambda1 - Cov2D.x);
    float2 Eigenvector2 = float2(Cov2D.y, Lambda2 - Cov2D.x);
    Eigenvector1 = normalize(Eigenvector1);
    Eigenvector2 = normalize(Eigenvector2);
	// Output the projected quad vectors
	// OPTIMIZE: scale the vectors according to opacity of the gaussian
	float2 ClampedPosition = saturateDown(Homogeneous.xy * 0.25 + 0.5f);
	g_RWActiveGaussianNDCPositionBuffer[DispatchID] = PackUnorm16x2(ClampedPosition);
    float2 ClampedVector1 = Eigenvector1 * sqrt(abs(Lambda1));
	g_RWActiveGaussianQuadNDCVector0Buffer[DispatchID] = PackUnorm16x2(saturateDown(ClampedVector1 * 0.5 + 0.5));
	float2 ClampedVector2 = Eigenvector2 * sqrt(abs(Lambda2));
	g_RWActiveGaussianQuadNDCVector1Buffer[DispatchID] = PackUnorm16x2(saturateDown(ClampedVector2 * 0.5 + 0.5));


	// g_RWActiveGaussianQuadLinearDepthsBuffer[DispatchID] = float2(
	// 	MaxResponseDepth1, MaxResponseDepth2
	// );
	// FIXME the original value should be correct.
	// g_RWActiveGaussianLinearDepthBuffer[DispatchID] = MaxResponseDepth0;
	// g_RWActiveGaussianQuadLinearDepthsBuffer[DispatchID] = 
	// 	g_RWActiveGaussianLinearDepthBuffer[DispatchID].xx;
}

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void ResolveGBuffers (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	float2 DepthUnnormalized = GetRWDepthTexture(C)[DispatchID].xy;
	float Weight = DepthUnnormalized.y;
	float Depth = DepthUnnormalized.x / max(Weight, 1e-6f);
	// TODO dynamic thresh
	if(Weight < 0.05) {
		// Empty pixel.
		Depth = 0;
	}
	// Depth
	GetRWDepthTexture(C)[DispatchID].x = Depth;
	// If the normals are reconstructed from the depth, they are not rendered to the GBuffer
#ifndef RECONSTRUCT_NORMALS_FROM_DEPTH
	// Normal
	float3 Normal = GetRWNormalTexture(C)[DispatchID].xyz / max(Weight, 1e-6f);
	Normal = Normal * 2 - 1;
	if(any(Normal != -1)) {
		Normal = normalize(Normal);
	}
	GetRWNormalTexture(C)[DispatchID] = float4(Normal * 0.5 + 0.5, 1);
#endif
}

float TapDepth (CameraDescription C, int2 TapCoords) {
	TapCoords = clamp(TapCoords, 0, C.FilmDimensions - 1);
	return GetDepthTexture(C).Load(int3(TapCoords, 0)).r;
}

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void FilterDepth (uint2 DispatchID : SV_DispatchThreadID) {
	// fp16 low quality depth -> fp32 filtered depth
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	float SumWeight = 0;
	float SumDepth  = 0;
	for(int dx = -1; dx <= 1; dx++) {
		for(int dy = -1; dy <= 1; dy++) {
			int2 TapCoords = DispatchID + int2(dx, dy);
			if(IsOutOfFilm(C, TapCoords)) continue;
			float Depth  = TapDepth(C, TapCoords);
			float Opacity = GetColorTexture(C).Load(int3(TapCoords, 0)).w;
			if(Opacity < UB.OpaqueThreshold) continue;
			float Weight = Opacity * (1.f / (1 + abs(dx) + abs(dy)));
			SumWeight += Weight;
			SumDepth  += Depth * Weight;
		}
	}
	if(SumWeight <= UB.OpaqueThreshold) SumDepth = 0;
	float FilteredDepth = SumDepth / max(SumWeight, 1e-6f);
	GetRWFilteredDepthTexture(C)[DispatchID] = FilteredDepth;
	float ZDepth = FilteredDepth == 0 ? -1 : LinearToZDepth(C, FilteredDepth);
	GetRWZDepthTexture(C)[DispatchID] = ZDepth;
}

Texture2D<float> g_InNearHZBTexture;
RWTexture2D<float> g_OutRWNearHZBTexture;

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void GenerateNearHZB (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	uint2 Dimensions = 0;
	g_InNearHZBTexture.GetDimensions(Dimensions.x, Dimensions.y);
	if(any(DispatchID >= Dimensions)) return;
	float4 ZDepths = g_InNearHZBTexture.GatherRed(g_PointClampSampler, DispatchID * 2);
	// Filter invalid depth values
	ZDepths = select(ZDepths < 0, 1.f.xxxx, ZDepths);
	float  MinZDepth = min(
		min(ZDepths.x, ZDepths.y),
		min(ZDepths.z, ZDepths.w)
	);
	g_OutRWNearHZBTexture[DispatchID] = MinZDepth;
}

float TapDepthFiltered (CameraDescription C, int2 TapCoords) {
	TapCoords = clamp(TapCoords, 0, C.FilmDimensions - 1);
	return GetFilteredDepthTexture(C).Load(int3(TapCoords, 0)).r;
}

// Reconstruct the normal texture from depth texture, so we dont have to rasterize normals.
// Overdraws from 3DGS are huge burdens on output mergers.
[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void ReconstructNormals (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	int2   TexCoords = int2(DispatchID);
	float  Depth = TapDepthFiltered(C, TexCoords);
	float3 CameraDirection = NDC2ToCameraDirection(C, FilmToNDC2(C, TexCoords + 0.5f.xx));
	
#ifndef HIGH_QUALITY_NORMAL_RECONSTRUCTION

	float4 Depths = float4(
		TapDepthFiltered(C, TexCoords - int2(1, 0)),
		TapDepthFiltered(C, TexCoords + int2(1, 0)),
		TapDepthFiltered(C, TexCoords - int2(0, 1)),
		TapDepthFiltered(C, TexCoords + int2(0, 1))
	);
	float3 Left  = RecoverWorldSpacePosition(C, TexCoords - int2(1, 0) + 0.5f.xx, Depths.x);
	float3 Right = RecoverWorldSpacePosition(C, TexCoords + int2(1, 0) + 0.5f.xx, Depths.y);
	float3 Up    = RecoverWorldSpacePosition(C, TexCoords - int2(0, 1) + 0.5f.xx, Depths.z);
	float3 Down  = RecoverWorldSpacePosition(C, TexCoords + int2(0, 1) + 0.5f.xx, Depths.w);
	float3 HorizontalDerivative = normalize(Right - Left);
	float3 VerticalDerivative = normalize(Down - Up);
	float3 Normal = normalize(cross(HorizontalDerivative, VerticalDerivative));
	if(dot(Normal, CameraDirection) > 0) {
		Normal = -Normal;
	}
	GetRWNormalTexture(C)[DispatchID] = float4(Normal * 0.5 + 0.5, 1);
#else

	// Reference: https://atyuwen.github.io/posts/normal-reconstruction/
	// Horizontal 4 points
	float4 H = float4(
		TapDepthFiltered(C, TexCoords - int2(1, 0)),
		TapDepthFiltered(C, TexCoords + int2(1, 0)),
		TapDepthFiltered(C, TexCoords - int2(2, 0)),
		TapDepthFiltered(C, TexCoords + int2(2, 0))
	);
	float2 HError = abs(2 * H.xy - H.zw - Depth);
	float3 HDerivative = 0;
	if(H.x && H.z && HError.x < HError.y) {
		float3 A = RecoverWorldSpacePosition(C, TexCoords - int2(1, 0) + 0.5f.xx, H.x);
		float3 B = RecoverWorldSpacePosition(C, TexCoords - int2(2, 0) + 0.5f.xx, H.z);
		HDerivative = normalize(B - A);
	} else {
		float3 A = RecoverWorldSpacePosition(C, TexCoords + int2(1, 0) + 0.5f.xx, H.y);
		float3 B = RecoverWorldSpacePosition(C, TexCoords + int2(2, 0) + 0.5f.xx, H.w);
		HDerivative = normalize(A - B); 
	}
	// Vertical 4 points
	float4 V = float4(
		TapDepthFiltered(C, TexCoords - int2(0, 1)),
		TapDepthFiltered(C, TexCoords + int2(0, 1)),
		TapDepthFiltered(C, TexCoords - int2(0, 2)),
		TapDepthFiltered(C, TexCoords + int2(0, 2))
	);
	float2 VError = abs(2 * V.xy - V.zw - Depth);
	float3 VDerivative = 0;
	if(V.x && V.z && VError.x < VError.y) {
		float3 A = RecoverWorldSpacePosition(C, TexCoords - int2(0, 1) + 0.5f.xx, V.x);
		float3 B = RecoverWorldSpacePosition(C, TexCoords - int2(0, 2) + 0.5f.xx, V.z);
		VDerivative = normalize(B - A);
	} else {
		float3 A = RecoverWorldSpacePosition(C, TexCoords + int2(0, 1) + 0.5f.xx, V.y);
		float3 B = RecoverWorldSpacePosition(C, TexCoords + int2(0, 2) + 0.5f.xx, V.w);
		VDerivative = normalize(A - B); 
	}
	float3 Normal = normalize(cross(HDerivative, VDerivative));
	if(dot(Normal, CameraDirection) > 0) {
		Normal = -Normal;
	}
	GetRWNormalTexture(C)[DispatchID] = float4(Normal * 0.5 + 0.5, 1);
#endif
}

// [numthreads(TILE_SIZE, TILE_SIZE, 1)]
// void FilterNormals (uint2 DispatchID : SV_DispatchThreadID) {
// 	if(DispatchID.x >= UB.ScreenDimensions.x || DispatchID.y >= UB.ScreenDimensions.y) return;
// 	int2 TexelCoords = int2(DispatchID);
// 	float3 Depth012  = 
// }

// Compound ray tracing. Trace rays in screen space first to cull the easy rays 
// and then trace the rest of the rays with 3DGS HWRT.
[numthreads(WAVE_SIZE, 1, 1)]
void TraceRaysInScreenSpace (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= g_RWRayToTraceCountBuffer[0]) return;
	int RayIndex = g_RWRayToTraceListBuffer[DispatchID];
	RayToTrace Ray = FetchRayToTrace(RayIndex, UB.RT_MaxTraceDistance);
	CameraDescription C = GetCameraDescription();
	
	float3 OriginUVW   = TransformPointWithPerspectiveDivide(C.ProjectionView, Ray.Origin);
	float3 TexelNormal = GetTexelNormalFromTexture(GetNormalTexture(C), OriginUVW.xy);

	float NormalBias = 0;
	// Bias along the normal to avoid self-intersecting camera facing scene depth texels
	// HZB traversal uses point filtering, so scene depth texels stick out from the plane they are representing
	{
		float2 CornerUV = OriginUVW.xy + .5f * C.FilmTexelSize;
		float3 CornerWorldPosition = RecoverWorldSpacePosition(C, CornerUV, ZDepthToLinear(C, OriginUVW.z));
		// Project texel corner onto normal
		NormalBias = abs(dot(CornerWorldPosition - Ray.Origin, TexelNormal)) * 2;
	}

	float3 BiasedOrigin = Ray.Origin + NormalBias * TexelNormal;
	float3 RayStartUVW  = TransformPointWithPerspectiveDivide(C.ProjectionView, BiasedOrigin);
	// Skip screen traces if the normal bias pushed our starting point off-screen, as TraceScreen() doesn't handle this
	if (any(RayStartUVW.xy < -1) || any(RayStartUVW.xy > 1)) {
		return;
	}
	
	bool bHit;
	float3 HitUVW;
	float3 LastVisibleUVW;
	float Unused;

	float MaxTraceDistance = UB.SSRT_MaxTraceDistance;
	float RelativeTexelThickness = UB.SSRT_RelativeTexelThickness;

	ScreenSpaceRayTrace(
		C,
		GetZDepthTexture(C),
		GetNearHZBTexture(C),
		BiasedOrigin,
		Ray.Direction,
		MaxTraceDistance, 
		UB.SSRT_MaxNumIterations,
		RelativeTexelThickness,
		0,
		bHit,
		HitUVW,
		LastVisibleUVW,
		Unused
	);

	bool bFastMoving = false;
	float3 HitWorldPosition = RecoverWorldSpacePosition(C, HitUVW.xy, ZDepthToLinear(C, HitUVW.z));
	float HitDistance = min(length(HitWorldPosition - BiasedOrigin), MaxTraceDistance);

	if (bHit)
	{
		float2 NoiseUV = float2(
			DispatchID % 1024,
			DispatchID / 1024
		) + 0.5f.xx;
		float Noise = InterleavedGradientNoise(NoiseUV, UB.FrameIndex);
		// No vignetting for screen traces for now.
		if (bHit)
		{
			float3 HistoryUVW = ReprojectToHistoryUVWFromUVW(C, HitUVW);
			if(all(HistoryUVW.xy >= 0 && all(HistoryUVW.xy <= 1))) {
				// Calculate the expected depth of the pixel last frame
				float PrevZDepth  = HistoryUVW.z;

				// Lookup the actual depth at the same screen position last frame
				float HistoryZDepth = GetPreviousZDepthTexture(C).SampleLevel(g_PointClampSampler, HistoryUVW.xy, 0).x;

				bHit = abs(HistoryZDepth - PrevZDepth) < RelativeTexelThickness * 0.5f * lerp(.5f, 2.0f, Noise);
			}
		}

		if (bHit)
		{
			float3 HistoryUVW = ReprojectToHistoryUVWFromUVW(C, HitUVW);
			float3 Radiance = GetPreviousRadianceTexture(C).SampleLevel(g_PointClampSampler, HistoryUVW.xy, 0).xyz;
			g_RWRayToTraceResultBuffer[DispatchID] = Radiance;
		}
	}

	if (bHit)
	{
		WriteRayTraceFlags(DispatchID, bHit, HitDistance);
	}
}

[numthreads(WAVE_SIZE, 1, 1)]
void CompactRayTraces (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= g_RWRayToTraceCountBuffer[0]) return;
	int RayIndex = g_RWRayToTraceListBuffer[DispatchID];
	RayToTrace Ray = FetchRayToTrace(RayIndex, UB.RT_MaxTraceDistance);
	if(!Ray.bHit) {
		int RayCount = WaveActiveCountBits(1);
		int RayWarpRank  = WavePrefixCountBits(1);
		int RayBaseRank = 0;
		if(WaveIsFirstLane()) {
			InterlockedAdd(g_RWCompactedRayToTraceCountBuffer[0], RayCount, RayBaseRank);
		}
		RayBaseRank = WaveReadLaneFirst(RayBaseRank);
		int NewRayRank = RayBaseRank + RayWarpRank;
		g_RWCompactedRayToTraceListBuffer[NewRayRank] = RayIndex;
	}
}

// [numthreads(TILE_SIZE, TILE_SIZE, 1)]
// void TemporalDenoise (uint2 DispatchID : SV_DispatchThreadID) {
// 	if(DispatchID.x >= UB.ScreenDimensions.x || DispatchID.y >= UB.ScreenDimensions.y) return;
// 	float2 Momentum = g_RW_GMomentumTexture[DispatchID].xy;
// 	CameraDescription C = GetCameraDescription();
// 	float3 WorldPosition = 
// }

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void FinalComposition (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	// TODO
	// I simply copy the color buffer to the final buffer
	// for now.
	float4 RadianceW = GetRWColorTexture(C)[DispatchID];
	if(UB.DebugMode == 1) {
		
    } else if(UB.DebugMode == 2) {
        RadianceW.rgb = g_GMaterialTexture.Load(int3(DispatchID, 0)).rrr;
    } else if(UB.DebugMode == 3) {
        RadianceW.rgb = g_GNormalTexture.Load(int3(DispatchID, 0)).xyz;
    } else if(UB.DebugMode == 4) {
		float Depth = g_GDepthTexture.Load(int3(DispatchID, 0)).r * 0.2f;
        RadianceW = float4(Depth.xxx, 1);
    } else if(UB.DebugMode == 4) {
        float Alpha = g_GColorTexture.Load(int3(DispatchID, 0)).a;
        RadianceW = float4(Alpha.xxx, 1);
    }
	float3 ViewDirection = -NDC2ToCameraDirection(C, FilmToNDC2(C, DispatchID + 0.5f.xx));
	float3 SkyRadiance = EvaluateSkyRadiance(ViewDirection);
	GetRWRadianceTexture(C)[DispatchID] = float4(
		RadianceW.rgb + SkyRadiance * (1.f - RadianceW.w),
		RadianceW.w
	);
}


// Spawn rays starting from the camera
// For 3DGS HWRT testing purposes only.
// Dispatched 1 group per a small tile
[numthreads(WAVE_SIZE, 1, 1)]
void SpawnCameraRays (uint GroupID : SV_GroupID, uint LocalID : SV_GroupThreadID) {
	if(GroupID == 0 && LocalID == 0) {
		g_RWRayToTraceCountBuffer[0] = UB.ScreenDimensions.x * UB.ScreenDimensions.y;
	}
	// Pack rays in 8x8 small tiles for better cache coherence when tracing a
	// bunch of rays
	int2 TileCoords = int2(GroupID % UB.SmallTileDimensions.x, GroupID / UB.SmallTileDimensions.x);
	for(int TileBaseTexelIndex = 0; TileBaseTexelIndex < SMALL_TILE_SIZE * SMALL_TILE_SIZE; TileBaseTexelIndex += WAVE_SIZE) {
		int TileTexelIndex = TileBaseTexelIndex + LocalID;
		int2 TexelCoords = int2(
			TileTexelIndex % SMALL_TILE_SIZE,
			TileTexelIndex / SMALL_TILE_SIZE
		) + TileCoords * SMALL_TILE_SIZE;
		
		float2 ScreenPosition = float2(TexelCoords) + 0.5f;

		RayToTrace Ray = SpawnCameraRay(UB.MainCamera, ScreenPosition);
		Ray.Seed = UB.HWRT_StochasticRayTracingQuality * BlueNoise_Sample1D(TexelCoords, UB.FrameIndex);
		int RayIndex = TexelCoords.x + TexelCoords.y * UB.ScreenDimensions.x;
		g_RWRayToTraceListBuffer[RayIndex] = RayIndex;
		WriteRayToTrace(RayIndex, Ray);
	}
}

// Display the camera rays trace results on the screen
[numthreads(WAVE_SIZE, 1, 1)]
void DisplayCameraRays (uint GroupID : SV_GroupID, uint LocalID : SV_GroupThreadID) {
	int2 TileCoords = int2(GroupID % UB.SmallTileDimensions.x, GroupID / UB.SmallTileDimensions.x);
	for(int TileBaseTexelIndex = 0; TileBaseTexelIndex < SMALL_TILE_SIZE * SMALL_TILE_SIZE; TileBaseTexelIndex += WAVE_SIZE) {
		int TileTexelIndex = TileBaseTexelIndex + LocalID;
		int2 TexelCoords = int2(
			TileTexelIndex % SMALL_TILE_SIZE,
			TileTexelIndex / SMALL_TILE_SIZE
		) + TileCoords * SMALL_TILE_SIZE;
		
		int RayIndex = TexelCoords.x + TexelCoords.y * UB.ScreenDimensions.x;
		if(UB.VisualizeShadingRays) {
			float4 RayResult = FetchRayTraceResult(RayIndex);
			g_RW_Radiance[TexelCoords] = float4(RayResult.xyz, 1);
		} else {
			float  RayT = FetchRayTraceHitT(RayIndex) * 0.2f;
			g_RW_Radiance[TexelCoords] = float4(RayT.xxx, 1);
		}
	}
}

[numthreads(WAVE_SIZE, 1, 1)]
void GenerateRTMesh (uint DispatchID : SV_DispatchThreadID) {
	int GaussianIndex = DispatchID;
	if(GaussianIndex >= UB.NumGaussians) return ;
	
	Gaussian G = FetchGaussian(GaussianIndex);
	float4x4 ToWorld = 0;
	{
		float3x3 MS = float3x3(
			float3(G.Scale.x, 0, 0),
			float3(0, G.Scale.y, 0),
			float3(0, 0, G.Scale.z)
		);
		float3x3 MR = EvaluateRotationMatrix(G.Rotation);
		float3x3 M = mul(MR, MS);

		ToWorld = float4x4(
			float4(M[0], G.Position.x),
			float4(M[1], G.Position.y),
			float4(M[2], G.Position.z),
			float4(0.xxx, 1)
		);
	}

	// Magic scaling number mentioned in the paper
	float AlphaMin = UB.HWRT_MinAlphaForGaussianEvaluation;
	float Sigma    = UB.GaussianRTProxyGeometrySigma;
	float MagicScale = sqrt(2 * log(Sigma / max(AlphaMin, 0.001f)));

	const float3 IcoVertices[12] = {
		float3(0.000000, -1.000000, 0.000000),
		float3(0.723600, -0.447215, 0.525720),
		float3(-0.276385, -0.447215, 0.850640),
		float3(-0.894425, -0.447215, 0.000000),
		float3(-0.276385, -0.447215, -0.850640),
		float3(0.723600, -0.447215, -0.525720),
		float3(0.276385, 0.447215, 0.850640),
		float3(-0.723600, 0.447215, 0.525720),
		float3(-0.723600, 0.447215, -0.525720),
		float3(0.276385, 0.447215, -0.850640),
		float3(0.894425, 0.447215, 0.000000),
		float3(0.000000, 1.000000, 0.000000)
	};
	const int3 IcoFaces[20] = {
		int3(0, 1, 2),
		int3(1, 0, 5),
		int3(0, 2, 3),
		int3(0, 3, 4),
		int3(0, 4, 5),
		int3(1, 5, 10),
		int3(2, 1, 6),
		int3(3, 2, 7),
		int3(4, 3, 8),
		int3(5, 4, 9),
		int3(1, 10, 6),
		int3(2, 6, 7),
		int3(3, 7, 8),
		int3(4, 8, 9),
		int3(5, 9, 10),
		int3(6, 10, 11),
		int3(7, 6, 11),
		int3(8, 7, 11),
		int3(9, 8, 11),
		int3(10, 9, 11)
	};

	// Emit the vertices
	int VertexBase = GaussianIndex * 12;
	for(int i = 0; i < 12; i++) {
		float3 Vertex = mul(ToWorld, float4(IcoVertices[i] * MagicScale, 1)).xyz;
		g_RW_RTVertexBuffer[VertexBase + i] = Vertex;
	}
	// Emit the indices
	int IndexBase = GaussianIndex * 60;
	int IndexOffset = GaussianIndex * 12;
	for(int i = 0; i < 20; i++) {
		int3 Face = IcoFaces[i];
		g_RW_RTIndexBuffer[IndexBase + i * 3 + 0] = Face.x + IndexOffset;
		g_RW_RTIndexBuffer[IndexBase + i * 3 + 1] = Face.y + IndexOffset;
		g_RW_RTIndexBuffer[IndexBase + i * 3 + 2] = Face.z + IndexOffset;
	}
}

#endif // USING_3DGS_RT