#include "3dgs.hlsl"

#include "material_evaluation.hlsl"

#include "material.hlsl"

#include "ssrt.hlsl"

#include "lightgrid.hlsl"

#include "card.hlsl"

#include "probes.hlsl"

#include "random.hlsl"
#include "radiometry.hlsl"
#include "spherical_harmonics.hlsl"

#include "hashgrids.hlsl"

[numthreads(1, 1, 1)]
void GenerateDispatchRaysIndirect () {
	DispatchRaysIndirectCommand Cmd = (DispatchRaysIndirectCommand)0;
	Cmd.RayGenerationShaderRecord = UB.RT_RayGenerationShaderRecord;
	Cmd.MissShaderTable = UB.RT_MissShaderTable;
	Cmd.HitGroupTable = UB.RT_HitGroupTable;
	Cmd.CallableShaderTable = UB.RT_CallableShaderTable;
	Cmd.Width  = g_RaysToDispatchCountBuffer[0];
	Cmd.Height = 1;
	Cmd.Depth  = 1;
	g_RWDispatchRaysIndirectCommandBuffer[0] = Cmd;
}

[numthreads(1, 1, 1)]
void GenerateDispatchIndirect () {
	DispatchIndirectCommand Cmd = (DispatchIndirectCommand)0;

	Cmd.ThreadGroupCountX = (g_ThreadsToDispatchCountBuffer[0] + UB.IndirectThreadGroupSize - 1) / UB.IndirectThreadGroupSize;
	Cmd.ThreadGroupCountY = 1;
	Cmd.ThreadGroupCountZ = 1;
	g_RWDispatchIndirectCommandBuffer[0] = Cmd;
}

[numthreads(1, 1, 1)]
void GenerateDrawIndirect () {
	DrawIndirectCommand Cmd = (DrawIndirectCommand)0;
	Cmd.VertexCount = g_VertexToDrawCountBuffer[0];
	Cmd.InstanceCount = 1;
	Cmd.StartVertex = 0;
	Cmd.StartInstance = 0;
	g_RWDrawIndirectCommandBuffer[0] = Cmd;
}

uint4 GetOverlappingTiles (float2 ScreenPosition, float Radius) {
	float2 MinTexCoords = ScreenPosition - Radius;
	float2 MaxTexCoords = ScreenPosition + Radius;
	// Convert to tile coords
	int2 MinTileCoords = floor(MinTexCoords / TILE_SIZE);
	int2 MaxTileCoords = ceil(MaxTexCoords  / TILE_SIZE);
	MinTileCoords = clamp(MinTileCoords, 0, UB.TileDimensions);
	MaxTileCoords = clamp(MaxTileCoords, 0, UB.TileDimensions);
	return uint4(MinTileCoords, MaxTileCoords);
}

[numthreads(WAVE_SIZE, 1, 1)]
void ClearCounters () {
	g_RWActiveGaussianCountBuffer[0] = 0;
	g_RWProbeUpdateRayHitShadeCountBuffer[0] = 0;
	g_HashGrids_ActiveTileCountBuffer[0] = 0;
	g_HashGrids_UpdateTileCountBuffer[0] = 0;
	g_RWAdaptiveProbeCountBuffer[0] = 0;
}

// Manually set by dispatches
uint g_CurrentInstanceIndex;

// Filter the active gaussians that are visible in the view frustrum
[numthreads(WAVE_SIZE, 1, 1)]
void FilterActiveGaussians (uint DispatchID : SV_DispatchThreadID) {

	// OPTIMIZE: also filter out the gaussians that failed the visibility test
	// for RasterizationDepth and history depth buffer.
#ifdef CARD_SHADERS
	uint InstanceIndex = MCUB.CardSetIndex;
	uint InstanceBaseGaussianIndex = g_InstanceGaussianIndexOffsetBuffer[InstanceIndex];
	uint InstanceNumGaussians = g_InstanceGaussianCountBuffer[InstanceIndex];
	if(DispatchID >= InstanceNumGaussians) return;
	uint GaussianIndex = InstanceBaseGaussianIndex + DispatchID;
	float3x4 Transform = g_InstanceTransformBuffer[InstanceIndex];
#else
	uint InstanceIndex = g_CurrentInstanceIndex;
	uint InstanceBaseGaussianIndex = g_InstanceGaussianIndexOffsetBuffer[InstanceIndex];
	uint InstanceNumGaussians = g_InstanceGaussianCountBuffer[InstanceIndex];
	if(DispatchID >= InstanceNumGaussians) return ;
	uint GaussianIndex = InstanceBaseGaussianIndex + DispatchID;
	float3x4 Transform = g_InstanceTransformBuffer[InstanceIndex];
#endif

    Gaussian G = FetchGaussian(GaussianIndex);
	float3 TransformedPosition = TransformPoint(Transform, G.Position);


	float3 ViewSpacePosition = 0;
	// We only clip gaussians by their positions in this pass.
	if(IsPointInFrustrum(
		GetCameraDescription(), TransformedPosition, ViewSpacePosition,
		 false, GetCameraDescription().NearPlane, 0.1f
	)) {
		int GaussianCount = WaveActiveCountBits(1);
		int GaussianRank  = WavePrefixCountBits(1);
		int GaussianBaseIndex = 0;
		if(WaveIsFirstLane()) {
			InterlockedAdd(g_RWActiveGaussianCountBuffer[0], GaussianCount, GaussianBaseIndex);
		}
		GaussianBaseIndex = WaveReadLaneFirst(GaussianBaseIndex);
		// Store the indices of active gaussians into a list.
		int ActiveListIndex = GaussianBaseIndex + GaussianRank;

		g_RWActiveGaussianListBuffer[ActiveListIndex] = PackActiveGaussianIndex(InstanceIndex, GaussianIndex);
		g_RWActiveGaussianIndirectSrcBuffer[ActiveListIndex] = ActiveListIndex;
		// The view space align the view direction with the negative z axis
		float LinearDepth = - ViewSpacePosition.z;
		g_RWActiveGaussianLinearDepthSrcBuffer[ActiveListIndex] = LinearDepth;
	}
}

[numthreads(WAVE_SIZE, 1, 1)]
void ProjectActiveGaussians (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= g_RWActiveGaussianCountBuffer[0]) return;
	int ActiveIndex = DispatchID; // Not sorted for now, so we can use the dispatch id directly
	int GaussianIndex, InstanceIndex;
	UnpackActiveGaussianIndex(g_RWActiveGaussianListBuffer[ActiveIndex], InstanceIndex, GaussianIndex);
    
    CameraDescription C = GetCameraDescription();
    Gaussian G = FetchGaussian(GaussianIndex);
    SymmetricMatrix Cov3D = ComputeCovarianceMatrix(G.Scale, G.Rotation);
    // Project to 2D covariance
#ifndef CARD_SHADERS
	// Employ EWA jacobian if the camera is perspective.
    float3x3 J = EWAJacobian2(G.Position, C.FieldOfView, C.View);
#else
	// Orthographic projection jacobian
	// It's the inverse of the scales of the object (in object space)
	float2 InvScales = abs(float2(C.Projection[0][0], C.Projection[1][1])); 
	float3x3 J = float3x3(
        InvScales.x, 0, 0,
        0, InvScales.y, 0,
        0, 0, 0
    );
#endif

	float4x4 InstanceTransform4x4 = ExpandMatrixWithIdentities(g_InstanceTransformBuffer[InstanceIndex]);
	float4x4 ToViewTransform = mul(C.View, InstanceTransform4x4);
	float4x4 ToNDCTransform = mul(C.ProjectionView, InstanceTransform4x4);
    float4 HomogeneousW = mul(C.ProjectionView, float4(G.Position, 1.f));
    float3 Homogeneous = HomogeneousW.xyz / HomogeneousW.w;

    // Get the covariance matrix in NDC space ([-1, 1] ^ 2)
    float3 Cov2D = ProjectCovarianceMatrixToNDC(
        J, Cov3D, ToViewTransform
    );

	{
		// 24.12.16: Expand the 2d projection of the gaussian.
		// The data we rendered is trained by a forwarding process with such biasing.
		// So we must expand the gaussian in the same way, otherwise there're
		// empty holes in the output.
		const float H_Var = 0.3f; // The magic number from the original implementation
		// Convert to NDC space for our method
		float VarScaleX = 2.f / C.FilmDimensions.x;
		float VarScaleY = 2.f / C.FilmDimensions.y;
		VarScaleX = VarScaleX * VarScaleX;
		VarScaleY = VarScaleY * VarScaleY;
		float H_VarX = H_Var * VarScaleX;
		float H_VarY = H_Var * VarScaleY;
		Cov2D.x += H_VarX;
		Cov2D.z += H_VarY;
	}

    float  Det           = Cov2D.x * Cov2D.z - Cov2D.y * Cov2D.y;

#ifndef OUTPUT_PBR_G_BUFFER
	SHCoefficents3 SH3 = FetchGaussianSHCoefficients(GaussianIndex, 2);
	float3 ViewDirection = normalize(C.Position - G.Position);
	float3 Color = SH3Evaluate(ViewDirection, SH3, 2);
	g_RWActiveGaussianColorBuffer[ActiveIndex] = Color;
#endif

    // Compute extent in screen space (by finding eigenvalues of
    // 2D covariance matrix). Use extent to compute a bounding rectangle
    // of screen-space tiles that this Gaussian overlaps with. Quit if
    // rectangle covers 0 tiles. 
    // Eigenvalues of 2D covariance matrix denotes the variance of the 
    // Gaussian in the directions of the eigenvectors, which are the
    // principal axes of the Gaussian. 
    float Mean    = 0.5f * (Cov2D.x + Cov2D.z);
	float Discriminant = sqrt(max(0.0f, Mean * Mean - Det));
    float Lambda1 = Mean + Discriminant;
    float Lambda2 = Mean - Discriminant;
    // Find the eigenvectors of the covariance matrix
    float2 Eigenvector1 = float2(Cov2D.y, Lambda1 - Cov2D.x);
    float2 Eigenvector2 = float2(Cov2D.y, Lambda2 - Cov2D.x);
    Eigenvector1 = normalize(Eigenvector1);
    Eigenvector2 = normalize(Eigenvector2);
	// Output the projected quad vectors
	// OPTIMIZE: scale the vectors according to opacity of the gaussian
	float2 ClampedPosition = saturateDown(Homogeneous.xy * 0.25 + 0.5f);
	g_RWActiveGaussianNDCPositionBuffer[ActiveIndex] = PackUnorm16x2(ClampedPosition);
	float LinearDepth = g_RWActiveGaussianLinearDepthSrcBuffer[ActiveIndex];
	// Clamp the radius for gaussians (to fix holes for the dataset)
	// TODO: this is totally a data-specific trick. But I found it useful.
	// Otherwise my renderer is visually inconsistent with the original one intensively...
#ifdef CARD_SHADERS
	float Bias = UB.Card_GaussianClampingScale / InvScales.x;
#else
	float Bias = UB.GaussianClampingScale / LinearDepth;
#endif
	Lambda1 = abs(Lambda1) + Bias*Bias;
	Lambda2 = abs(Lambda2) + Bias*Bias;
 	// Larger objects have larger clamping scale
	float SqrLambda1 = sqrt(Lambda1);
	float SqrLambda2 = sqrt(Lambda2);
    float2 ClampedVector1 = Eigenvector1 * SqrLambda1;
	g_RWActiveGaussianQuadNDCVector0Buffer[ActiveIndex] = PackUnorm16x2(saturateDown(ClampedVector1 * 0.5 + 0.5));
	float2 ClampedVector2 = Eigenvector2 * SqrLambda2;
	g_RWActiveGaussianQuadNDCVector1Buffer[ActiveIndex] = PackUnorm16x2(saturateDown(ClampedVector2 * 0.5 + 0.5));
}

// OPTIMIZE: fine-grain culling (using history HZB)


// The active list indirection buffer is sorted according to their linear depth
// And sent to rasterization.

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void ResolveGBuffers (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	float2 DepthUnnormalized = GetRWDepthTexture(C)[DispatchID].xy;
	float Weight = DepthUnnormalized.y;
	float Depth = DepthUnnormalized.x / max(Weight, 1e-6f);
	float Opacity = GetRWColorTexture(C)[DispatchID].w;
	bool bEmpty = Opacity < UB.OpaqueThreshold;
	if(bEmpty) {
		// Empty pixel.
		Depth = 0;
	}
	// Depth
	GetRWDepthTexture(C)[DispatchID].x = Depth;
	// If the normals are reconstructed from the depth, they are not rendered to the GBuffer
#ifndef RECONSTRUCT_NORMALS_FROM_DEPTH
	// Normalize rendered normals
	float3 Normal = GetRWNormalTexture(C)[DispatchID].xyz / max(Weight, 1e-6f);
	Normal = Normal * 2 - 1;
	if(any(Normal != -1)) {
		Normal = normalize(Normal);
	}
	GetRWNormalTexture(C)[DispatchID] = float4(Normal * 0.5 + 0.5, 1);
#endif
}

float TapDepth (CameraDescription C, int2 TapCoords) {
	TapCoords = clamp(TapCoords, 0, C.FilmDimensions - 1);
	return GetDepthTexture(C).Load(int3(TapCoords, 0)).r;
}

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void FilterDepth (uint2 DispatchID : SV_DispatchThreadID) {
	// fp16 low quality depth -> fp32 filtered depth
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	float SumWeight = 0;
	float SumDepth  = 0;
	bool  bTransparent = false;
	for(int dx = -UB.DepthFilterRadius; dx <= UB.DepthFilterRadius; dx++) {
		for(int dy = -UB.DepthFilterRadius; dy <= UB.DepthFilterRadius; dy++) {
			int2 TapCoords = DispatchID + int2(dx, dy);
			if(IsOutOfFilm(C, TapCoords)) continue;
			float Depth  = TapDepth(C, TapCoords);
			float Opacity = GetColorTexture(C).Load(int3(TapCoords, 0)).w;
			if(Opacity < UB.OpaqueThreshold) {
				if(dx == 0 && dy == 0) {
					bTransparent = true;
				}
				continue;
			}
			float Weight = Opacity * (1.f / (1 + abs(dx) + abs(dy)));
			SumWeight += Weight;
			SumDepth  += Depth * Weight;
		}
	}
	
	if(SumWeight <= UB.OpaqueThreshold || bTransparent) SumDepth = 0;
	float FilteredDepth = SumDepth / max(SumWeight, 1e-6f);
	GetRWFilteredDepthTexture(C)[DispatchID] = FilteredDepth;
	// float ZDepth = FilteredDepth == 0 ? ZDEPTH_INF : LinearToZDepth(C, FilteredDepth);
	// GetRWZDepthTexture(C)[DispatchID] = ZDepth;
}

// Combine the GBuffers rendered via gaussians and regular mesh.
[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void CombineGBuffers (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	float4 EmissionA = GetRWEmissionAlphaTexture(C)[DispatchID];
	float RegularOpacity  = EmissionA.w;
	float GaussianOpacity = GetRWColorTexture(C)[DispatchID].w;
	// Filtered depth
	float GaussianFilteredDepth = GetRWFilteredDepthTexture(C)[DispatchID].r;
	float RegularZDepth = GetRasterizationDepthTexture(C).Load(int3(DispatchID, 0)).r;
	float RegularLinearDepth = 0;
	if(RegularZDepth < 1) RegularLinearDepth = ZDepthToLinear(C, RegularZDepth);
	float LerpingFactor = 0;
#if false
	LerpingFactor = RegularOpacity == 0 ? 0 : (1 - GaussianOpacity);
#else
	// The geometry produced should be discrete rather than "smooth"
	// Otherwise SSRT and shading will be greatly affected.
	LerpingFactor = (GaussianOpacity < UB.OpaqueThreshold) ? 0 : 1;
#endif
	float NewFilteredDepth = lerp(RegularLinearDepth, GaussianFilteredDepth, LerpingFactor);
	GetRWFilteredDepthTexture(C)[DispatchID] = NewFilteredDepth;
	// ZDepth, will be 1 + eps when the pixel is transparent
	float ZDepth = NewFilteredDepth == 0 ? ZDEPTH_INF : LinearToZDepth(C, NewFilteredDepth);
	GetRWZDepthTexture(C)[DispatchID] = ZDepth;
	// Gaussians are not emissive.
	float3 GaussianEmission = 0.f;
	GetRWEmissionAlphaTexture(C)[DispatchID].rgb = lerp(EmissionA.rgb, GaussianEmission, LerpingFactor);
	// Normal is naturally blended (or being reconstructed from depth later)
	// Accumulate opacities
	GetRWColorTexture(C)[DispatchID].w = RegularOpacity + GaussianOpacity;
}

Texture2D<float> g_InNearHZBTexture;
RWTexture2D<float> g_OutNearHZBTexture;

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void GenerateNearHZB (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	uint2 Dimensions = 0;
	g_InNearHZBTexture.GetDimensions(Dimensions.x, Dimensions.y);
	if(any(DispatchID * 2 >= Dimensions)) return;
	float2 GatherUV = (DispatchID * 2 + 0.5f) / Dimensions;
	float4 ZDepths = g_InNearHZBTexture.GatherRed(g_PointClampSampler, GatherUV);
	float  MinZDepth = min(
		min(ZDepths.x, ZDepths.y),
		min(ZDepths.z, ZDepths.w)
	);
	g_OutNearHZBTexture[DispatchID] = MinZDepth;
}

float TapDepthFiltered (CameraDescription C, int2 TapCoords) {
	TapCoords = clamp(TapCoords, 0, C.FilmDimensions - 1);
	return GetFilteredDepthTexture(C).Load(int3(TapCoords, 0)).r;
}

// Reconstruct the normal texture from depth texture, so we dont have to rasterize normals.
// Overdraws from 3DGS are huge burdens on output mergers.
[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void ReconstructNormals (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	int2   TexCoords = int2(DispatchID);
	float  Depth = TapDepthFiltered(C, TexCoords);
	float3 CameraDirection = NDC2ToCameraDirection(C, FilmToNDC2(C, TexCoords + 0.5f.xx));
	
#ifndef HIGH_QUALITY_NORMAL_RECONSTRUCTION

	float4 Depths = float4(
		TapDepthFiltered(C, TexCoords - int2(1, 0)),
		TapDepthFiltered(C, TexCoords + int2(1, 0)),
		TapDepthFiltered(C, TexCoords - int2(0, 1)),
		TapDepthFiltered(C, TexCoords + int2(0, 1))
	);
	float3 Left  = RecoverWorldSpacePosition(C, TexCoords - int2(1, 0) + 0.5f.xx, Depths.x);
	float3 Right = RecoverWorldSpacePosition(C, TexCoords + int2(1, 0) + 0.5f.xx, Depths.y);
	float3 Up    = RecoverWorldSpacePosition(C, TexCoords - int2(0, 1) + 0.5f.xx, Depths.z);
	float3 Down  = RecoverWorldSpacePosition(C, TexCoords + int2(0, 1) + 0.5f.xx, Depths.w);
	float3 HorizontalDerivative = normalize(Right - Left);
	float3 VerticalDerivative = normalize(Down - Up);
	float3 Normal = normalize(cross(HorizontalDerivative, VerticalDerivative));
	if(dot(Normal, CameraDirection) > 0) {
		Normal = -Normal;
	}
	GetRWNormalTexture(C)[DispatchID] = float4(Normal * 0.5 + 0.5, 1);
#else

	// Reference: https://atyuwen.github.io/posts/normal-reconstruction/
	// Horizontal 4 points
	float4 H = float4(
		TapDepthFiltered(C, TexCoords - int2(1, 0)),
		TapDepthFiltered(C, TexCoords + int2(1, 0)),
		TapDepthFiltered(C, TexCoords - int2(2, 0)),
		TapDepthFiltered(C, TexCoords + int2(2, 0))
	);
	float2 HError = abs(2 * H.xy - H.zw - Depth);
	float3 HDerivative = 0;
	if(H.x && H.z && HError.x < HError.y) {
		float3 A = RecoverWorldSpacePosition(C, TexCoords - int2(1, 0) + 0.5f.xx, H.x);
		float3 B = RecoverWorldSpacePosition(C, TexCoords - int2(2, 0) + 0.5f.xx, H.z);
		HDerivative = normalize(B - A);
	} else {
		float3 A = RecoverWorldSpacePosition(C, TexCoords + int2(1, 0) + 0.5f.xx, H.y);
		float3 B = RecoverWorldSpacePosition(C, TexCoords + int2(2, 0) + 0.5f.xx, H.w);
		HDerivative = normalize(A - B); 
	}
	// Vertical 4 points
	float4 V = float4(
		TapDepthFiltered(C, TexCoords - int2(0, 1)),
		TapDepthFiltered(C, TexCoords + int2(0, 1)),
		TapDepthFiltered(C, TexCoords - int2(0, 2)),
		TapDepthFiltered(C, TexCoords + int2(0, 2))
	);
	float2 VError = abs(2 * V.xy - V.zw - Depth);
	float3 VDerivative = 0;
	if(V.x && V.z && VError.x < VError.y) {
		float3 A = RecoverWorldSpacePosition(C, TexCoords - int2(0, 1) + 0.5f.xx, V.x);
		float3 B = RecoverWorldSpacePosition(C, TexCoords - int2(0, 2) + 0.5f.xx, V.z);
		VDerivative = normalize(B - A);
	} else {
		float3 A = RecoverWorldSpacePosition(C, TexCoords + int2(0, 1) + 0.5f.xx, V.y);
		float3 B = RecoverWorldSpacePosition(C, TexCoords + int2(0, 2) + 0.5f.xx, V.w);
		VDerivative = normalize(A - B); 
	}
	float3 Normal = normalize(cross(HDerivative, VDerivative));
	if(dot(Normal, CameraDirection) > 0) {
		Normal = -Normal;
	}
	GetRWNormalTexture(C)[DispatchID] = float4(Normal * 0.5 + 0.5, 1);
#endif
}

// [numthreads(TILE_SIZE, TILE_SIZE, 1)]
// void FilterNormals (uint2 DispatchID : SV_DispatchThreadID) {
// 	if(DispatchID.x >= UB.ScreenDimensions.x || DispatchID.y >= UB.ScreenDimensions.y) return;
// 	int2 TexelCoords = int2(DispatchID);
// 	float3 Depth012  = 
// }


[numthreads(1, 1, 1)]
void InitializeCounters () {
	g_LightGrid_GridLightListAllocator[0] = 0;
}

// Update light headers (mainly grid local positions) for each light 
// Because the grid bounds may be modified by the camera movement and jittering
// also the lights may be moved.
[numthreads(WAVE_SIZE, 1, 1)]
void UpdateLightHeaders (uint DispatchID : SV_DispatchThreadID) {
	uint NumLights = GetNumLights();
	// Ignore the first two lights (directional and sky light)
	if(DispatchID >= NumLights) return;
	int LightIndex = DispatchID;
	LightData LD = FetchLightDetails(LightIndex); 
	Light L = (Light)0;
	L.Type      = LIGHT_TYPE_AREA;
	if(DispatchID == 0) {
		L.Type = LIGHT_TYPE_DIRECTIONAL;
		L.Intensity = Luminance(LD.Radiance);
		L.Normal = normalize(LD.V1);
	} else if(DispatchID == 1) {
		L.Type = LIGHT_TYPE_SKY;
		float SumLuminance = 0;
		// Sample the average radiance of all faces of the sky box
		for(int i = 0; i < 6; i++) {
			float3 Direction = GetSkyBoxDirection(i);
			float3 Radiance = EvaluateSkyRadiance(Direction, 99.f);
			SumLuminance += Luminance(Radiance);
		}
		L.Intensity = SumLuminance / 6 * PI;
	} else {
		float3 WorldCenter = (LD.V1 + LD.V2 + LD.V3) / 3;
		uint4 GridIndex = LightGrid_GetGridIndex(WorldCenter);
		if(IsInvalid(GridIndex.w)) return ;
		float  GridSize;
		float3 GridMin = LightGrid_GetGridBounds(GridIndex, GridSize);
		float3 LocalCenter = saturateDown((WorldCenter - GridMin) / GridSize);
		float Area = length(cross(LD.V2 - LD.V1, LD.V3 - LD.V1)) * 0.5f;
		L.Intensity = Luminance(LD.Radiance) * Area;
		L.GridIndex = GridIndex;
		L.LocalPosition = LocalCenter;
		L.Normal = normalize(cross(LD.V2 - LD.V1, LD.V3 - LD.V1));
	}
	WriteLightHeader(LightIndex, L);
}

[numthreads(WAVE_SIZE, 1, 1)]
void InjectLights (uint DispatchID : SV_DispatchThreadID) {
	uint NumLights = GetNumLights();
	uint4 GridIndex = LightGrid_GetGridIndex(DispatchID);
	if(GridIndex.w >= UB.LightGrid_NumGridCascades) return ;
	float3 GridMin; 
	float GridSize;
	GridMin = LightGrid_GetGridBounds(GridIndex, GridSize);
	float GridLightWeight[LIGHT_GRID_MAX_NUM_GRID_LIGHTS];
	uint  GridLightIndices[LIGHT_GRID_MAX_NUM_GRID_LIGHTS];
	// Bias the initial weight to avoid precision issues
	float GridLightWeightSum = 1e-7f;
	float SampledReservoirsWeightSum = 0.f;
	// Scatter random numbers for RIS.
	Random rng = MakeRandom(9918293 + DispatchID, UB.FrameIndex);
	int LastLight, AcceptedLightCount = 0;
	for(LastLight = 0; LastLight < NumLights && AcceptedLightCount < LIGHT_GRID_MAX_NUM_GRID_LIGHTS; LastLight++) {
		Light L = FetchLightHeader(LastLight);
		float LightWeight = EstimateLightGridContribution(L, GridMin, GridSize);
		if(LightWeight >= UB.LightGrid_MinLightContributionForInjection) {
			GridLightWeight[AcceptedLightCount] = LightWeight;
			GridLightIndices[AcceptedLightCount] = LastLight;
			GridLightWeightSum += LightWeight;
			AcceptedLightCount ++;
		}
	}
	[unroll(LIGHT_GRID_MAX_NUM_GRID_LIGHTS)]
	for(int i = AcceptedLightCount; i < LIGHT_GRID_MAX_NUM_GRID_LIGHTS; i++) {
		GridLightWeight[i] = 0;
		GridLightIndices[i] = 0xffffffffu;
	}
	SampledReservoirsWeightSum = GridLightWeightSum;
	// O(MxN) Brute force algorithm. Assume that there're not many lights
	for(uint ItLightIndex = LastLight; ItLightIndex < NumLights; ItLightIndex ++) {
		Light L = FetchLightHeader(ItLightIndex);
		float LightWeight = EstimateLightGridContribution(L, GridMin, GridSize);
		if(LightWeight >= UB.LightGrid_MinLightContributionForInjection) {
			float NewGridLightWeightSum = GridLightWeightSum + LightWeight;
			float LightAcceptProbability = LightWeight / NewGridLightWeightSum;
			float U = rng.rand();
			if(LightAcceptProbability > U) {
				U = (U - LightAcceptProbability) / (1 - LightAcceptProbability);
				float P = U * SampledReservoirsWeightSum;
				// Multi-reservoir sampling using LightWeight / TotalWeight as target cdf.
				uint LightIndex = ItLightIndex;
				for(int i = 0; i < LIGHT_GRID_MAX_NUM_GRID_LIGHTS; i++) {
					P -= GridLightWeight[i];
					if(P <= 0) {
						SampledReservoirsWeightSum += LightWeight - GridLightWeight[i];
						GridLightWeight[i] = LightWeight;
						GridLightIndices[i] = LightIndex;
						break;
					}
				}
			}
			GridLightWeightSum = NewGridLightWeightSum;
		}
	}
	// Write back
	int NumGridLights = 0;
	for(int i = 0; i < LIGHT_GRID_MAX_NUM_GRID_LIGHTS; i++) {
		if(GridLightIndices[i] != 0xffffffffu) {
			NumGridLights ++;
		} else break;
	}
	int LightGridListIndexBase = 0;
	InterlockedAdd(g_LightGrid_GridLightListAllocator[0], NumGridLights, LightGridListIndexBase);
	g_LightGrid_GridLightListOffsetBuffer[DispatchID] = LightGridListIndexBase;
	// Clamp the number of lights to avoid overflowing the list buffer
	NumGridLights = min(NumGridLights, UB.LightGrid_MaxNumEntries - LightGridListIndexBase);
	g_LightGrid_GridLightCountBuffer[DispatchID] = NumGridLights;
	for(int i = 0; i < NumGridLights; i++) {
		int LightGridListIndex = LightGridListIndexBase + i;
		g_LightGrid_GridLightListBuffer[LightGridListIndex] = GridLightIndices[i];
	}
}

struct LightSample {
	int LightType;
	// If the sampled light is infinitely far, position is replaced by direction.
	float3 Position;
	float  Pdf;
	float3 Radiance;

	bool IsValid () {
		return Pdf > 0;
	}
};

Material FetchMaterial (CameraDescription C, uint2 TexelCoords) {
	Material Result = MakeMaterial(0.f, 0.f);
	Result.Normal = GetNormalTexture(C).Load(int3(TexelCoords, 0)).xyz;
	Result.Normal = normalize(Result.Normal * 2 - 1);
	float4 AlbedoAlpha = GetColorTexture(C).Load(int3(TexelCoords, 0));
	Result.Albedo = AlbedoAlpha.xyz;
	Result.Alpha = AlbedoAlpha.w;
	Result.Roughness = GetMaterialTexture(C).Load(int3(TexelCoords, 0)).x;
	return Result;
}

LightSample SampleLightWithCosineWeight (float3 Position, Material M, uint LightType, LightData LD, float2 u2) {
	LightSample Result = (LightSample) 0;
	Result.LightType = LightType;
	if(LightType == LIGHT_TYPE_DIRECTIONAL) {
		Result.Position = LD.V1;
		float CosineFactor = saturate(dot(LD.V1, M.Normal));
		Result.Radiance = LD.Radiance * CosineFactor;
		Result.Pdf = 1.f;
	} else if(LightType == LIGHT_TYPE_SKY) {
		Result.Position = SampleSkyLight(M.Normal, u2, Result.Pdf);
		float CosineFactor = saturate(dot(Result.Position, M.Normal));
		Result.Radiance = EvaluateSkyRadiance(-Result.Position) * CosineFactor;
	} else if(LightType == LIGHT_TYPE_AREA) {
		Result.Position = SampleAreaLightArea(LD.V1, LD.V2, LD.V3, u2, Result.Pdf);
		// Convert area pdf to solid angle pdf
		float  Distance = length(Result.Position - Position);
		float3 Direction   = normalize(Result.Position - Position);
		float3 LightNormal = normalize(cross(LD.V2 - LD.V1, LD.V3 - LD.V1));
		float Cosine = dot(LightNormal, -Direction);
		float ReceiverCosine = dot(Direction, M.Normal);
		Result.Pdf *= Distance * Distance / abs(Cosine);
		Result.Radiance = LD.Radiance * saturate(Cosine) * saturate(ReceiverCosine);
	}
	return Result;
}

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void SampleLightRays (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	// No need to jitter film positions (already done in the rasterization pass via TAA)
	float2 FilmPosition = DispatchID + 0.5f.xx;
	float  LinearDepth  = GetFilteredDepthTexture(C).Load(int3(DispatchID, 0)).r;
	// Empty pixel
	if(LinearDepth == 0) {
		return ;
	}
	float3 Origin = RecoverWorldSpacePosition(C, FilmPosition, LinearDepth);

	// Sample lights using light grid
	uint4 GridIndex      = LightGrid_GetGridIndex(Origin);
	float GridSize;
	float3 GridMin = LightGrid_GetGridBounds(GridIndex, GridSize);
	uint  WaveGridIndex1 = LightGrid_GetGridIndex1(GridIndex);

	if(UB.Debug_VisualizeLightGridCascade && !IsInvalid(GridIndex.w)) {
		int Level = 2;
		bool bInGrid = all(UB.LightGrid_GridCascadeMin[Level].rgb <= Origin) && all(Origin < UB.LightGrid_GridCascadeMax[Level].rgb);
		g_RW_DebugTexture[DispatchID] =  bInGrid ? 1 : 0;//float(1 + GridIndex.w) / UB.LightGrid_NumGridCascades;
	}

	Material M = FetchMaterial(C, DispatchID);

	uint  SampledLightIndex = 0xffffffffu;
	float SampledLightResampleWeight = 0;
	float SumResampleWeights = 0;
	LightSample ReservedSample = (LightSample) 0;
	uint  Seed = DispatchID.x + (DispatchID.y * C.FilmDimensions.x);
	Random rng = MakeRandom(Seed ^ 0x51f49a7cu, UB.FrameIndex);

	// Filter out invalid pixels falling outside of the light grid
	bool bSampled = IsInvalid(GridIndex.w);
	int Iteration = 0;

	// Cooperative sampling
	while(Iteration < 16) {
		uint MinGridIndex1 = WaveActiveMin(bSampled ? 0x7fffffffu : WaveGridIndex1);
		// Sample lights for the pixels within the same light grid with minimum id.
		// Other threads keep idle.
		// It's likely that a tile is covered by a single light grid as light grids are large.
		// So the memory reads can be effectively broadcasted to all threads.
		if(!bSampled && WaveGridIndex1 == MinGridIndex1) {
			float U = rng.rand();
			int NumGridLights = g_LightGrid_GridLightCountBuffer[WaveGridIndex1];
			int LightGridListOffset = g_LightGrid_GridLightListOffsetBuffer[WaveGridIndex1];
			// float GridLightSumWeight = g_LightGrid_GridLightSumWeightBuffer[GridIndex1];
			// Resample grid lights using luminance as the weight
			for(int i = 0; i < NumGridLights; i++) {
				int LightIndex = g_LightGrid_GridLightListBuffer[LightGridListOffset + i];
				Light L = FetchLightHeader(LightIndex);
				// We have to produce a full sample of the light to accurately estimate the light contribution
				LightData   Details = FetchLightDetails(LightIndex);
				// Note: the returned sample is already cosine weighted
				float2 u2 = rng.rand2();
				LightSample Sample  = SampleLightWithCosineWeight(Origin, M, L.Type, Details, u2);
				// Ignore sky light (we regard sky light as an indirect light source due to it's 
				// low frequency nature)
				if(L.Type == LIGHT_TYPE_SKY) Sample.Pdf = 0;
				if(Sample.IsValid()) {
					float LightGridWeight = EstimateLightGridContribution(L, GridMin, GridSize);
					float LightCurrWeight = Luminance(Sample.Radiance / Sample.Pdf);
					// RIS
					float ResampleWeight  = LightCurrWeight / max(LightGridWeight, 1e-7f);
					if(ResampleWeight > UB.LightGrid_MinResampleWeightForDirectIllumiation) {
						float NewSumResampleWeights = SumResampleWeights + ResampleWeight;
						float CurrentLightU = ResampleWeight / NewSumResampleWeights;
						if(CurrentLightU > U) {
							U /= CurrentLightU;
							ReservedSample = Sample;
							SampledLightResampleWeight = ResampleWeight;
						} else {
							U *= 1.f - CurrentLightU;
						}
						SumResampleWeights = NewSumResampleWeights;
					}
				}
			}
			bSampled = true;
		}
		// All the pixels are sampled. Break.
		if(WaveActiveAllTrue(bSampled)) {
			break;
		}
		Iteration ++;
	}

	// Okay we have a sample for each pixel. Now encode a shadow ray for visibility testing.
	
	if(ReservedSample.IsValid()) {

		// Calculate the real sample contribution. (Picking 1 single light from a bunch of lights)
		// float LightCdf = 1.f / SumResampleWeights;//SampledLightResampleWeight / SumResampleWeights;
		// float LightCdf = 1.f / GetNumLights();
		// float NormalizationFactor = Luminance(ReservedSample.Radiance / ReservedSample.Pdf);
		ReservedSample.Radiance *= SumResampleWeights / (ReservedSample.Pdf * SampledLightResampleWeight);//NormalizationFactor;// * (1.f / LightCdf) / ReservedSample.Pdf;

		// ReservedSample.Radiance = normalize(ReservedSample.Radiance);

		// Spawn shadow ray
		float3 Direction = 0;
		float OcclusionThreshold = 0;
		if(IsInfinitelyFarLightType(ReservedSample.LightType)) {
			Direction = ReservedSample.Position;
			OcclusionThreshold = UB.RT_MaxTraceDistance;
		} else {
			Direction = normalize(ReservedSample.Position - Origin);
			OcclusionThreshold = length(ReservedSample.Position - Origin);
		}
		// Allocate rays
		int RayIndex = 0;
		{
			int RayIndexBase = 0;
			int RayWarpCount = WaveActiveCountBits(1);
			int RayWarpRank  = WavePrefixCountBits(1);
			if(WaveIsFirstLane()) {
				InterlockedAdd(g_RWRayToTraceCountBuffer[0], RayWarpCount, RayIndexBase);
			}
			RayIndexBase = WaveReadLaneFirst(RayIndexBase);
			RayIndex = RayIndexBase + RayWarpRank;
		}
		// Write ray to memory for compound ray tracing
		RayToTrace Ray = InitRayToTrace(UB.RT_MaxTraceDistance);
		// Ray.Origin = Origin;
		Ray.Direction = Direction;
		Ray.Seed = BlueNoise_Sample1D(DispatchID, UB.FrameIndex) * UB.HWRT_StochasticRayTracingQuality;
		WriteRayToTrace(RayIndex, Ray, false);
		g_RWRayToTraceUVPositionBuffer[RayIndex] = PackUnorm16x2(FilmPosition / C.FilmDimensions);
		g_RWRayToTraceListBuffer[RayIndex] = RayIndex;
		// Keep in mind the occulusion threshold for direct illumination visibility testing
		g_RWDirectIlluminationRayOcclusionThresholdBuffer[RayIndex] = OcclusionThreshold;
		// Store the sample contribution for direct illumination (if it passed the visibility test)
		g_RWDirectIlluminationRayContributionBuffer[RayIndex] = PackRadianceA16(float4(ReservedSample.Radiance, 1.f));
	}
}

// Compound ray tracing. Trace rays in screen space first to cull the easy rays 
// and then trace the rest of the rays with 3DGS HWRT.
[numthreads(WAVE_SIZE, 1, 1)]
void TraceRaysInScreenSpace (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= g_RWRayToTraceCountBuffer[0]) return;
	int RayIndex = g_RWRayToTraceListBuffer[DispatchID];
	RayToTrace Ray = FetchRayToTrace(RayIndex, UB.RT_MaxTraceDistance, false);
#ifndef SSRC_PROBE_UPDATE_RAY_TRACING
	// Shadow ray tracing for DI
	{
		// Manually recover the origin from the screen position
		float2 FilmPosition = UnpackUnorm16x2(g_RWRayToTraceUVPositionBuffer[RayIndex])
			* GetCameraDescription().FilmDimensions;
		float  LinearDepth = GetFilteredDepthTexture(GetCameraDescription()).Load(int3(FilmPosition, 0)).r;
		Ray.Origin = RecoverWorldSpacePosition(GetCameraDescription(), FilmPosition, LinearDepth);
	}
#else
	// SSRC probe update ray tracing for indirect illumination
	{
		// Unpack the trace origin from probe headers
		int2 ProbeIndex = GetProbeUpdateRayProbeIndex(RayIndex);
		float3 ProbeWorldPosition = GetScreenProbePosition(ProbeIndex);
		Ray.Origin = ProbeWorldPosition;
	}
#endif

	CameraDescription C = GetCameraDescription();
	
	float3 OriginUVW   = TransformPointWithPerspectiveDivide(C.ProjectionView, Ray.Origin);
	OriginUVW.xy = NDC2ToUV(OriginUVW.xy);
	float3 TexelNormal = normalize(
		2 * GetNormalTexture(C).SampleLevel(g_PointClampSampler, OriginUVW.xy, 0).xyz - 1
	);

	float NormalBias = 0;
	// Bias along the normal to avoid self-intersecting camera facing scene depth texels
	// HZB traversal uses point filtering, so scene depth texels stick out from the plane they are representing
	{
		float2 CornerUV = OriginUVW.xy + .5f * C.FilmTexelSize;
		float3 CornerWorldPosition = RecoverWorldSpacePositionNDC2(C, UVToNDC2(CornerUV), ZDepthToLinear(C, OriginUVW.z));
		// Project texel corner onto normal
		NormalBias = abs(dot(CornerWorldPosition - Ray.Origin, TexelNormal)) * 2;
	}

	float3 BiasedOrigin = Ray.Origin + NormalBias * TexelNormal;
	float3 RayStartUVW  = TransformPointWithPerspectiveDivide(C.ProjectionView, BiasedOrigin);
	RayStartUVW.xy = NDC2ToUV(RayStartUVW.xy);
	// Skip screen traces if the normal bias pushed our starting point off-screen, as TraceScreen() doesn't handle this
	if (any(RayStartUVW.xy < 0) || any(RayStartUVW.xy >= 1)) {
		return;
	}
	
	bool bHit;
	float3 HitUVW;
	float3 LastVisibleUVW;
	float Unused;

	float MaxTraceDistance = UB.SSRT_MaxTraceDistance;
	float RelativeTexelThickness = UB.SSRT_RelativeTexelThickness;

	ScreenSpaceRayTrace(
		C,
		GetZDepthTexture(C),
		GetNearHZBTexture(C),
		BiasedOrigin,
		Ray.Direction,
		// normalize(float3(0, 1, 1)),
		MaxTraceDistance, 
		UB.SSRT_MaxNumIterations,
		RelativeTexelThickness,
		0,
		bHit,
		HitUVW,
		LastVisibleUVW,
		Unused
	);

	float3 HitWorldPosition = RecoverWorldSpacePositionNDC2(C, UVToNDC2(HitUVW.xy), ZDepthToLinear(C, HitUVW.z));
	float HitDistance = min(length(HitWorldPosition - BiasedOrigin), MaxTraceDistance);

	if (bHit)
	{
		float2 NoiseUV = float2(
			RayIndex % 1024,
			RayIndex / 1024
		) + 0.5f.xx;
		float Noise = InterleavedGradientNoise(NoiseUV, UB.FrameIndex);
		// No vignetting for screen traces for now.
		if (bHit)
		{
			float3 PreviousUVW = ReprojectToPreviousUVWFromUVW(C, HitUVW);
			if(all(PreviousUVW.xy >= 0) && all(PreviousUVW.xy < 1)) {
				// Calculate the expected depth of the pixel last frame
				float PrevZDepth  = PreviousUVW.z;

				// Lookup the actual depth at the same screen position last frame
				float HistoryZDepth = GetHistoryZDepthTexture(C).SampleLevel(g_PointClampSampler, PreviousUVW.xy, 0).x;

				bHit = abs(HistoryZDepth - PrevZDepth) < RelativeTexelThickness * 0.5f * lerp(.5f, 2.0f, Noise);
			}
		}
#ifdef SSRC_PROBE_UPDATE_RAY_TRACING
		if (bHit)
		{
			float3 PreviousUVW = ReprojectToPreviousUVWFromUVW(C, HitUVW);
			if(all(PreviousUVW.xy >= 0) && all(PreviousUVW.xy < 1)) {
				float3 Radiance = g_HistoryRadianceWithoutEmission.SampleLevel(g_PointClampSampler, PreviousUVW.xy, 0).xyz;
				ProbeUpdateRayResult Result = FetchProbeUpdateRayResult(RayIndex);
				Result.Radiance = Radiance;
				Result.bBypass  = true;
				WriteProbeUpdateRayResult(RayIndex, Result);
				// float3 Normal = normalize(
				// 	GetHistoryNormalTexture(C).SampleLevel(g_PointClampSampler, PreviousUVW.xy, 0).xyz * 2 - 1
				// );
				// g_RWRayToTraceResultNormalBuffer[RayIndex] = PackNormal(Normal);
			}
		}
#endif
	}

	// Remember to reduce the texel relative thickness on SSRT if there're too many false hits.
	
	WriteRayTraceFlags(RayIndex, bHit, HitDistance);
}

[numthreads(WAVE_SIZE, 1, 1)]
void CompactRayTraces (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= g_RWRayToTraceCountBuffer[0]) return;
	int RayIndex = g_RWRayToTraceListBuffer[DispatchID];
	// Ray origin is not used so we do not need to fetch it.
	RayToTrace Ray = FetchRayToTrace(RayIndex, UB.RT_MaxTraceDistance, false);
	if(!Ray.bHit) {
		int RayCount = WaveActiveCountBits(1);
		int RayWarpRank  = WavePrefixCountBits(1);
		int RayBaseRank = 0;
		if(WaveIsFirstLane()) {
			InterlockedAdd(g_RWCompactedRayToTraceCountBuffer[0], RayCount, RayBaseRank);
		}
		RayBaseRank = WaveReadLaneFirst(RayBaseRank);
		int NewRayRank = RayBaseRank + RayWarpRank;
		g_RWCompactedRayToTraceListBuffer[NewRayRank] = RayIndex;
		// Backward a little bit for ray continuation.
		// FIXME
		// float RayTMinBiased = max(Ray.RayTMin * 0.4f, Ray.RayTMin - 0.4f);
		float RayTMinBiased = Ray.RayTMin;
		WriteRayTraceFlags(RayIndex, Ray.bHit, RayTMinBiased);
	}
}

[numthreads(WAVE_SIZE, 1, 1)]
void ResolveDirectLighting (uint DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(DispatchID >= g_RWRayCountBuffer[0]) return;

	// Splat ray origins onto the film
	int RayIndex = DispatchID;
	RayToTrace Ray = FetchRayToTrace(RayIndex, UB.RT_MaxTraceDistance, false);
	float2 FilmPosition = UnpackUnorm16x2(g_RWRayToTraceUVPositionBuffer[RayIndex]) * C.FilmDimensions;
	int2   PixelCoords  = int2(FilmPosition);

#ifndef NDEBUG
	{
		// Build the mapping from pixel to ray index for debugging
		int PixelIndex = PixelCoords.x + PixelCoords.y * C.FilmDimensions.x;
		g_Debug_DirectIlluminationPixelRayIndexBuffer[PixelIndex] = RayIndex;
	}
#endif
	
	if(IsOutOfFilm(C, PixelCoords)) return;

	Material M = FetchMaterial(C, PixelCoords);

	// Transparent
	if(M.Alpha < UB.OpaqueThreshold) {
		GetRWDirectIlluminationTexture(C)[PixelCoords] = 0.f.xxxx;
		return;
	}

	float  Threshold = g_RWDirectIlluminationRayOcclusionThresholdBuffer[RayIndex];
	float  Noise = BlueNoise_Sample1D(PixelCoords, UB.FrameIndex, 1);
	Threshold *= lerp(UB.DI_OcclusionThresholdMinFactor, UB.DI_OcclusionThresholdMaxFactor, Noise);
	float3 Radiance = UnpackRadianceA16(g_RWDirectIlluminationRayContributionBuffer[RayIndex]).xyz;
	Radiance *= (Threshold < Ray.RayTMin) ? 1 : 0;

	GetRWDirectIlluminationTexture(C)[PixelCoords] = float4(Radiance, 1);
	// Pixels with no valid samples will have a sample count of 0.
}

// Similar to Lumen
float GetFilterPositionWeight(float NeighborLinearDepth, float LinearDepth)
{
	float DepthDifference = abs(NeighborLinearDepth - LinearDepth);
	float RelativeDepthDifference = DepthDifference / LinearDepth;
	return exp2(-1000.f * (RelativeDepthDifference * RelativeDepthDifference));
}

// Used to specify the filter pass
// Hard coded 2 pass a-trous filter for now.
#ifndef FILTER_PASS
#define FILTER_PASS 0
#endif

#ifndef FILTER_RADIUS
#define FILTER_RADIUS 2
#endif

float NormalWeight (float3 NormalA, float3 NormalB) {
	return pow(saturate(dot(NormalA, NormalB)), 4);

}

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void SpatialFilterDirectIllumination (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	int2 PixelCoords = int2(DispatchID);
	Material M = FetchMaterial(C, PixelCoords);
	if(M.Alpha < UB.OpaqueThreshold) {
		return;
	}
	float  PixelLinearDepth = GetFilteredDepthTexture(C).Load(int3(PixelCoords, 0)).r;
	float3 PixelNormal = normalize(GetNormalTexture(C).Load(int3(PixelCoords, 0)).xyz - 0.5f);
	float3 SumRadiance = 0;
	float SumWeight = 0;

#if FILTER_PASS == 0
	Texture2D<float4> Input = GetDirectIlluminationTexture(C);
#else
	Texture2D<float4> Input = GetFilteredDirectIlluminationTexture(C);
#endif

	int StepSize = 1 << FILTER_PASS;

	// int Count = 2 * UB.DI_FilterRadius * (UB.DI_FilterRadius + 1) + 1;
	for(int dy = -FILTER_RADIUS; dy <= FILTER_RADIUS; dy++) {
		int L = FILTER_RADIUS - abs(dy);
		for(int dx = -L; dx <= L; dx ++) {
			int2 Offset = int2(dx, dy) * StepSize;
			int2 TexelCoords = PixelCoords + Offset;
			if(IsOutOfFilm(C, TexelCoords)) continue;
			float  NeighborLinearDepth = GetFilteredDepthTexture(C).Load(int3(TexelCoords, 0)).r;
			float3 NeighborNormal = normalize(GetNormalTexture(C).Load(int3(TexelCoords, 0)).xyz - 0.5f);
			bool   bIsNeightborTransparent = NeighborLinearDepth == 0;
			float3 NeighborRadiance = Input.Load(int3(TexelCoords, 0)).rgb;
			float Weight = GetFilterPositionWeight(NeighborLinearDepth, PixelLinearDepth);
			float GaussianKernelWeight = exp(-dot(Offset, Offset) * UB.DI_InvFilterGaussianRadius2);
			Weight *= GaussianKernelWeight;
			Weight *= NormalWeight(PixelNormal, NeighborNormal);
			Weight *= bIsNeightborTransparent ? 0 : 1;

			SumRadiance += NeighborRadiance * Weight;
			SumWeight += Weight;
		}
	}
#if FILTER_PASS == 0
	RWTexture2D<float4> Output = GetRWFilteredDirectIlluminationTexture(C);
#else
	RWTexture2D<float4> Output = GetRWDirectIlluminationTexture(C);
#endif
	Output[PixelCoords] = float4(SumRadiance / SumWeight, SumWeight);
}

// Indirect illumination

[numthreads(WAVE_SIZE, 1, 1)]	
void SSRC_ResetHashGrids (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= UB.HashGrids_MaxNumTiles) return;
	if(DispatchID == 0) {
		g_HashGrids_HistoryActiveTileCountBuffer[0] = 0;
		g_HashGrids_FreeTileCountBuffer[0] = UB.HashGrids_MaxNumTiles;
	}
	g_HashGrids_FreeTileListBuffer[DispatchID] = UB.HashGrids_MaxNumTiles - DispatchID - 1;
}

[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_ReInsertHashGridTiles (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= g_HashGrids_HistoryActiveTileCountBuffer[0]) return;
	int TileIndex = g_HashGrids_HistoryActiveTileListBuffer[DispatchID];
	uint CurrentTimestamp = UB.FrameIndex + 1;
	uint TileTimestamp = g_HashGrids_TileTimestampBuffer[TileIndex];
	bool bShouldFreeTile = false;
	if(TileTimestamp + UB.HashGrids_TileLifespan < CurrentTimestamp) {
		bShouldFreeTile = true;
	}
	// Keep the tile (and insert to the hash table)
	uint TileBucketHash  = g_HashGrids_TileBucketHashBuffer[TileIndex];
	bool bIsNewSlot = false;
	uint SlotIndex = INVALID_U32;
	if(!bShouldFreeTile) {
		// The hash table has been cleared, so just simply re-insert all living tiles
		// Try to insert the tile to the hash table
		SlotIndex = HashGrids_FindAndAllocate(TileBucketHash, bIsNewSlot);
	}
	if(IsInvalid(SlotIndex)) {
		// The hash table is full, we have to drop the tile
		bShouldFreeTile = true;
	}
	if(bShouldFreeTile) {
		// Free the tile
		int FreeListIndex;
		InterlockedAdd(g_HashGrids_FreeTileCountBuffer[0], 1, FreeListIndex);
		g_HashGrids_FreeTileListBuffer[FreeListIndex] = TileIndex;
		return ;
	}
	// Theorietically, this should always be true otherwise hash collision occurs
	if(bIsNewSlot) {
		// Register the tile on the active list
		int ActiveListIndex;
		InterlockedAdd(g_HashGrids_ActiveTileCountBuffer[0], 1, ActiveListIndex);
		g_HashGrids_ActiveTileListBuffer[ActiveListIndex] = TileIndex;
		// Insert the tile to the hash table
		g_HashGrids_BucketHashBuffer[SlotIndex] = TileBucketHash;
		g_HashGrids_BucketTileIndexBuffer[SlotIndex] = TileIndex;
	}
}

// SSRC probe allocation

float3 GetProbeOffsetAdaptiveNormal (int2 ScreenCoords, float3 GeometryNormal, float3 ViewDirection) {
    float3 AdaptiveNormal = ViewDirection;//normalize(ViewDirection + GeometryNormal);
#if false
    // Fine-tune the normal to bent normal when close to occluded regions
    float4 BentNormalOcc  = g_BentNormalAndOcclusionTexture.Load(int3(ScreenCoords, 0));
    float  Occlusion      = BentNormalOcc.w;
    float3 BentNormal     = BentNormalOcc.xyz * 2 - 1;
    AdaptiveNormal = normalize(lerp(BentNormal, AdaptiveNormal, saturate(1.5 * Occlusion * Occlusion)));
#endif
    return AdaptiveNormal;
}

// Allocate fixed uniform probes for current frame
[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_AllocateUniformProbes (int DispatchID : SV_DispatchThreadID) {
    if(DispatchID > UB.SSRC_NumUniformScreenProbes) {
        return;
    }
	CameraDescription C = GetCameraDescription();
    int2 ProbeIndex = int2(DispatchID % UB.TileDimensions.x, DispatchID / UB.TileDimensions.x);
    ProbeHeader Header  = (ProbeHeader) 0;
    Header.ScreenCoords = GetUniformScreenProbeScreenCoords(ProbeIndex);
    float LinearDepth   = GetFilteredDepthTexture(C).Load(int3(Header.ScreenCoords, 0)).x;
    bool  bValid        = LinearDepth != 0;

    // Negative depths stands for invalid probes
    Header.LinearDepth   = bValid ? LinearDepth : -1;
    // High resolution recovery for accurate probe placement (otherwise may cause artifacts because of inaccurate occlusions)
    float3 WorldPosition  = RecoverWorldSpacePosition(C, Header.ScreenCoords + 0.5f, LinearDepth);
    // Offset the probe along adaptive "normal".
    float3 Normal         = normalize(GetNormalTexture(C).Load(int3(Header.ScreenCoords, 0)).xyz * 2.f - 1.f);
    float3 ViewDirection  = normalize(C.Position - WorldPosition);
    float3 AdaptiveNormal = GetProbeOffsetAdaptiveNormal(Header.ScreenCoords, Normal, ViewDirection);
    float3 ProbePositionOffset = AdaptiveNormal * Header.LinearDepth * SSRC_PROBE_NORMAL_OFFSET;
    Header.Position      = WorldPosition + ProbePositionOffset;
    Header.Normal        = Normal;
    WriteScreenProbeHeader(ProbeIndex, Header);

    // Also, clear the tile adaptive probe count for later adaptive allocation
    g_RWTileAdaptiveProbeCountTexture[ProbeIndex] = 0;
}

float3 RecoverScreenProbePosition (int2 TileCoords, float LinearDepth, bool bPrevious) {
    // We are using the camera coordinate system to recover probe position, which is placed with G-Buffer samples
    // We need to take care of the jittering as the camera coordinate system is not affected by TAA (but the G-Buffer is). 
    float2 UV = GetUniformScreenProbeScreenUV(TileCoords, bPrevious) + (bPrevious ? UB.PreviousTAAJitterUV : UB.TAAJitterUV);
    float2 NDC2 = UVToNDC2(UV);
    if(!bPrevious) {
        return RecoverWorldSpacePositionNDC2(GetCameraDescription(), NDC2, LinearDepth);
    } else {
        return RecoverWorldSpacePositionNDC2(GetCameraDescription(true), NDC2, LinearDepth);
    }
}

void CalculateSSRCSampleWeightsForUniformScreenProbes (
    float2 ScreenPosition,
    float3 Position,
    float  LinearDepth,
    float3 Normal,
    bool bScreenSpaceWeight,
    out int2 TileCoordsX00,
    out float4 Weights,
    bool bPrevious = false
) {
    float2 ScreenPositionProbeGrid = ScreenPosition - 0.5f - GetTileJitter(bPrevious);
    int2 ScreenCoordsProbeGrid     = clamp(ScreenPositionProbeGrid, 0, UB.ScreenDimensions - TILE_SIZE - 1);
    TileCoordsX00         = min(ScreenCoordsProbeGrid / TILE_SIZE, UB.TileDimensions - 2);
    // Pad the bilinear filtering weights
#ifdef DEBUG_MIN_PROBE_REPROJECTION
    int BilinearExpand = 0;
#else
    // Values larger than 1 causes SG to leak into neighboring probes
    // 0903: However we just need this to fix darkening around sharp edges of geometries.
    int BilinearExpand = 1;
#endif
    float2 Bilinear    = 
        (clamp(ScreenPositionProbeGrid - TileCoordsX00 * TILE_SIZE, 0, TILE_SIZE) + BilinearExpand) 
        / (float)(TILE_SIZE + 2 * BilinearExpand);
    float4 CornerLinearDepths;
    CornerLinearDepths.x = GetScreenProbeLinearDepth(TileCoordsX00 + int2(0, 0), bPrevious);
    CornerLinearDepths.y = GetScreenProbeLinearDepth(TileCoordsX00 + int2(1, 0), bPrevious);
    CornerLinearDepths.z = GetScreenProbeLinearDepth(TileCoordsX00 + int2(0, 1), bPrevious);
    CornerLinearDepths.w = GetScreenProbeLinearDepth(TileCoordsX00 + int2(1, 1), bPrevious);
    if(bScreenSpaceWeight) Weights = float4(
        (1.f - Bilinear.x) * (1.f - Bilinear.y),
        Bilinear.x * (1.f - Bilinear.y),
        (1.f - Bilinear.x) * Bilinear.y,
        Bilinear.x * Bilinear.y
    );
    else Weights = 1.f.xxxx;
    float4 DepthWeights;
    float4 PixelPlane  = float4(Normal, dot(Position, Normal));
    float3 PositionX00 = RecoverScreenProbePosition(TileCoordsX00 + int2(0, 0), CornerLinearDepths.x, bPrevious);
    float3 PositionX10 = RecoverScreenProbePosition(TileCoordsX00 + int2(1, 0), CornerLinearDepths.y, bPrevious);
    float3 PositionX01 = RecoverScreenProbePosition(TileCoordsX00 + int2(0, 1), CornerLinearDepths.z, bPrevious);
    float3 PositionX11 = RecoverScreenProbePosition(TileCoordsX00 + int2(1, 1), CornerLinearDepths.w, bPrevious);
    float4 PlaneDistances;
    PlaneDistances.x = abs(dot(PixelPlane, float4(PositionX00, -1.f)));
    PlaneDistances.y = abs(dot(PixelPlane, float4(PositionX10, -1.f)));
    PlaneDistances.z = abs(dot(PixelPlane, float4(PositionX01, -1.f)));
    PlaneDistances.w = abs(dot(PixelPlane, float4(PositionX11, -1.f)));
    float4 RelativeDepthDifference = PlaneDistances / LinearDepth;
    // Negative depths stands for invalid probes
    DepthWeights = select(
        CornerLinearDepths > 0, 
        exp2(-10000.0f * (RelativeDepthDifference * RelativeDepthDifference)),
        0.0
    );
    Weights *= DepthWeights;
}

void CalculateSSRCSampleWeights (
    float2 ScreenPosition,
    float3 Position,
    float  LinearDepth,
    float3 Normal,
    bool   bScreenSpaceWeight,
    out SSRC_SampleData Sample,
    bool bPrevious = false
) {
    int2 TileCoordsX00;
    CalculateSSRCSampleWeightsForUniformScreenProbes(
        ScreenPosition,
        Position,
        LinearDepth,
        Normal,
        bScreenSpaceWeight,
        TileCoordsX00,
        Sample.Weights,
        bPrevious
    );
    Sample.Index[0] = TileCoordsX00 + int2(0, 0);
    Sample.Index[1] = TileCoordsX00 + int2(1, 0);
    Sample.Index[2] = TileCoordsX00 + int2(0, 1);
    Sample.Index[3] = TileCoordsX00 + int2(1, 1);
    
    // Weight the adaptive probes and search within the nearest tiles
    {
        float Epsilon = .01f;
		float4 PixelPlane = float4(Normal, dot(Position, Normal));
        for (uint CornerIndex = 0; CornerIndex < 4; CornerIndex++)
		{
			if (Sample.Weights[CornerIndex] <= Epsilon)
			{
				int2 TileCoords = TileCoordsX00 + uint2(CornerIndex % 2, CornerIndex / 2);
				int NumAdaptiveProbes = 
                    bPrevious ? g_RWPreviousTileAdaptiveProbeCountTexture[TileCoords] 
                    : g_RWTileAdaptiveProbeCountTexture[TileCoords];
                [unroll(1 << (SSRC_MAX_ADAPTIVE_PROBE_LAYERS * 2))]
				for (uint AdaptiveProbeListIndex = 0; AdaptiveProbeListIndex < NumAdaptiveProbes; AdaptiveProbeListIndex++)
				{
                    // TODO: reconstruct probe data from G-Buffer to reduce VRAM bandwidth when shading
					int  AdaptiveProbeIndex1 = GetAdaptiveProbeIndex(TileCoords, AdaptiveProbeListIndex, bPrevious);
					int  ScreenProbeIndex1   = AdaptiveProbeIndex1 + UB.SSRC_NumUniformScreenProbes;
                    int2 ScreenProbeIndex    = int2(ScreenProbeIndex1 % UB.TileDimensions.x, ScreenProbeIndex1 / UB.TileDimensions.x);

                    ProbeHeader Header         = GetScreenProbeHeader(ScreenProbeIndex, bPrevious);
					float2 ProbeScreenPosition = Header.ScreenCoords + 0.5f;
					float ProbeLinearDepth     = Header.LinearDepth;
					
					float NewDepthWeight = 0;

                    float3 ProbePosition = Header.Position;
                    float  PlaneDistance = abs(dot(float4(ProbePosition, -1), PixelPlane));
                    float RelativeDepthDifference = PlaneDistance / ProbeLinearDepth;
                    NewDepthWeight = exp2(-10000.0f * (RelativeDepthDifference * RelativeDepthDifference));

					float2 DistanceToScreenProbe = abs(ProbeScreenPosition - ScreenPosition);
					float NewCornerWeight = 1.0f - saturate(min(DistanceToScreenProbe.x, DistanceToScreenProbe.y) / (float)(TILE_SIZE));
					float NewInterpolationWeight = NewDepthWeight * (bScreenSpaceWeight ? NewCornerWeight : 1.f);

					if (NewInterpolationWeight > Sample.Weights[CornerIndex])
					{
						Sample.Weights[CornerIndex] = NewInterpolationWeight;
						Sample.Index[CornerIndex] = ScreenProbeIndex;
					}
				}
			}
		}
    }
}


groupshared int  LocalNumProbesToAllocate;
groupshared int  LocalAdaptiveProbeOffset;
groupshared int2 LocalProbeScreenCoordsToAllocate[WAVE_SIZE];
[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_AllocateAdaptiveProbes (int DispatchID : SV_DispatchThreadID, int LocalID : SV_GroupThreadID) {
    if(UB.SSRC_NoAdaptiveProbes) return ;
// This macro is passed in by compiler arguments
#ifndef SSRC_ADAPTIVE_PROBE_LAYER
#define SSRC_ADAPTIVE_PROBE_LAYER 0
#endif
    const int AdaptiveProbeDownsampleFactor = TILE_SIZE / (2 << SSRC_ADAPTIVE_PROBE_LAYER);
    int2 DownsampledTileDimensions = UB.ScreenDimensions / AdaptiveProbeDownsampleFactor;
    int2 AdaptiveTileCoords = int2(
        DispatchID % DownsampledTileDimensions.x,
        DispatchID / DownsampledTileDimensions.x
    );
    if(WaveIsFirstLane()) {
        LocalNumProbesToAllocate = 0;
    }
    GroupMemoryBarrierWithGroupSync();
	CameraDescription C = GetCameraDescription();

    {
        // Omit the adaptive probe that overlaps with the previous layer
        if(any((AdaptiveTileCoords&1) != 0)) {
            // Compute the screen coords for current adaptive probe
            int2 AdaptiveProbeScreenCoords = AdaptiveTileCoords * AdaptiveProbeDownsampleFactor + GetTileJitter();
            if(all(AdaptiveProbeScreenCoords < UB.ScreenDimensions)) {
                float LinearDepth = GetFilteredDepthTexture(C).Load(int3(AdaptiveProbeScreenCoords, 0)).x;
                bool  bValid = LinearDepth > 0;
                if(bValid) {
                    float3 WorldPosition  = RecoverWorldSpacePosition(C, AdaptiveProbeScreenCoords + 0.5f, LinearDepth);
                    float3 GeometryNormal = normalize(GetNormalTexture(C).Load(int3(AdaptiveProbeScreenCoords, 0)).xyz * 2.f - 1.f);
                    SSRC_SampleData Sample;

                    CalculateSSRCSampleWeights(
                        AdaptiveProbeScreenCoords + 0.5f,
                        WorldPosition,
                        LinearDepth,
                        GeometryNormal,
                        true,
                        Sample
                    );

                    float Epsilon = .01f;
                    Sample.Weights /= max(dot(Sample.Weights, 1), Epsilon);

                    float LightingIsValid = (dot(Sample.Weights, 1) < 1.0f - Epsilon) ? 0.0f : 1.0f;

                    if (!LightingIsValid)
                    {
                        int ListIndex;
                        InterlockedAdd(LocalNumProbesToAllocate, 1, ListIndex);
                        LocalProbeScreenCoordsToAllocate[ListIndex] = AdaptiveProbeScreenCoords;
                    }
                }
            }
        }
    }
    
    GroupMemoryBarrierWithGroupSync();

    // Allocate probes
    if(WaveIsFirstLane()) {
        InterlockedAdd(g_RWAdaptiveProbeCountBuffer[0], LocalNumProbesToAllocate, LocalAdaptiveProbeOffset);
    }

    GroupMemoryBarrierWithGroupSync();
    
    int NumProbeToAllocateClipped = min(max(UB.SSRC_MaxNumAdaptiveProbes - LocalAdaptiveProbeOffset, 0), LocalNumProbesToAllocate);

    int AdaptiveProbeIndex = LocalAdaptiveProbeOffset + LocalID;

    if(LocalID < NumProbeToAllocateClipped) {
        // Allocate the index slot and record the index of the adaptive probe
        int TileAdaptiveProbeRank;
        // Set the tile coords to the tile that the LocalID th probe belongs to
        int2 TileCoords = (LocalProbeScreenCoordsToAllocate[LocalID] - GetTileJitter()) / TILE_SIZE;
        InterlockedAdd(g_RWTileAdaptiveProbeCountTexture[TileCoords], 1, TileAdaptiveProbeRank);
        g_RWTileAdaptiveProbeIndexTexture[GetAdaptiveProbeIndexCoords(TileCoords, TileAdaptiveProbeRank)] = AdaptiveProbeIndex;
        // The probe here is guaranteed to be valid upon allocation.
        int ScreenProbeIndex1 = AdaptiveProbeIndex + UB.SSRC_NumUniformScreenProbes;
        ProbeHeader Header;
        Header.ScreenCoords   = LocalProbeScreenCoordsToAllocate[LocalID];
        float3 GeometryNormal = normalize(GetNormalTexture(C).Load(int3(Header.ScreenCoords, 0)).xyz * 2.f - 1.f);
        float  LinearDepth    = GetFilteredDepthTexture(C).Load(int3(Header.ScreenCoords, 0)).x;
        Header.LinearDepth    = LinearDepth;
        float2 UV = (Header.ScreenCoords + 0.5f) * UB.InvScreenDimensions;
        // High resolution recovery for accurate probe placement (otherwise may cause artifacts because of inaccurate occlusions)
        float3 WorldPosition = RecoverWorldSpacePosition(C, Header.ScreenCoords + 0.5f, LinearDepth);
        float3 ViewDirection = normalize(C.Position - WorldPosition);
        float3 AdaptiveNormal = GetProbeOffsetAdaptiveNormal(Header.ScreenCoords, GeometryNormal, ViewDirection);
        Header.Position      = WorldPosition + AdaptiveNormal * Header.LinearDepth * SSRC_PROBE_NORMAL_OFFSET;
        
        Header.Normal        = GeometryNormal;
        int2 ScreenProbeIndex = int2(ScreenProbeIndex1 % UB.TileDimensions.x, ScreenProbeIndex1 / UB.TileDimensions.x);
        WriteScreenProbeHeader(ScreenProbeIndex, Header);
    }
}

// Write dispatch parameters for SSRC computations
[numthreads(1, 1, 1)]
void SSRC_PrepareProbeProcessing () {
    // Clip the number of allocated adaptive probes
    g_RWAdaptiveProbeCountBuffer[0] = min(g_RWAdaptiveProbeCountBuffer[0], UB.SSRC_MaxNumAdaptiveProbes);

    DispatchIndirectCommand Command = (DispatchIndirectCommand)0;
    Command.ThreadGroupCountX = UB.SSRC_NumUniformScreenProbes + g_RWAdaptiveProbeCountBuffer[0];
    Command.ThreadGroupCountY = 1;
    Command.ThreadGroupCountZ = 1;
    g_RWProbeDispatchCommandBuffer[0] = Command;

    Command.ThreadGroupCountX = (UB.SSRC_NumUniformScreenProbes + g_RWAdaptiveProbeCountBuffer[0] + WAVE_SIZE - 1) / WAVE_SIZE;
    Command.ThreadGroupCountY = 1;
    Command.ThreadGroupCountZ = 1;
    g_RWProbePerLaneDispatchCommandBuffer[0] = Command;

    // Also, set the reduce count for scan sum update rays
    // Pad 1 for the last element
    g_RWProbeUpdateRayReduceCountBuffer[0] = 
        UB.SSRC_NumUniformScreenProbes + g_RWAdaptiveProbeCountBuffer[0] + 1;
}


void SSRC_ResetProbeTexels (int GroupID, int LocalID, int2 ProbeIndex, float3 ProbeNormal) {
    for(int BaseProbeTexelIndex = 0; BaseProbeTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseProbeTexelIndex += WAVE_SIZE) {
        int ProbeTexelIndex = BaseProbeTexelIndex + LocalID;
        int2 ProbeTexelCoords = int2(ProbeTexelIndex % SSRC_PROBE_TEXTURE_SIZE, ProbeTexelIndex / SSRC_PROBE_TEXTURE_SIZE);
        WriteScreenProbeOctahedronRadianceDepth(ProbeIndex, ProbeTexelCoords, float4(0, 0, 0, GetCameraDescription().FarPlane));
    }
    GroupMemoryBarrierWithGroupSync();
}


// Retrieve the sample probes and weights used for reprojecting a probe
bool SSRC_GetProbeReprojectionSample (float3 ProbeNormal, float3 ProbeTangent, float3 ProbeBitangent, float3 ProbePosition, float ProbeLinearDepth, int2 ProbeIndex, bool WriteProbeTrust, out SSRC_SampleData Sample) {
    // Reproject probe to find adjacent 4 probes from the last frame
    float4 PrevHomogeneousW = mul(GetCameraDescription(true).ProjectionView, float4(ProbePosition, 1));
    // The probe is totally out of the screen on the last frame, so we should reset the probe
    if(PrevHomogeneousW.w > 0) {
        float3 PrevHomogeneous = PrevHomogeneousW.xyz / PrevHomogeneousW.w;
        float2 NoiseOffset = 0.f.xx;
        // Jitter the probe position for stochastic reprojection sampling (2x2 -> 3x3)
#if defined(SCREEN_PROBE_TINY_STOCHASTIC_JITTER) && !defined(DEBUG_MIN_PROBE_REPROJECTION)
        NoiseOffset = (BlueNoise_Sample2D(ProbeIndex, MI.FrameSeed) * 2 - 1) * 0.5f;
#endif
        float2 PrevScreenPosition = UB.ScreenDimensions * NDC2ToUV(PrevHomogeneous.xy) + NoiseOffset;
        float2 PrevProbeHistoryDimensionsMin = GetTileJitter(true) + 0.5f;
        float2 PrevProbeHistoryDimensionsMax = UB.ScreenDimensions - TILE_SIZE + GetTileJitter(true) + 0.5f;
        float2 PrevScreenPositionClamped = clamp(PrevScreenPosition, PrevProbeHistoryDimensionsMin, PrevProbeHistoryDimensionsMax);
        // ~~~Exclude screen space weight when doing reprojection (which UE told me to do so...)~~~
        // That will introduce too many bias (colors flowing in a fixed direction in screen space)
        CalculateSSRCSampleWeights(
            PrevScreenPositionClamped,
            ProbePosition,
            ProbeLinearDepth,
            ProbeNormal,
            true, // false,
            Sample,
            true
        );
        float2 OutOfRangeDecay2 = max(
            PrevScreenPosition - PrevProbeHistoryDimensionsMax,
            PrevProbeHistoryDimensionsMin - PrevScreenPosition
        );
        OutOfRangeDecay2 = max(OutOfRangeDecay2, 0.f);
        float OutOfRangeDecay  = max(1.f - 2.f * length(OutOfRangeDecay2) / TILE_SIZE, 0.f);
        // Stochastic noise for the history trust
        float Noise = InterleavedGradientNoise(float2(ProbeIndex) / UB.TileDimensions, UB.FrameIndex);
        // 1.5 ~ 3 probes
        // Noise should not be affecting the trust value... it'll make the cache unstable
        float HistoryTrust = min(dot(Sample.Weights, 1)/* * lerp(0.8f, 1.2f, Noise)*/, 1.f) * OutOfRangeDecay;
        if(WriteProbeTrust && WaveIsFirstLane()) {
            g_RWProbeHistoryTrustTexture[ProbeIndex] = HistoryTrust;
        }
        float Epsilon = .01f;
        Sample.Weights /= max(dot(Sample.Weights, 1), Epsilon);
        // Successful reprojection
        return true;
    }
    return false;
}


// Quantilization
// May overflow if the radiance is too large (e.g. 1000)
int QuantilizeRadiance (float V, float Noise) {
    return floor(sign(V) * min(abs(V), 1000) * 16384 + Noise);
}
float RecoverRadiance (int V) {
    return float(V) / 16384;
}
float3 RecoverRadiance (int3 V) {
    return float3(V) / 16384;
}
float4 RecoverRadiance (int4 V) {
    return float4(V) / 16384;
}
int QuantilizeWeight (float V, float Noise) {
    // 2^17 = 131,072 (fp32: 2^23 precision)
    // Note: InvPdf < 100, no worries about overflowing
    return floor(V * 131072.f + Noise);
}
float RecoverWeight (int V) {
    return float(V) / 131072.f;
}

// Radiance + Weight (sample count)
groupshared int4   LocalProbeTexelsQuantilized[SSRC_PROBE_TEXTURE_SIZE * SSRC_PROBE_TEXTURE_SIZE];
groupshared int    LocalProbeTexelSampleWeightQuantilized[SSRC_PROBE_TEXTURE_SIZE * SSRC_PROBE_TEXTURE_SIZE];
// Initialize probe cache from the previous frame, one group per probe
[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_ReprojectProbeHistory (int LocalID : SV_GroupThreadID, int GroupID : SV_GroupID) {
    int2 ProbeIndex = int2(GroupID % UB.TileDimensions.x, GroupID / UB.TileDimensions.x);
	CameraDescription C = GetCameraDescription();
    ProbeHeader Header = GetScreenProbeHeader(ProbeIndex);
    if(UB.SSRC_ResetCache) {
        if(WaveIsFirstLane()) {
            // Clear probe history
            g_RWProbeHistoryTrustTexture[ProbeIndex] = 0;
        }
        // The reset for probes that have zero trust is delayed to SSRC_UpdateProbes
        return ;
    }
    float3 ProbeTangent, ProbeBitangent;
    GetOrthoVectors(Header.Normal, ProbeTangent, ProbeBitangent);
    
    SSRC_SampleData Sample;
    bool ReprojectionSucceeded = SSRC_GetProbeReprojectionSample(
        Header.Normal, ProbeTangent, ProbeBitangent, 
        Header.Position, Header.LinearDepth, ProbeIndex, 
        true, Sample
    );
    if(!ReprojectionSucceeded) {
        if(WaveIsFirstLane()) {
            // Clear probe history
            g_RWProbeHistoryTrustTexture[ProbeIndex] = 0;
        }
        // The reset for probes that have zero trust is delayed to SSRC_UpdateProbes
        return ;
    }

    // Reproject Octahedron
    {
        float Q_Noise = InterleavedGradientNoise(
			ProbeIndex * SSRC_PROBE_TEXTURE_SIZE + int2(LocalID % SSRC_PROBE_TEXTURE_SIZE, LocalID / SSRC_PROBE_TEXTURE_SIZE),
			UB.FrameIndex
		);

#if SSRC_PROBE_TEXTURE_SIZE * SSRC_PROBE_TEXTURE_SIZE % WAVE_SIZE != 0
#error "SSRC_PROBE_TEXTURE_SIZE * SSRC_PROBE_TEXTURE_SIZE must be a multiple of WAVE_SIZE"
#endif
        for(int BaseProbeTexelIndex = 0; BaseProbeTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseProbeTexelIndex += WAVE_SIZE) {
            int ProbeTexelIndex = BaseProbeTexelIndex + LocalID;
            LocalProbeTexelsQuantilized[ProbeTexelIndex] = 0;
            LocalProbeTexelSampleWeightQuantilized[ProbeTexelIndex] = 0;
        }
        GroupMemoryBarrierWithGroupSync();
        for(int CornerIndex = 0; CornerIndex < 4; CornerIndex++) {
            // A probe with a weight greater than 0 must be valid
            [branch]
            if(Sample.Weights[CornerIndex] > 0) {
                int2 SrcProbeIndex = Sample.Index[CornerIndex];
                ProbeHeader SrcProbeHeader = GetScreenProbeHeader(SrcProbeIndex, true);
                for(int BaseProbeTexelIndex = 0; BaseProbeTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseProbeTexelIndex += WAVE_SIZE) {
                    int SrcTexelIndex = BaseProbeTexelIndex + LocalID;
                    int2 ProbeTexelCoords = int2(SrcTexelIndex % SSRC_PROBE_TEXTURE_SIZE, SrcTexelIndex / SSRC_PROBE_TEXTURE_SIZE); 
                    float4 RadianceDepth = GetScreenProbeOctahedronRadianceDepth(SrcProbeIndex, ProbeTexelCoords, true);
					float3 RayRadiance = RadianceDepth.xyz;
                    float RayDepth = RadianceDepth.w;
                    float3 Tangent, Bitangent;
                    GetOrthoVectors(SrcProbeHeader.Normal, Tangent, Bitangent);
                    float3 RayDirection = HemiOctahedron01ToUnitVectorA((ProbeTexelCoords + 0.5f) / SSRC_PROBE_TEXTURE_SIZE);
                    RayDirection = RayDirection.x * Tangent + RayDirection.y * Bitangent + RayDirection.z * SrcProbeHeader.Normal;
                    float3 RayHitPosition = SrcProbeHeader.Position + RayDirection * RayDepth;
                    float3 ReprojectedRayDirection = normalize(RayHitPosition - Header.Position);
                    float  ReprojectedRayDepth     = length(RayHitPosition - Header.Position);
                    if(dot(ReprojectedRayDirection, Header.Normal) > 0) {
                        // Successful reprojection
                        float3 LocalReprojectedRayDirection = float3(
                            dot(ReprojectedRayDirection, ProbeTangent),
                            dot(ReprojectedRayDirection, ProbeBitangent),
                            dot(ReprojectedRayDirection, Header.Normal)
                        );
                        float2 ReprojectedProbeTexelUV = UnitVectorToHemiOctahedron01A(LocalReprojectedRayDirection);
                        int2 ReprojectedProbeTexelCoords = clamp(int2(
                            ReprojectedProbeTexelUV * SSRC_PROBE_TEXTURE_SIZE
                        ), 0, SSRC_PROBE_TEXTURE_SIZE - 1);
                        int  ReprojectedProbeTexelIndex = ReprojectedProbeTexelCoords.y * SSRC_PROBE_TEXTURE_SIZE + ReprojectedProbeTexelCoords.x;
                        float  Weight = Sample.Weights[CornerIndex];
                        float3 WeightedRayRadiance = Weight * RayRadiance;
                        InterlockedAdd(LocalProbeTexelsQuantilized[ReprojectedProbeTexelIndex].x, QuantilizeRadiance(WeightedRayRadiance.x, Q_Noise));
                        InterlockedAdd(LocalProbeTexelsQuantilized[ReprojectedProbeTexelIndex].y, QuantilizeRadiance(WeightedRayRadiance.y, Q_Noise));
                        InterlockedAdd(LocalProbeTexelsQuantilized[ReprojectedProbeTexelIndex].z, QuantilizeRadiance(WeightedRayRadiance.z, Q_Noise));
                        InterlockedAdd(LocalProbeTexelsQuantilized[ReprojectedProbeTexelIndex].w, QuantilizeRadiance(ReprojectedRayDepth * Weight, Q_Noise));
                        InterlockedAdd(LocalProbeTexelSampleWeightQuantilized[ReprojectedProbeTexelIndex], QuantilizeWeight(Weight, Q_Noise));
                    }
                }
            }
        }
        GroupMemoryBarrierWithGroupSync();

        // GI10: Calculate the radiance backup value to be used for unvisited cells
        // Simply average the radiance values among probe samples.
        float4 BackupRadianceSum = 0;
        for(int BaseProbeTexelIndex = 0; BaseProbeTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseProbeTexelIndex += WAVE_SIZE) {
            int ProbeTexelIndex = BaseProbeTexelIndex + LocalID;
            float Weight = RecoverWeight(LocalProbeTexelSampleWeightQuantilized[ProbeTexelIndex]);
            float V = Weight > 0 ? 1.0f : 0.0f;
            float3 Radiance = RecoverRadiance(LocalProbeTexelsQuantilized[ProbeTexelIndex].xyz) / max(Weight, 1e-4f);
            BackupRadianceSum += float4(Radiance, V);
        }
        BackupRadianceSum = WaveActiveSum(BackupRadianceSum);

        float4 BackupRadianceDepth = 0;
        {
            float3 Radiance      = BackupRadianceSum.xyz / max(BackupRadianceSum.w, 1.0f);
            float  NumEmptyCells = (SSRC_PROBE_TEXTURE_SIZE * SSRC_PROBE_TEXTURE_SIZE - BackupRadianceSum.w);
            // Fill holes if there're only a tiny amount of empty cells
            // Otherwise decay the radiance they received
            BackupRadianceDepth = float4(Radiance / max(NumEmptyCells, 1.0f), C.FarPlane);
        }
        
        // Write the reprojected probe texel
        for(int BaseProbeTexelIndex = 0; BaseProbeTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseProbeTexelIndex += WAVE_SIZE) {
            int ProbeTexelIndex = BaseProbeTexelIndex + LocalID;
            int2 ProbeTexelCoords = int2(ProbeTexelIndex % SSRC_PROBE_TEXTURE_SIZE, ProbeTexelIndex / SSRC_PROBE_TEXTURE_SIZE);
            float Weight = RecoverWeight(LocalProbeTexelSampleWeightQuantilized[ProbeTexelIndex]);
            float4 RadianceDepth = RecoverRadiance(LocalProbeTexelsQuantilized[ProbeTexelIndex]);
            if(Weight < 0.01f) RadianceDepth = BackupRadianceDepth;
            else RadianceDepth = RadianceDepth / Weight;
            WriteScreenProbeOctahedronRadianceDepth(ProbeIndex, ProbeTexelCoords, RadianceDepth);
        }
    }
}

// Allocate update rays for each probe
[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_AllocateProbeUpdateRays (int DispatchID : SV_DispatchThreadID) {
    if(DispatchID >= UB.SSRC_NumUniformScreenProbes + g_RWAdaptiveProbeCountBuffer[0]) {
        return;
    }
    // NOTE: the allocation number must be a multiple of WAVE_SIZE
    // NOTE: and no greater than SSRC_MAX_NUM_UPDATE_RAY_PER_PROBE
    int2 ProbeIndex = int2(DispatchID % UB.TileDimensions.x, DispatchID / UB.TileDimensions.x);
    ProbeHeader Header = GetScreenProbeHeader(ProbeIndex);
    // Invalid probe
    if(Header.LinearDepth <= 0) {
        g_RWProbeUpdateRayCountsBuffer[DispatchID] = 0;
        return ;
    }
    // Naive strategy: allocate more rays for probes that failed in reprojection
    float Trust = g_RWProbeHistoryTrustTexture[ProbeIndex];
    int   Bonus = UB.SSRC_BaseUpdateRayWaves + (1.f - Trust) * 
		(SSRC_MAX_NUM_UPDATE_RAY_PER_PROBE / WAVE_SIZE - UB.SSRC_BaseUpdateRayWaves);
	if(UB.SSRC_ResetCache) Bonus = 0;
	g_RWProbeUpdateRayCountsBuffer[DispatchID] = min(WAVE_SIZE * max(1, Bonus), SSRC_MAX_NUM_UPDATE_RAY_PER_PROBE);
}

// A scan sum is performed to accumulate allocated raycount for each probe

[numthreads(1, 1, 1)]
void SSRC_SetRayCounts () {
    int ProbeCount = UB.SSRC_NumUniformScreenProbes + g_RWAdaptiveProbeCountBuffer[0];
    g_RWProbeAllUpdateRayCountBuffer[0] = g_RWProbeUpdateRayOffsetsBuffer[ProbeCount];
	g_RWRayToTraceCountBuffer[0] = g_RWProbeUpdateRayOffsetsBuffer[ProbeCount];
	g_RWRayCountBuffer[0] = g_RWProbeUpdateRayOffsetsBuffer[ProbeCount];
}

#define MIN_PDF_TO_TRACE 1e-3f

groupshared float  LocalOctahedronSampleWeight[SSRC_PROBE_TEXTURE_TEXEL_COUNT];
groupshared float  LocalOctahedronSampleWeightPrefixSum[SSRC_PROBE_TEXTURE_TEXEL_COUNT];

float RadianceToSampleWeight (float3 Radiance) {
    return dot(Radiance, 1.f.xxx) + 1e-4f;
}

[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_SampleProbeUpdateRays (int LocalID : SV_GroupThreadID, int GroupID : SV_GroupID) {
    const float Epsilon = 1e-7f;
    // We assume that ray count is always a multiple of WAVE_SIZE
    int  ProbeIndex1 = GroupID;
    int2 ProbeIndex  = int2(ProbeIndex1 % UB.TileDimensions.x, ProbeIndex1 / UB.TileDimensions.x);
    int  RayCount    = g_RWProbeUpdateRayCountsBuffer[ProbeIndex1];
    ProbeHeader Header = GetScreenProbeHeader(ProbeIndex);
    // Prepare probe local coordinate system
    float3 ProbeTangent, ProbeBitangent;
    GetOrthoVectors(Header.Normal, ProbeTangent, ProbeBitangent);

    float SumSizeOctahedronOriginal = 0.f;
    // Load octahedron sample weights
    {
        float SavedPrefixSum = 0.f;
        for(int BaseProbeTexelIndex = 0; BaseProbeTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseProbeTexelIndex += WAVE_SIZE) {
            int  ProbeTexelIndex = BaseProbeTexelIndex + LocalID;
            int2 ProbeTexelCoords = int2(ProbeTexelIndex % SSRC_PROBE_TEXTURE_SIZE, ProbeTexelIndex / SSRC_PROBE_TEXTURE_SIZE);
            float4 RadianceDepth = GetScreenProbeOctahedronRadianceDepth(ProbeIndex, ProbeTexelCoords);
            float3 Radiance = RadianceDepth.xyz;
            float AreaCorrectionFactor = 1.f;
            float  SampleWeight = RadianceToSampleWeight(Radiance) * AreaCorrectionFactor;
            LocalOctahedronSampleWeight[ProbeTexelIndex] = SampleWeight;
            float PrefixSum = WavePrefixSum(SampleWeight) + SavedPrefixSum;
            LocalOctahedronSampleWeightPrefixSum[ProbeTexelIndex] = PrefixSum;
#if SSRC_PROBE_TEXTURE_TEXEL_COUNT % WAVE_SIZE != 0
#error "SSRC_PROBE_TEXTURE_TEXEL_COUNT must be a multiple of WAVE_SIZE"
#endif
            SavedPrefixSum = WaveReadLaneAt(PrefixSum + RadianceToSampleWeight(Radiance), WAVE_SIZE - 1); 
        }
        SumSizeOctahedronOriginal = SavedPrefixSum;
    }
    GroupMemoryBarrierWithGroupSync();
    // Assume that octahedron mapping to sphere is area preserving (ignoring the distortion)
    float SumSizeOctahedron = SumSizeOctahedronOriginal * (TWO_PI / SSRC_PROBE_TEXTURE_TEXEL_COUNT) + Epsilon;

    float SumSize = SumSizeOctahedron;
    
    Random rng = MakeRandom((GroupID * WAVE_SIZE + LocalID) ^ 0x718f3a21u, UB.SSRC_ProbeUpdateRaySampleSeed);
#if SSRC_MAX_NUM_UPDATE_RAY_PER_PROBE % WAVE_SIZE != 0
#error "SSRC_MAX_NUM_UPDATE_RAY_PER_PROBE must be a multiple of WAVE_SIZE"
#endif
    // Allocate a number of rays to sample the probe octahedron
    // Round to a multiple of WAVE_SIZE with russian roulette for maximum wave coherence & occupancy
    int NumProbeOctahedronSamples = RayCount;
    // Sample probe octahedron
    [unroll(SSRC_MAX_NUM_UPDATE_RAY_PER_PROBE / WAVE_SIZE)]
    for(int RayRankBase = 0; RayRankBase < NumProbeOctahedronSamples; RayRankBase += WAVE_SIZE) {
        // We assume that ray count is always a multiple of WAVE_SIZE
        int RayRank = RayRankBase + LocalID;
        float  u    = rng.rand();
        float2 u2   = rng.rand2();
		float  u3   = rng.rand();
        float  U    = u * SumSizeOctahedronOriginal;
        int L = 0, R = SSRC_PROBE_TEXTURE_TEXEL_COUNT;
        for(int i = 0; i < SSRC_PROBE_TEXTURE_TEXEL_COUNT_L2; i++) {
            int Mid = (L + R) / 2;
            if(LocalOctahedronSampleWeightPrefixSum[Mid] < U) L = Mid;
            else R = Mid;
        }
        float OctPdf = LocalOctahedronSampleWeight[L] / max(SumSizeOctahedronOriginal, Epsilon) * SSRC_PROBE_TEXTURE_TEXEL_COUNT;
        float2 TexelUV = u2;
        int2   TexelCoords = int2(L % SSRC_PROBE_TEXTURE_SIZE, L / SSRC_PROBE_TEXTURE_SIZE);
        float2 OctahedronUV = (TexelUV + TexelCoords) * (1.f / SSRC_PROBE_TEXTURE_SIZE);
        float3 RayDirection = HemiOctahedron01ToUnitVectorA(OctahedronUV);
        RayDirection = RayDirection.x * ProbeTangent + RayDirection.y * ProbeBitangent + RayDirection.z * Header.Normal;
        // Convert from [0, 1]^2 to S^2
        float AreaCorrectionFactor = 1.f;
        OctPdf = OctPdf * AreaCorrectionFactor * (1.f / TWO_PI);

        float RayPdf = OctPdf;
        if(UB.SSRC_NoImportanceSampling) {
            RayPdf = UniformSampleHemispherePdf();
            RayDirection = UniformSampleHemisphere(u2);
            RayDirection = normalize(ProbeTangent * RayDirection.x + ProbeBitangent * RayDirection.y + Header.Normal * RayDirection.z);
        }
        // 0623: This must be checked otherwise there're precision issues
        float bValid = dot(RayDirection, Header.Normal) > 0;
        int ProbeIndex1 = ProbeIndex.x + ProbeIndex.y * UB.TileDimensions.x;
        int RayIndex = RayRank + g_RWProbeUpdateRayOffsetsBuffer[ProbeIndex1];
		if(WaveIsFirstLane()) {
			// Record the probe index for the (wave of) ray
			g_RWProbeUpdateRayProbeBuffer[RayIndex / WAVE_SIZE] = PackUint16x2(ProbeIndex);
		}
		// Setup ray to trace indirection list (for later compound tracing)
		g_RWRayToTraceListBuffer[RayIndex] = RayIndex;
        if(RayPdf >= MIN_PDF_TO_TRACE && bValid) {
			// A valid update ray is spawned
			// Queue up for a ray trace
			RayToTrace Ray = InitRayToTrace(UB.RT_MaxTraceDistance);
			Ray.Direction = RayDirection;
			Ray.Seed = u3 * UB.HWRT_StochasticRayTracingQuality;
			WriteRayToTrace(RayIndex, Ray, false);
			g_RWRayToTraceResultBuffer[RayIndex] = PackFp16x4Safe(0.f.xxxx);
			g_RWRayToTraceUVPositionBuffer[RayIndex] = PackUnorm16x2(ScreenToUV(Header.ScreenCoords + 0.5f));
			// Keep extra data for later probe update
			g_RWProbeUpdateRayDirectionBuffer[RayIndex] = PackNormal(RayDirection);
			ProbeUpdateRayResult Result = (ProbeUpdateRayResult)0;
			Result.InvPdf = 1.f / RayPdf;
			WriteProbeUpdateRayResult(RayIndex, Result);
        } else {
			// Invalid ray, mark it as complteted with TMin 0 (invalid)
			WriteRayTraceFlags(RayIndex, true, 0);
			g_RWRayToTraceResultBuffer[RayIndex] = PackFp16x4Safe(0.f.xxxx);
			// Makes no contribution and is invalid
			ProbeUpdateRayResult Result = (ProbeUpdateRayResult)0;
			Result.InvPdf = 0.f;
			// InvPdf == 0 indicates that the ray is invalid
			WriteProbeUpdateRayResult(RayIndex, Result);
        }
    }
}

// Compact to filter out invalid rays...

// Trace in screen space... (and hits update ProbeUpdateRayResult / ProbeUpdateRayDepth directly)

// Compact completed rays...

// Trace with HWRT...

[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_ResolveRayDepths (uint DispatchID : SV_DispatchThreadID) {
	int RayIndex = DispatchID;
	if(RayIndex >= g_RWRayCountBuffer[0]) return ; // Same as g_RWProbeAllUpdateRayCountBuffer[0]
	RayToTrace Ray = FetchRayToTrace(RayIndex, UB.RT_MaxTraceDistance, false);
	g_RWProbeUpdateRayDepthBuffer[RayIndex] = Ray.RayTMin;
}

// Filter hits outside of the screen or without history radiance
[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_ResolveHitLightingFromScreenHistory (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= g_RWRayToTraceCountBuffer[0]) return ;
	int RayIndex = g_RWRayToTraceListBuffer[DispatchID];
	RayToTrace Ray = FetchRayToTrace(RayIndex, UB.RT_MaxTraceDistance, false);
	CameraDescription C = GetCameraDescription();
	// Whether we should bypass the second level radiance cache. 
	bool bBypass = false;
	if(Ray.bHit) {
		{
			int2 ProbeIndex = GetProbeUpdateRayProbeIndex(RayIndex);
			ProbeHeader Header = GetScreenProbeHeader(ProbeIndex);
			Ray.Origin = Header.Position;
		}
		float3 HitWorldPosition = Ray.Origin + Ray.Direction * Ray.RayTMin;
		float4 PreviousHomogeneousW = mul(GetCameraDescription(true).ProjectionView, float4(HitWorldPosition, 1));
		float3 PreviousHomogeneous = PreviousHomogeneousW.xyz / PreviousHomogeneousW.w;
		if(PreviousHomogeneousW.w > 0 && all(PreviousHomogeneous.xy >= -1) && all(PreviousHomogeneous.xy <= 1)
		&& PreviousHomogeneous.z >= 0 && PreviousHomogeneous.z <= 1) {
			float2 HistoryScreenPosition = UB.ScreenDimensions * NDC2ToUV(PreviousHomogeneous.xy);
			int2 HistoryScreenCoords = int2(HistoryScreenPosition + 0.5f);
			float3 HistoryNormal = normalize(GetHistoryNormalTexture(C).Load(int3(HistoryScreenCoords, 0)).xyz * 2.f - 1.f);
			uint2  PackedHitResult = g_RWRayToTraceResultBuffer[RayIndex];
			float3 HitNormal     = UnpackNormal(PackedHitResult.y);
			float  HistoryDepth  = ZDepthToLinear(C, GetHistoryZDepthTexture(C).Load(int3(HistoryScreenCoords, 0)));
			float  PreviousDepth = ZDepthToLinear(C, PreviousHomogeneous.z);
			bool   bNormalVisible = dot(HistoryNormal, HitNormal) > 0.5f;
			bool   bDepthVisible  = 
                        abs(HistoryDepth - PreviousDepth) 
                        / max(PreviousDepth, HistoryDepth) < 5e-2f;
			if(bNormalVisible && bDepthVisible) {
				// The irradiance is directly attained from reprojected history radiance
				// TODO: exclude specular radiance
				float3 HistoryRadiance = g_HistoryRadianceWithoutEmission.Load(int3(HistoryScreenCoords, 0)).xyz;
				ProbeUpdateRayResult Result = FetchProbeUpdateRayResult(RayIndex);
				Result.Radiance = HistoryRadiance;
				Result.bBypass = true;
				WriteProbeUpdateRayResult(RayIndex, Result);
				bBypass = true;
			}
		}
	}
	if(!bBypass) {
		if(Ray.bHit) {
			// Queue up all hits that failed in reprojection and require direct lighting shading
			int HitCountNoBypass = WaveActiveCountBits(true);
			int HitCountListOffset = 0;
			if(WaveIsFirstLane()) {
				InterlockedAdd(g_RWProbeUpdateRayHitShadeCountBuffer[0], HitCountNoBypass, HitCountListOffset);
			}
			HitCountListOffset = WaveReadLaneFirst(HitCountListOffset);
			
			int ShadeHitIndex  = HitCountListOffset + WavePrefixCountBits(true);
			g_RWProbeUpdateRayHitShadeListBuffer[ShadeHitIndex] = RayIndex;
			// Cache hit positions / view directions in a separate buffer, as we need to immediately
			// spawn new rays for direct illumination in the next shader.
			int2 ProbeIndex = GetProbeUpdateRayProbeIndex(RayIndex);
			float3 ProbeWorldPosition = GetScreenProbeHeader(ProbeIndex).Position;
			float3 HitPosition = ProbeWorldPosition + Ray.Direction * Ray.RayTMin;
			// Record secondary vertex info for light ray sampling and tracing
			// g_RWProbeUpdateRayHitShadePositionBuffer[ShadeHitIndex] = HitPosition;
			// g_RWProbeUpdateRayHitShadeViewDirectionBuffer[ShadeHitIndex] = PackNormal(-Ray.Direction);

			// According to GI1.0, bypass the cache when the ray length from
			// primary vertex to secondary vertex is less than hash grid cell size.
			// (Avoid light leaking though cache filtering)
			float CellSize = HashGrids_GetCellSize(Ray.Origin);
			if(Ray.RayTMin < CellSize) {
				ProbeUpdateRayResult Result = FetchProbeUpdateRayResult(RayIndex);
				Result.bBypass = true;
				WriteProbeUpdateRayResult(RayIndex, Result);
			}
		} else {
			// A miss indicates that the ray has reached the sky
			// Sample the sky radiance and store it in the result buffer
			// Note: sky radiance is considered as an indirect lighting source
			// due to it's low frequency and high coherence nature
			ProbeUpdateRayResult Result = FetchProbeUpdateRayResult(RayIndex);
			Result.Radiance = EvaluateSkyRadiance(-Ray.Direction, UB.LightingSkyRadianceLOD);
			Result.bBypass = true;
			WriteProbeUpdateRayResult(RayIndex, Result);
		}
	}
}

// Clear g_RWRayToTraceCountBuffer[0] for the next shader.

// Sample light rays for DI calculation using light grid
[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_SampleLightRays (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= g_RWProbeUpdateRayHitShadeCountBuffer[0]) return ;
	// float3 HitPosition   = g_RWProbeUpdateRayHitShadePositionBuffer[DispatchID];
	// float3 HitViewDirection = UnpackNormal(g_RWProbeUpdateRayHitShadeViewDirectionBuffer[DispatchID]);
	int  ProbeUpdateRayIndex = g_RWProbeUpdateRayHitShadeListBuffer[DispatchID];
	int2 ProbeIndex          = GetProbeUpdateRayProbeIndex(ProbeUpdateRayIndex);
	float3 ProbeUpdateRayDepth     = g_RWProbeUpdateRayDepthBuffer[ProbeUpdateRayIndex];
	float3 ProbeUpdateRayDirection = UnpackNormal(g_RWProbeUpdateRayDirectionBuffer[ProbeUpdateRayIndex]);
	float3 HitPosition = ProbeUpdateRayDirection * ProbeUpdateRayDepth + GetScreenProbePosition(ProbeIndex);
	float3 HitViewDirection = -ProbeUpdateRayDirection;
	// Till now rays to be traced have identical indices with the probe update rays
	// After this kernel, rays to be traced will be cleared and re-assigned shadow rays for DI calculation.
	uint2 PackedHitResult = g_RWRayToTraceResultBuffer[ProbeUpdateRayIndex];
	Material HitMaterial = UnpackCachedMaterial(PackedHitResult.x);
	float3 HitNormal     = UnpackNormal(PackedHitResult.y);
	HitMaterial.Normal = HitNormal;
	// Offset the hit position to avoid self-intersection
	HitPosition += HitNormal * UB.II_SecondaryVertexNormalOffset;

	// Sample lights using light grid
	uint4 GridIndex      = LightGrid_GetGridIndex(HitPosition);
	float GridSize;
	float3 GridMin       = LightGrid_GetGridBounds(GridIndex, GridSize);
	uint  GridIndex1     = LightGrid_GetGridIndex1(GridIndex);

	uint  SampledLightIndex = 0xffffffffu;
	float SampledLightResampleWeight = 0;
	float SumResampleWeights = 0;
	LightSample ReservedSample = (LightSample) 0;
	uint  Seed = DispatchID.x;
	Random rng = MakeRandom(Seed ^ 0xa7193ac9u, UB.FrameIndex);

	float U = rng.rand();
	int NumGridLights = g_LightGrid_GridLightCountBuffer[GridIndex1];
	int MaxNumGridLights = WaveActiveMax(NumGridLights);
	int LightGridListOffset = g_LightGrid_GridLightListOffsetBuffer[GridIndex1];
	// Resample grid lights using luminance as the weight
	[unroll(LIGHT_GRID_MAX_NUM_GRID_LIGHTS)]
	for(int i = 0; i < MaxNumGridLights; i++) {
		float2 u2 = rng.rand2();
		int LightIndex = (i < NumGridLights) ? g_LightGrid_GridLightListBuffer[LightGridListOffset + i] : 0;
		if(i < NumGridLights) {
			Light L = FetchLightHeader(LightIndex);
			// We have to produce a full sample of the light to accurately estimate the light contribution
			LightData   Details = FetchLightDetails(LightIndex);
			// Note: the returned sample is already cosine weighted
			LightSample Sample  = SampleLightWithCosineWeight(HitPosition, HitMaterial, L.Type, Details, u2);
			if(Sample.IsValid()) {
				float LightGridWeight = EstimateLightGridContribution(L, GridMin, GridSize);
				float LightCurrWeight = Luminance(Sample.Radiance / Sample.Pdf); 
				// RIS
				float ResampleWeight  = LightCurrWeight / max(LightGridWeight, 1e-7f);
				if(ResampleWeight > UB.LightGrid_MinResampleWeightForDirectIllumiation) {
					float NewSumResampleWeights = SumResampleWeights + ResampleWeight;
					float CurrentLightU = ResampleWeight / NewSumResampleWeights;
					if(CurrentLightU > U) {
						U /= CurrentLightU;
						ReservedSample = Sample;
						SampledLightResampleWeight = ResampleWeight;
					} else {
						U *= 1.f - CurrentLightU;
					}
					SumResampleWeights = NewSumResampleWeights;
				}
			}
		}
	}

	
	// Allocate an hash grid cache cell for the hit position
	// (Only points outside of the screen are cached in the hash grid cache)
	// Store indirections
	uint HashCellIndex = HashGrids_AllocateTile(HitPosition, HitViewDirection);
	// Probe update ray results should be resolved from this cell
	g_RWProbeUpdateRayResolveHashCellIndexBuffer[ProbeUpdateRayIndex] = HashCellIndex;

	if(ReservedSample.IsValid()) {

		// Okay we have a sample for each pixel. Now encode a shadow ray for visibility testing.
		// Calculate the real sample contribution. (Picking 1 single light from a bunch of lights)

		ReservedSample.Radiance *= SumResampleWeights / (ReservedSample.Pdf * SampledLightResampleWeight);

		// Spawn shadow ray
		float3 NewRayDirection = 0;
		float OcclusionThreshold = 0;
		if(IsInfinitelyFarLightType(ReservedSample.LightType)) {
			NewRayDirection = ReservedSample.Position;
			OcclusionThreshold = UB.RT_MaxTraceDistance;
		} else {
			NewRayDirection = normalize(ReservedSample.Position - HitPosition);
			OcclusionThreshold = length(ReservedSample.Position - HitPosition);
		}
		// Allocate rays
		int NewRayIndex = 0;
		{
			int NewRayIndexBase = 0;
			int NewRayWarpCount = WaveActiveCountBits(1);
			int NewRayWarpRank  = WavePrefixCountBits(1);
			if(WaveIsFirstLane()) {
				InterlockedAdd(g_RWRayToTraceCountBuffer[0], NewRayWarpCount, NewRayIndexBase);
			}
			NewRayIndexBase = WaveReadLaneFirst(NewRayIndexBase);
			NewRayIndex = NewRayIndexBase + NewRayWarpRank;
		}
		// Write ray to memory for HWRT
		RayToTrace NewRay = InitRayToTrace(UB.RT_MaxTraceDistance);
		NewRay.Direction = NewRayDirection;
		NewRay.Seed = rng.rand() * UB.HWRT_StochasticRayTracingQuality;
		NewRay.Origin = HitPosition;
		WriteRayToTrace(NewRayIndex, NewRay, true);
		// Keep in mind the occulusion threshold for direct illumination visibility testing
		g_RWDirectIlluminationRayOcclusionThresholdBuffer[NewRayIndex] = OcclusionThreshold;
		// Store the sample contribution for direct illumination (if it passed the visibility test)
		g_RWDirectIlluminationRayContributionBuffer[NewRayIndex] = PackRadianceA16(float4(ReservedSample.Radiance, 1.f));
		// Trace results are used to shade the hit of a probe update ray. Store indirections
		g_RWDirectIlluminationRayProbeUpdateRayIndexBuffer[NewRayIndex] = ProbeUpdateRayIndex;
	}
}

// Only the newly allocated cells should be cleared
[numthreads(1, 1, 1)]
void SSRC_PrepareClearNewHashGridTileCells () {
	// Clip counters
	g_HashGrids_FreeTileCountBuffer[0] = max(g_HashGrids_FreeTileCountBuffer[0], 0);
	DispatchIndirectCommand Command = (DispatchIndirectCommand) 0;
	Command.ThreadGroupCountX = 
		g_HashGrids_ActiveTileCountBuffer[0] 
	- g_HashGrids_ActiveTileCountBeforeAllocationBuffer[0];
	Command.ThreadGroupCountY = 1;
	Command.ThreadGroupCountZ = 1;
	g_RWDispatchIndirectCommandBuffer[0] = Command;
}

// Clear the newly allocated tile cells
[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_ClearNewHashGridTileCells (uint GroupID : SV_GroupID, uint LocalID : SV_GroupThreadID) {
	uint TileIndex = g_HashGrids_ActiveTileListBuffer[GroupID + g_HashGrids_ActiveTileCountBeforeAllocationBuffer[0]];
	uint Start = TileIndex * HASHGRIDS_NUM_CELLS_PER_TILE * 2;
	for(int BaseCellOffset = 0; BaseCellOffset < (HASHGRIDS_NUM_CELLS_PER_TILE * 2); BaseCellOffset += WAVE_SIZE) {
		int DWordIndex = Start + BaseCellOffset + LocalID;
		if(DWordIndex < (HASHGRIDS_NUM_CELLS_PER_TILE * 2)) {
			g_HashGrids_CellValueBuffer[DWordIndex] = 0;
		}
	}
	Start = TileIndex * HASHGRIDS_TILE_CELL_MIP_OFFSET_1 * 4;
	for(int BaseCellOffset = 0; BaseCellOffset < (HASHGRIDS_TILE_CELL_MIP_OFFSET_1 * 4); BaseCellOffset += WAVE_SIZE) {
		int DWordIndex = Start + BaseCellOffset + LocalID;
		if(DWordIndex < (HASHGRIDS_TILE_CELL_MIP_OFFSET_1 * 4)) {
			g_HashGrids_UpdateCellValueXBuffer[DWordIndex] = 0;
		}
	}
}

// HWRT trace shadow rays (without indirection ray index list)

// Resolve direct lighting, accumulate their contributions to hash grids
[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_ResolveHitDirectLightingFromTraceResult (uint DispatchID : SV_DispatchThreadID) {
	if(DispatchID >= g_RWRayToTraceCountBuffer[0]) return ;
	int RayIndex = DispatchID; // No indirection
	RayToTrace Ray = FetchRayToTrace(RayIndex, UB.RT_MaxTraceDistance, true);
	CameraDescription C = GetCameraDescription();

	float  Threshold = g_RWDirectIlluminationRayOcclusionThresholdBuffer[RayIndex];
	uint Seed = DispatchID ^ 0x81c61f7eu;
	Random rng = MakeRandom(Seed, UB.FrameIndex);
	float  Noise = rng.rand();
	Threshold *= lerp(UB.DI_OcclusionThresholdMinFactor, UB.DI_OcclusionThresholdMaxFactor, Noise);
	float3 Radiance = UnpackRadianceA16(g_RWDirectIlluminationRayContributionBuffer[RayIndex]).xyz;
	Radiance *= (Threshold < Ray.RayTMin) ? 1 : 0;

	uint ProbeUpdateRayIndex = g_RWDirectIlluminationRayProbeUpdateRayIndexBuffer[RayIndex];
	// Shadow ray tracing will not overwrite RayToTraceResultBuffer.
	Material M = UnpackCachedMaterial(g_RWRayToTraceResultBuffer[ProbeUpdateRayIndex].x);
	// Lambertian only for secondary vertices
	Radiance *= M.Albedo;

	// Accumulate the radiance to the hash grid cell
	uint HashCellIndex = g_RWProbeUpdateRayResolveHashCellIndexBuffer[ProbeUpdateRayIndex];
	if(!IsInvalid(HashCellIndex)) {
		uint CompactCellIndex = HashGrids_CellIndexToCompactCellIndex(HashCellIndex);
		HashGrids_AccumulateSamplesToCell(CompactCellIndex, Radiance, 1);

		// Bypass the hash grid cache for the probe update ray if required
		ProbeUpdateRayResult Result = FetchProbeUpdateRayResult(ProbeUpdateRayIndex);
		// Bypass hash grid cache, directly transfer radiance from DI results
		if(Result.bBypass) {
			Result.Radiance = Radiance;
			WriteProbeUpdateRayResult(ProbeUpdateRayIndex, Result);
		}
	}
}

groupshared float4 LocalHashGridTileRadiance[HASHGRIDS_TILE_CELL_WIDTH][HASHGRIDS_TILE_CELL_WIDTH];
// Filter hash grids
[numthreads(HASHGRIDS_TILE_CELL_WIDTH, HASHGRIDS_TILE_CELL_WIDTH, 1)]
void SSRC_FilterHashGrids (uint GroupID : SV_GroupID, uint2 LocalID : SV_GroupThreadID) {
	uint  TileIndex  = g_HashGrids_UpdateTileListBuffer[GroupID];
	uint2 CellOffset = LocalID;
    // MIP 0
    {
        uint CellIndex     = HashGrids_GetCellIndex(TileIndex, CellOffset, 0);
		uint CompactCellIndex = HashGrids_CellIndexToCompactCellIndex(CellIndex);

        // Temporal accumulation
        float4 OldRadiance = HashGrids_GetCellRadiance(CellIndex);
        float4 NewRadiance = HashGrids_GetUpdateCellRadiance(CompactCellIndex);
        NewRadiance.rgb /= max(NewRadiance.w, 1.0f);
		float  SampleCount = min(OldRadiance.w + NewRadiance.w, UB.HashGrids_MaxNumSamples);
        
		float4 Radiance = float4(
			lerp(OldRadiance.rgb, NewRadiance.rgb, saturate(NewRadiance.w / SampleCount)),
			SampleCount
		);
        
        LocalHashGridTileRadiance[CellOffset.y][CellOffset.x] = float4(Radiance.rgb * SampleCount, SampleCount);
        uint2 PackedValue = PackFp16x4Safe(Radiance);
		g_HashGrids_CellValueBuffer[CellIndex * 2 + 0] = PackedValue.x;
		g_HashGrids_CellValueBuffer[CellIndex * 2 + 1] = PackedValue.y;

        // Clear scratch
        g_HashGrids_UpdateCellValueXBuffer[4 * CompactCellIndex + 0] = 0;
        g_HashGrids_UpdateCellValueXBuffer[4 * CompactCellIndex + 1] = 0;
        g_HashGrids_UpdateCellValueXBuffer[4 * CompactCellIndex + 2] = 0;
        g_HashGrids_UpdateCellValueXBuffer[4 * CompactCellIndex + 3] = 0;
    }

    // MIP 1
    GroupMemoryBarrierWithGroupSync();
    if(all(CellOffset < HASHGRIDS_TILE_CELL_WIDTH / 2))
    {
        uint CellIndex     = HashGrids_GetCellIndex(TileIndex, CellOffset, 1);

        // Box filter
        float4 Radiance00 = LocalHashGridTileRadiance[2 * CellOffset.y + 0][2 * CellOffset.x + 0];
        float4 Radiance01 = LocalHashGridTileRadiance[2 * CellOffset.y + 0][2 * CellOffset.x + 1];
		float4 Radiance10 = LocalHashGridTileRadiance[2 * CellOffset.y + 1][2 * CellOffset.x + 0];
		float4 Radiance11 = LocalHashGridTileRadiance[2 * CellOffset.y + 1][2 * CellOffset.x + 1];

        float4 Radiance = (Radiance00 + Radiance01 + Radiance10 + Radiance11);

        LocalHashGridTileRadiance[2 * CellOffset.y][2 * CellOffset.x] = Radiance;
		uint2 PackedValue = PackFp16x4Safe(float4(Radiance.rgb / max(Radiance.w, 1), Radiance.w));
        g_HashGrids_CellValueBuffer[CellIndex * 2 + 0] = PackedValue.x;
		g_HashGrids_CellValueBuffer[CellIndex * 2 + 1] = PackedValue.y;
    }

    // MIP 2
    GroupMemoryBarrierWithGroupSync();
	if(all(CellOffset < HASHGRIDS_TILE_CELL_WIDTH / 4))
	{
		uint CellIndex     = HashGrids_GetCellIndex(TileIndex, CellOffset, 2);

		// Box filter
		float4 Radiance00 = LocalHashGridTileRadiance[4 * CellOffset.y + 0][4 * CellOffset.x + 0];
		float4 Radiance01 = LocalHashGridTileRadiance[4 * CellOffset.y + 0][4 * CellOffset.x + 2];
		float4 Radiance10 = LocalHashGridTileRadiance[4 * CellOffset.y + 2][4 * CellOffset.x + 0];
		float4 Radiance11 = LocalHashGridTileRadiance[4 * CellOffset.y + 2][4 * CellOffset.x + 2];

		float4 Radiance = (Radiance00 + Radiance01 + Radiance10 + Radiance11);

		LocalHashGridTileRadiance[4 * CellOffset.y][4 * CellOffset.x] = Radiance;
		uint2 PackedValue = PackFp16x4Safe(float4(Radiance.rgb / max(Radiance.w, 1), Radiance.w));
		g_HashGrids_CellValueBuffer[CellIndex * 2 + 0] = PackedValue.x;
		g_HashGrids_CellValueBuffer[CellIndex * 2 + 1] = PackedValue.y;
	}

	// MIP 3
	GroupMemoryBarrierWithGroupSync();
	if(all(CellOffset < HASHGRIDS_TILE_CELL_WIDTH / 8))
	{
		uint CellIndex     = HashGrids_GetCellIndex(TileIndex, CellOffset, 3);

		// Box filter
		float4 Radiance00 = LocalHashGridTileRadiance[8 * CellOffset.y + 0][8 * CellOffset.x + 0];
		float4 Radiance01 = LocalHashGridTileRadiance[8 * CellOffset.y + 0][8 * CellOffset.x + 4];
		float4 Radiance10 = LocalHashGridTileRadiance[8 * CellOffset.y + 4][8 * CellOffset.x + 0];
		float4 Radiance11 = LocalHashGridTileRadiance[8 * CellOffset.y + 4][8 * CellOffset.x + 4];

		float4 Radiance = (Radiance00 + Radiance01 + Radiance10 + Radiance11);

		// LocalHashGridTileRadiance[8 * CellOffset.y][8 * CellOffset.x] = Radiance;
		uint2 PackedValue = PackFp16x4Safe(float4(Radiance.rgb / max(Radiance.w, 1), Radiance.w));
		g_HashGrids_CellValueBuffer[CellIndex * 2 + 0] = PackedValue.x;
		g_HashGrids_CellValueBuffer[CellIndex * 2 + 1] = PackedValue.y;
	}
}

// Resolve probe update ray radiance results from hash grid cache
[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_ResolveProbeUpdateRayRadianceFromCells (uint DispatchID : SV_DispatchThreadID)
{
	if(DispatchID >= g_RWProbeUpdateRayHitShadeCountBuffer[0]) return ;
	int ProbeUpdateRayIndex = g_RWProbeUpdateRayHitShadeListBuffer[DispatchID];
    uint CellIndex          = g_RWProbeUpdateRayResolveHashCellIndexBuffer[ProbeUpdateRayIndex];
	float4 Radiance         = HashGrids_GetFilteredRadiance(CellIndex);
	ProbeUpdateRayResult Result = FetchProbeUpdateRayResult(ProbeUpdateRayIndex);
	if(!Result.bBypass) {
		// Resolve radiance from hash grid cache if no bypass is specified
		Result.Radiance = Radiance.xyz;
		WriteProbeUpdateRayResult(ProbeUpdateRayIndex, Result);
	}
}

// Now probe update ray trace results are resolved.
// Time to update SSRC!

void WriteScreenProbeSHCoefficients (int2 ProbeIndex, float3 SHCoefficients[9]) {
    float4 R1 = float4(SHCoefficients[1].x, SHCoefficients[2].x, SHCoefficients[3].x, SHCoefficients[4].x);
    float4 R2 = float4(SHCoefficients[5].x, SHCoefficients[6].x, SHCoefficients[7].x, SHCoefficients[8].x);
    float4 G1 = float4(SHCoefficients[1].y, SHCoefficients[2].y, SHCoefficients[3].y, SHCoefficients[4].y);
    float4 G2 = float4(SHCoefficients[5].y, SHCoefficients[6].y, SHCoefficients[7].y, SHCoefficients[8].y);
    float4 B1 = float4(SHCoefficients[1].z, SHCoefficients[2].z, SHCoefficients[3].z, SHCoefficients[4].z);
    float4 B2 = float4(SHCoefficients[5].z, SHCoefficients[6].z, SHCoefficients[7].z, SHCoefficients[8].z);
    float3 RGB0 = SHCoefficients[0];
    g_RWProbeIrradianceTexture[ProbeIndex].xyz = RGB0;
    g_RWProbeSHCoefficientsRTexture[ProbeIndex] = R1;
    g_RWProbeSHCoefficientsRTexture[ProbeIndex + int2(UB.TileDimensions.x, 0)] = R2;
    g_RWProbeSHCoefficientsBTexture[ProbeIndex] = B1;
    g_RWProbeSHCoefficientsBTexture[ProbeIndex + int2(UB.TileDimensions.x, 0)] = B2;
    g_RWProbeSHCoefficientsGTexture[ProbeIndex] = G1;
    g_RWProbeSHCoefficientsGTexture[ProbeIndex + int2(UB.TileDimensions.x, 0)] = G2;
}


void AccumulateOctahedronRadiance (
    float3 RayDirection, float3 RayRadiance, float RayDepth, float RayWeight, float Q_Noise,
    float3 ProbeTangent, float3 ProbeBitangent, float3 ProbeNormal,
    inout float3 BackupRadianceSum, inout float BackupRadianceWeightSum) {
    // Accumulate the weighted radiance
    float3 ProbeRayDirection = float3(
        dot(ProbeTangent,   RayDirection),
        dot(ProbeBitangent, RayDirection),
        dot(ProbeNormal,    RayDirection)
    );
    float2 OctahedronUV = UnitVectorToHemiOctahedron01A(ProbeRayDirection);
    int2 OctahedronTexelCoords = clamp(int2(
        int(OctahedronUV.x * SSRC_PROBE_TEXTURE_SIZE),
        int(OctahedronUV.y * SSRC_PROBE_TEXTURE_SIZE)
        ), 0, SSRC_PROBE_TEXTURE_SIZE - 1);
    int  OctahedronTexelIndex = OctahedronTexelCoords.y * SSRC_PROBE_TEXTURE_SIZE + OctahedronTexelCoords.x;
    // Re-weight the importance of each ray within each pixel with the inverse of their pdf
    // to avoid biased estimation of average radiance within the probe octahedron texel.
    float3 WeightedTargetRadiance = RayRadiance * RayWeight;
    float  WeightedRayDepth       = RayDepth * RayWeight;
    InterlockedAdd(LocalProbeTexelsQuantilized[OctahedronTexelIndex].x, QuantilizeRadiance(WeightedTargetRadiance.x, Q_Noise));
    InterlockedAdd(LocalProbeTexelsQuantilized[OctahedronTexelIndex].y, QuantilizeRadiance(WeightedTargetRadiance.y, Q_Noise));
    InterlockedAdd(LocalProbeTexelsQuantilized[OctahedronTexelIndex].z, QuantilizeRadiance(WeightedTargetRadiance.z, Q_Noise));
    InterlockedAdd(LocalProbeTexelsQuantilized[OctahedronTexelIndex].w, QuantilizeRadiance(WeightedRayDepth, Q_Noise));
    InterlockedAdd(LocalProbeTexelSampleWeightQuantilized[OctahedronTexelIndex], QuantilizeWeight(RayWeight, Q_Noise));
#ifndef BACKUP_RADIANCE_ON_PROBE_TEXELS
    // Accumulate backup radiance
    BackupRadianceSum += WeightedTargetRadiance;
    BackupRadianceWeightSum += RayWeight;
#endif
}

[numthreads(WAVE_SIZE, 1, 1)]
void Debug_SSRC_VisualizeProbes (int DispatchID : SV_DispatchThreadID) {
    int2 ProbeIndex = int2(DispatchID % UB.TileDimensions.x, DispatchID / UB.TileDimensions.x);
    if(ProbeIndex.x >= UB.TileDimensions.x || ProbeIndex.y >= UB.TileDimensions.y) {
        return;
    }
    int2 UniformProbeScreenCoords = GetUniformScreenProbeScreenCoords(ProbeIndex);

    if(all(UniformProbeScreenCoords >= 0) && all(UniformProbeScreenCoords < UB.ScreenDimensions)
    && IsScreenProbeValid(ProbeIndex))
        g_RW_DebugTexture[UniformProbeScreenCoords] = float4(10.f.xxx, 1.f);
    // Visualize adaptive probes
    int  AdaptiveProbeCount = g_RWTileAdaptiveProbeCountTexture[ProbeIndex];
    for(int i = 0; i < AdaptiveProbeCount; i++) {
        int  ScreenProbeIndex1 = GetAdaptiveProbeIndex(ProbeIndex, i) + UB.SSRC_NumUniformScreenProbes;
        int2 AdaptiveProbeIndex = int2(ScreenProbeIndex1 % UB.TileDimensions.x, ScreenProbeIndex1 / UB.TileDimensions.x);
        ProbeHeader Header = GetScreenProbeHeader(AdaptiveProbeIndex);
        int2 AdaptiveProbeScreenCoords = Header.ScreenCoords;
        g_RW_DebugTexture[AdaptiveProbeScreenCoords] = float4(10.f.xxx, 1.f);
    }
}

[numthreads(WAVE_SIZE, 1, 1)]
void Debug_SSRC_PrepareVisualizeProbeUpdateRays () {
	int2   TexCoords      = UB.Debug_CursorPixelCoords;
	CameraDescription C   = GetCameraDescription();
    float  LinearDepth    = GetFilteredDepthTexture(C).Load(int3(TexCoords, 0)).x;
    if(LinearDepth > 0) {
		float3 DebugCursorWorldPos = RecoverWorldSpacePosition(C, TexCoords + 0.5f.xx, LinearDepth);
        float3 GeometryNormal = normalize(2.f * GetNormalTexture(C).Load(int3(TexCoords, 0)).xyz - 1.f);
        SSRC_SampleData Sample;
        CalculateSSRCSampleWeights(
            TexCoords + 0.5f,
            DebugCursorWorldPos,
            LinearDepth,
            GeometryNormal,
            true,
            Sample
        );
        int MaxIndex;
        if(Sample.Weights[0] > Sample.Weights[1]) {
            MaxIndex = 0;
        } else {
            MaxIndex = 1;
        }
        if(Sample.Weights[2] > Sample.Weights[MaxIndex]) {
            MaxIndex = 2;
        }
        if(Sample.Weights[3] > Sample.Weights[MaxIndex]) {
            MaxIndex = 3;
        }
        if(Sample.Weights[MaxIndex] != 0) {
            int2 ProbeIndex  = Sample.Index[MaxIndex];
#ifndef NDEBUG
            g_Debug_SSRC_ProbeIndexBuffer[0] = ProbeIndex;
#endif
			int  ProbeIndex1 = ProbeIndex.x + ProbeIndex.y * UB.TileDimensions.x;
            int  ProbeRayCount = g_RWProbeUpdateRayCountsBuffer[ProbeIndex1];
            DrawIndirectCommand Command = (DrawIndirectCommand)0;
            Command.VertexCount = 2;
            Command.InstanceCount  = ProbeRayCount;
            Command.StartVertex   = 0;
            Command.StartInstance = 0;
            g_RWDrawIndirectCommandBuffer[0] = Command;
        } else {
            DrawIndirectCommand Command = (DrawIndirectCommand)0;
            Command.VertexCount = 0;
            Command.InstanceCount  = 0;
            Command.StartVertex   = 0;
            Command.StartInstance = 0;
            g_RWDrawIndirectCommandBuffer[0] = Command;
        }
    } else {
        DrawIndirectCommand Command = (DrawIndirectCommand)0;
        Command.VertexCount = 0;
        Command.InstanceCount  = 0;
        Command.StartVertex   = 0;
        Command.StartInstance = 0;
        g_RWDrawIndirectCommandBuffer[0] = Command;
    }
}

[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_UpdateProbes (int LocalID : SV_GroupThreadID, int GroupID : SV_GroupID) {

	CameraDescription C = GetCameraDescription();

    const float Epsilon = 1e-7f;

    int2 ProbeIndex = int2(GroupID % UB.TileDimensions.x, GroupID / UB.TileDimensions.x);
    ProbeHeader Header = GetScreenProbeHeader(ProbeIndex);
    // Thread group early out if the probe is not valid
    [branch]
    if(!Header.bValid) return ;

    // Retrieve tangent space for current probe
    float3 ProbeTangent, ProbeBitangent;
    GetOrthoVectors(Header.Normal, ProbeTangent, ProbeBitangent);

    int  ProbeRayCount   = g_RWProbeUpdateRayCountsBuffer[GroupID];
    int  ProbeRayOffset  = g_RWProbeUpdateRayOffsetsBuffer[GroupID];
    
    float  ReprojectionTrust = g_RWProbeHistoryTrustTexture[ProbeIndex].x;

    // Re-initialize the probe if it is not trusted at all
    [branch]
    if(ReprojectionTrust == 0) {
        // Simly reset the probe texels for probe initialization
        SSRC_ResetProbeTexels(GroupID, LocalID, ProbeIndex, Header.Normal);
    }

    // Clear accumulation buffer for octahedron radiance
    for(int BaseProbeTexelIndex = 0; BaseProbeTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseProbeTexelIndex += WAVE_SIZE) {
        int ProbeTexelIndex = BaseProbeTexelIndex + LocalID;
        LocalProbeTexelsQuantilized[ProbeTexelIndex] = 0.xxxx;
        LocalProbeTexelSampleWeightQuantilized[ProbeTexelIndex] = 0;
    }
    GroupMemoryBarrierWithGroupSync();
    // Noise for octahedron radiance quantilization
    float Q_Noise = 0.5f; // no noise for now
    // Backup radiance value for untraced probe texels in current update
    float3 BackupRadianceSum = 0.f;
    float  BackupRadianceWeightSum = 0.f;

    // TODO: sometimes not stable enough
    float3 ImpactFactors = 1.f - ReprojectionTrust;

    // Update probe octahedron radiance
    {
        // Enumerate rays and accumulate
        [unroll(SSRC_MAX_NUM_UPDATE_RAY_PER_PROBE / WAVE_SIZE)]
        for(int RayRankBase = 0; RayRankBase < ProbeRayCount; RayRankBase += WAVE_SIZE) {
            int RayRank  = RayRankBase + LocalID;
			int RayIndex = ProbeRayOffset + RayRank;

            float3 RayDirection      = UnpackNormal(g_RWProbeUpdateRayDirectionBuffer[RayIndex]);
            float3 RayRadiance;
            float  InvPdf;
			{
				ProbeUpdateRayResult Result = FetchProbeUpdateRayResult(RayIndex);
				RayRadiance = Result.Radiance;
				InvPdf = Result.InvPdf;
			}

			float  RayDepth          = g_RWProbeUpdateRayDepthBuffer[RayIndex];

            // Check for valid update rays
            if(InvPdf > 0 && dot(RayDirection, Header.Normal) > 0) {

                float3 TargetRadiance = RayRadiance;
                float  SampleWeight   = InvPdf;
                
                // Accumulate the weighted radiance
                AccumulateOctahedronRadiance(
                    RayDirection, TargetRadiance, RayDepth, SampleWeight, Q_Noise,
                    ProbeTangent, ProbeBitangent, Header.Normal, BackupRadianceSum, BackupRadianceWeightSum
                );
            }
        }
#ifdef BACKUP_RADIANCE_ON_PROBE_TEXELS
        GroupMemoryBarrierWithGroupSync();
        // Accumulate backup radiance
        for(int BaseTexelIndex = 0; BaseTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseTexelIndex += WAVE_SIZE) {
            int TexelIndex = BaseTexelIndex + LocalID;
            float3 Radiance = RecoverRadiance(LocalProbeTexelsQuantilized[TexelIndex]);
            float  Weight   = RecoverWeight(LocalProbeTexelSampleWeightQuantilized[TexelIndex]);
            BackupRadianceSum += Radiance / max(Weight, 1e-4f);
            BackupRadianceWeightSum += (Weight != 0) ? 1 : 0;
        }
#endif
        BackupRadianceSum = WaveActiveSum(BackupRadianceSum);
        BackupRadianceWeightSum = WaveActiveSum(BackupRadianceWeightSum);
        // Clamp to zero for negative radiance
        BackupRadianceSum = max(BackupRadianceSum, 0.f.xxx);
        GroupMemoryBarrierWithGroupSync();
        // Compute the backup radiance
        float3 BackupRadiance = 0.f.xxx;
        {
            // Count untraced probe texels in current update
            int NumUntracedTexels = 0;
            [unroll(SSRC_PROBE_TEXTURE_TEXEL_COUNT / WAVE_SIZE)]
            for(int BaseProbeTexelIndex = 0; BaseProbeTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseProbeTexelIndex += WAVE_SIZE) {
                int ProbeTexelIndex = BaseProbeTexelIndex + LocalID;
                NumUntracedTexels += (LocalProbeTexelSampleWeightQuantilized[ProbeTexelIndex] == 0);
            }
            NumUntracedTexels = WaveActiveSum(NumUntracedTexels);
            // Compute the backup radiance
            BackupRadiance = BackupRadianceSum / max(BackupRadianceWeightSum, 1e-4f);
            float  empty_cell_count = NumUntracedTexels;
            BackupRadiance = BackupRadiance / max(NumUntracedTexels, 1.0f);
        }
        [unroll(SSRC_PROBE_TEXTURE_TEXEL_COUNT / WAVE_SIZE)]
        for(int BaseProbeTexelIndex = 0; BaseProbeTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseProbeTexelIndex += WAVE_SIZE) {
            int  ProbeTexelIndex = BaseProbeTexelIndex + LocalID;
            int2 ProbeTexelCoords = int2(ProbeTexelIndex % SSRC_PROBE_TEXTURE_SIZE, ProbeTexelIndex / SSRC_PROBE_TEXTURE_SIZE);
            int4  Quantilized = LocalProbeTexelsQuantilized[ProbeTexelIndex];
            float4 RadianceDepthSum = RecoverRadiance(Quantilized.xyzw);
            float4 OldRadianceDepth = GetScreenProbeOctahedronRadianceDepth(ProbeIndex, ProbeTexelCoords);

            int    QuantilizedWeight = LocalProbeTexelSampleWeightQuantilized[ProbeTexelIndex];
            float  Weight   = QuantilizedWeight == 0 ? 1.f : RecoverWeight(QuantilizedWeight);
            // Overwrite the radiance depth with backup values if the texel is not traced in current update
            if(QuantilizedWeight == 0) RadianceDepthSum = float4(BackupRadiance, C.FarPlane);
            float4 RadianceDepth = RadianceDepthSum / Weight;
            // Accumulate the compensation radiance for over-lit caused by LSM method.
            float3 TexelCompensation = min(RadianceDepth.xyz, 0);

            float  LumaA = Luminance(max(RadianceDepth.xyz, 0.f));
            float  LumaB = Luminance(OldRadianceDepth.xyz);
            // Copy-pasted from GI1.0
            // Shadow-preserving biased temporal hysteresis (inspired by: https://www.youtube.com/watch?v=WzpLWzGvFK4&t=630s)
            // It darkens the scene, while providing temporal stability as a trade-off.
            float TemporalBlend = squared(clamp(max(LumaA - LumaB - min(LumaA, LumaB), 0.0f) / max(max(LumaA, LumaB), 1e-4f), 0.0f, 0.95f));
            // Replaced by a constant for now.
			TemporalBlend = 0.75f;
			// Clamp the lerping factor with impact factors from our pipeline
            TemporalBlend = min(max(1.f - ImpactFactors.x, 0), TemporalBlend);
            float4 UpdatedRadianceDepth = lerp(RadianceDepth, OldRadianceDepth, TemporalBlend);
            UpdatedRadianceDepth = max(UpdatedRadianceDepth, 0.f);
            WriteScreenProbeOctahedronRadianceDepth(ProbeIndex, ProbeTexelCoords, UpdatedRadianceDepth);
        }
    }
}


// From Lumen
float GetFilterPositionWeightForProbeGather(float NeighborLinearDepth, float LinearDepth)
{
	float DepthDifference = abs(NeighborLinearDepth - LinearDepth);
	float RelativeDepthDifference = DepthDifference / LinearDepth;
	return exp2(-1000.f * (RelativeDepthDifference * RelativeDepthDifference));
}

void GatherProbeRadiance (
    float3 Position,
    float  LinearDepth,
    float3 HitPosition,
    int2   NeighborProbeIndex,
    inout float3 SumRadiance,
    inout float  SumWeight,
    inout float MaxWeight
) {
    if(all(NeighborProbeIndex >= 0) && all(NeighborProbeIndex < UB.TileDimensions)) {
        float NeighborLinearDepth = GetScreenProbeLinearDepth(NeighborProbeIndex);
        if(NeighborLinearDepth > 0) { // Valid
            float PositionWeight = GetFilterPositionWeightForProbeGather(NeighborLinearDepth, LinearDepth);
            if(PositionWeight > 0) {
                float3 NeighborWorldPosition = GetScreenProbePosition(NeighborProbeIndex);
                float3 ToNeighbor = HitPosition - NeighborWorldPosition;
                float  ToNeighborLength = max(length(ToNeighbor), 1e-3f);
                float3 ToNeighborUnit = ToNeighbor / ToNeighborLength;
                float3 NeighborProbeNormal = GetScreenProbeNormal(NeighborProbeIndex);
                float3 Tangent, Bitangent;
                GetOrthoVectors(NeighborProbeNormal, Tangent, Bitangent);
                float3 NeighborProbeLocalDirection = float3(
                    dot(Tangent,   ToNeighborUnit),
                    dot(Bitangent, ToNeighborUnit),
                    dot(NeighborProbeNormal, ToNeighborUnit)
                );
                if(NeighborProbeLocalDirection.z > 0) {
                    float2 NeighborProbeUV = UnitVectorToHemiOctahedron01A(NeighborProbeLocalDirection);
                    int2   NeighborTexelCoords = clamp(NeighborProbeUV * SSRC_PROBE_TEXTURE_SIZE, 0, SSRC_PROBE_TEXTURE_SIZE - 1);
                    float4 NeighborRadianceDepth = GetScreenProbeOctahedronRadianceDepth(NeighborProbeIndex, NeighborTexelCoords);
                    float3 NeighborRadiance = NeighborRadianceDepth.xyz;
                    float  NeighborDepth = NeighborRadianceDepth.w;
                    float  DepthWeight = 1 - abs(NeighborDepth - ToNeighborLength) / max(1e-3f, max(NeighborDepth, ToNeighborLength));
                    DepthWeight = pow(saturate(DepthWeight), 6);
                    float  Weight = PositionWeight * DepthWeight;
                    MaxWeight = max(Weight, MaxWeight);
                    SumRadiance += NeighborRadiance * Weight;
                    SumWeight   += Weight;
                }
            }
        }
    }
    
}

[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_FilterProbes (int GroupID : SV_GroupID, int LocalID : SV_GroupThreadID) {

    int2 ProbeIndex = int2(GroupID % UB.TileDimensions.x, GroupID / UB.TileDimensions.x);
    ProbeHeader Header = GetScreenProbeHeader(ProbeIndex);
    // Thread group early out if the probe is not valid
    [branch]
    if(!Header.bValid) return ;
    
    int2 ProbeScreenCoords  = Header.ScreenCoords;
    int2 TileIndex = int2(ProbeScreenCoords / TILE_SIZE);
    float  ReprojectionTrust = g_RWProbeHistoryTrustTexture[ProbeIndex].x;

    float3 Tangent, Bitangent;
    GetOrthoVectors(Header.Normal, Tangent, Bitangent);

    float3 SH_Coefficients[9];
    for(int i = 0; i < 9; i++) {
        SH_Coefficients[i] = 0.f;
    }

    for(int BaseProbeTexelIndex = 0; BaseProbeTexelIndex < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseProbeTexelIndex += WAVE_SIZE) {
        int  ProbeTexelIndex = BaseProbeTexelIndex + LocalID;
        int2 ProbeTexelCoords = int2(ProbeTexelIndex % SSRC_PROBE_TEXTURE_SIZE, ProbeTexelIndex / SSRC_PROBE_TEXTURE_SIZE);
        float2 ProbeTexelUV = (ProbeTexelCoords + 0.5f) / SSRC_PROBE_TEXTURE_SIZE;
        float3 ProbeLocalTexelDirection = HemiOctahedron01ToUnitVectorA(ProbeTexelUV);
        float3 ProbeWorldTexelDirection = 
            Tangent * ProbeLocalTexelDirection.x 
          + Bitangent * ProbeLocalTexelDirection.y
          + Header.Normal * ProbeLocalTexelDirection.z;
        float4  TexelRadianceDepth = GetScreenProbeOctahedronRadianceDepth(ProbeIndex, ProbeTexelCoords);
        float3 HitPosition = Header.Position + ProbeWorldTexelDirection * TexelRadianceDepth.w;

        float  MaxWeight = max(ReprojectionTrust, 0.1f);
        float3 SumRadiance = 0.f;
        float  SumWeight   = 0.f;

        if(UB.SSRC_ProbeFiltering) {
            
            int2 Offsets[4];
            Offsets[0] = int2(-1, 0);
            Offsets[1] = int2(1, 0);
            Offsets[2] = int2(0, -1);
            Offsets[3] = int2(0, 1);
            for (uint OffsetIndex = 0; OffsetIndex < 4; OffsetIndex++)
            {
                GatherProbeRadiance(
                    Header.Position,
                    Header.LinearDepth,
                    HitPosition,
                    TileIndex + Offsets[OffsetIndex],
                    SumRadiance,
                    SumWeight,
                    MaxWeight
                );
            }
        }

        if(UB.SSRC_ProbeFiltering && ReprojectionTrust < 0.8f) {
            int2 Offsets[8];
            Offsets[0] = int2(-2, 0);
            Offsets[1] = int2(2, 0);
            Offsets[2] = int2(0, -2);
            Offsets[3] = int2(0, 2);
            Offsets[4] = int2(-1, 1);
            Offsets[5] = int2(1, 1);
            Offsets[6] = int2(-1, -1);
            Offsets[7] = int2(1, -1);
            for (uint OffsetIndex = 0; OffsetIndex < 8; OffsetIndex++)
            {
                GatherProbeRadiance(
                    Header.Position,
                    Header.LinearDepth,
                    HitPosition,
                    TileIndex + Offsets[OffsetIndex],
                    SumRadiance,
                    SumWeight,
                    MaxWeight
                );
            }
        }

        SumRadiance += TexelRadianceDepth.xyz * MaxWeight;
        SumWeight   += MaxWeight;
    
        float3 NewRadiance = SumRadiance / SumWeight;
        float4 NewRadianceDepth = float4(NewRadiance, TexelRadianceDepth.w);
        WriteScreenProbeOctahedronRadianceDepth(ProbeIndex, ProbeTexelCoords, NewRadianceDepth, true);

        // Accumulate SH coefficients
        float  Coefficients[9];
        SH_GetCoefficients(ProbeWorldTexelDirection, Coefficients);
        float AreaCorrection = 1.f;
        for(int i = 0; i < 9; i++) {
            SH_Coefficients[i] += Coefficients[i] * NewRadiance * AreaCorrection;
        }
    }

    // Write SH coefficients
    for(int i = 0; i<9; i++) {
        // Multiply by TWO_PI to monte-carlo integrate to retrieve the coefficients
        // (TWO_PI: Hemispherical integration)
        SH_Coefficients[i] = WaveActiveSum(SH_Coefficients[i]) * (1.f / SSRC_PROBE_TEXTURE_TEXEL_COUNT) * TWO_PI;
    }
    if(WaveIsFirstLane()) {
        WriteScreenProbeSHCoefficients(ProbeIndex, SH_Coefficients);
    }

}


[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_PadProbeTextureEdges (int GroupID : SV_GroupID, int LocalID : SV_GroupThreadID) {

    int2 ProbeIndex = int2(GroupID % UB.TileDimensions.x, GroupID / UB.TileDimensions.x);
    ProbeHeader Header = GetScreenProbeHeader(ProbeIndex);
    // Thread group early out if the probe is not valid
    [branch]
    if(!Header.bValid) return ;
    int2 BaseSrcTexCoords = ProbeIndex * SSRC_PROBE_TEXTURE_SIZE;
    int2 BaseDstTexCoords = ProbeIndex * (SSRC_PROBE_TEXTURE_SIZE + 2);
    
    if(LocalID < SSRC_PROBE_TEXTURE_SIZE + 2) {
        g_RWProbeSampleColorTexture[BaseDstTexCoords + int2(LocalID, 0)] = g_RWProbeColorTexture[BaseSrcTexCoords + int2(clamp(LocalID - 1, 0, SSRC_PROBE_TEXTURE_SIZE - 1), 0)];
        g_RWProbeSampleColorTexture[BaseDstTexCoords + int2(LocalID, SSRC_PROBE_TEXTURE_SIZE + 1)] = g_RWProbeColorTexture[BaseSrcTexCoords + int2(clamp(LocalID - 1, 0, SSRC_PROBE_TEXTURE_SIZE - 1), SSRC_PROBE_TEXTURE_SIZE - 1)];
    }
    if(LocalID < SSRC_PROBE_TEXTURE_SIZE) {
        g_RWProbeSampleColorTexture[BaseDstTexCoords + int2(0, LocalID + 1)] = g_RWProbeColorTexture[BaseSrcTexCoords + int2(0, LocalID)];
        g_RWProbeSampleColorTexture[BaseDstTexCoords + int2(SSRC_PROBE_TEXTURE_SIZE + 1, LocalID + 1)] = g_RWProbeColorTexture[BaseSrcTexCoords + int2(SSRC_PROBE_TEXTURE_SIZE - 1, LocalID)];
    }
    for(int BaseTexelRank = 0; BaseTexelRank < SSRC_PROBE_TEXTURE_TEXEL_COUNT; BaseTexelRank += WAVE_SIZE) {
        int TexelRank = BaseTexelRank + LocalID;
        int2 TexelCoords = int2(TexelRank % SSRC_PROBE_TEXTURE_SIZE, TexelRank / SSRC_PROBE_TEXTURE_SIZE);
        int2 SrcTexCoords = BaseSrcTexCoords + TexelCoords;
        int2 DstTexCoords = BaseDstTexCoords + TexelCoords + 1.xx;
        g_RWProbeSampleColorTexture[DstTexCoords] = g_RWProbeColorTexture[SrcTexCoords];
    }
}

void GetScreenProbeSHCoefficients (int2 ProbeIndex, out float3 ProbeSH[9]) {
    float4 R1 = g_RWProbeSHCoefficientsRTexture[ProbeIndex];
    float4 R2 = g_RWProbeSHCoefficientsRTexture[ProbeIndex + int2(UB.TileDimensions.x, 0)];
    float4 G1 = g_RWProbeSHCoefficientsGTexture[ProbeIndex];
    float4 G2 = g_RWProbeSHCoefficientsGTexture[ProbeIndex + int2(UB.TileDimensions.x, 0)];
    float4 B1 = g_RWProbeSHCoefficientsBTexture[ProbeIndex];
    float4 B2 = g_RWProbeSHCoefficientsBTexture[ProbeIndex + int2(UB.TileDimensions.x, 0)];
    float3 RGB0 = g_RWProbeIrradianceTexture[ProbeIndex].xyz;
    ProbeSH[0] = RGB0;
    ProbeSH[1] = float3(R1.x, G1.x, B1.x);
    ProbeSH[2] = float3(R1.y, G1.y, B1.y);
    ProbeSH[3] = float3(R1.z, G1.z, B1.z);
    ProbeSH[4] = float3(R1.w, G1.w, B1.w);
    ProbeSH[5] = float3(R2.x, G2.x, B2.x);
    ProbeSH[6] = float3(R2.y, G2.y, B2.y);
    ProbeSH[7] = float3(R2.z, G2.z, B2.z);
    ProbeSH[8] = float3(R2.w, G2.w, B2.w);
}

// Modified from GI1.0
// Evaluates the irradiance from the probe's SH representation using a bent cone.
float3 ProbeIntegrateBentCone(float3 normal, float ao, int2 ProbeIndex)
{
    float ClampedCosineSH[9];
    SH_GetCoefficients_ClampedCosine_Cone(normal, acos(sqrt(saturate(1.0f - ao))), ClampedCosineSH);

    float3 irradiance = float3(0.0f, 0.0f, 0.0f);
    float3 ProbeSH[9];
    GetScreenProbeSHCoefficients(ProbeIndex, ProbeSH);
    for (uint i = 0; i < 9; ++i)
    {
        irradiance += ClampedCosineSH[i] * ProbeSH[i];
    }

    return max(irradiance, 0.0f);
}

float4 SampleScreenProbeRadianceDepth (int2 ProbeIndex, float3 LocalDirection) {
    float2 TexelPosition = SSRC_PROBE_TEXTURE_SIZE * UnitVectorToHemiOctahedron01A(LocalDirection);
    float2 AtlasPosition = TexelPosition + ProbeIndex * (SSRC_PROBE_TEXTURE_SIZE + 2) + 1.xx;
    uint2  Dimensions;
    g_ProbeSampleColorTexture.GetDimensions(Dimensions.x, Dimensions.y);
    float2 AtlasUV = AtlasPosition / Dimensions;
    return g_ProbeSampleColorTexture.SampleLevel(g_LinearClampSampler, AtlasUV, 0);
}

// Copy-pasted from Capsaicin
/**
 * Calculate the approximate direction of the specular peak.
 * @note This can be used in place of a light direction vector when calculating
 * shading half-vectors when the light direction is unknown.
 * @param normal         Shading normal vector at current position (must be normalised).
 * @param viewDirection  Outgoing ray view direction (must be normalised).
 * @param roughness      The GGX perceptual roughness (roughness = sqrt(roughnessAlpha).
 * @return The calculated direction.
 */
float3 calculateGGXSpecularDirection(float3 normal, float3 viewDirection, float roughness)
{
    // Moving Frostbite to Physically Based Rendering 3.0, page 69
    float3 reflection = reflect(-viewDirection, normal);
    float smoothness = saturate(1 - roughness);
    float lerpFactor = smoothness * (sqrt(smoothness) + roughness);
    return normalize(lerp(normal, reflection, lerpFactor));
}

[numthreads(WAVE_SIZE, 1, 1)]
void SSRC_Integrate (int2 GroupID : SV_GroupID, int LocalID : SV_GroupThreadID) {
    int TileID = GroupID.x + GroupID.y * UB.TileDimensions.x;
    int2 TileTextureBaseOffset = int2(GroupID) * TILE_SIZE;
    const int PIXEL_PER_THREAD = TILE_SIZE * TILE_SIZE / WAVE_SIZE;
	CameraDescription C = GetCameraDescription();
    Random rng = MakeRandom(TileID, LocalID);
    for(int i = 0; i< PIXEL_PER_THREAD; i++) {
        int PixelIndex = i * WAVE_SIZE + LocalID;
        // Operate in subtiles (8x8) to get better coherency in loop branching
        // with the more likely the same number of basis to access for each thread
        int SubtileIndex  = PixelIndex / (SMALL_TILE_SIZE * SMALL_TILE_SIZE);
        int SubPixelIndex = PixelIndex % (SMALL_TILE_SIZE * SMALL_TILE_SIZE);
        int PixelX = SMALL_TILE_SIZE * (SubtileIndex % 2) + SubPixelIndex % SMALL_TILE_SIZE;
        int PixelY = SMALL_TILE_SIZE * (SubtileIndex / 2) + SubPixelIndex / SMALL_TILE_SIZE;
        int2 TexCoords = TileTextureBaseOffset + int2(PixelX, PixelY);
        float2 UV = (TexCoords + 0.5f) / UB.ScreenDimensions;
        float LinearDepth = GetFilteredDepthTexture(C).Load(int3(TexCoords, 0)).x;
        if(LinearDepth > 0) {
            
            // Frame
            float3 WorldPosition = RecoverWorldSpacePosition(C, TexCoords + 0.5f, LinearDepth);
            float3 Normal        = normalize(2.f * GetNormalTexture(C).Load(int3(TexCoords, 0)).xyz - 1.f);

            Material M = FetchMaterial(C, TexCoords);
            
            float3 ViewDirection = normalize(C.Position - WorldPosition);
            float DotNV = saturate(dot(Normal, ViewDirection));

            SSRC_SampleData Sample;
            CalculateSSRCSampleWeights(
                TexCoords + 0.5f,
                WorldPosition,
                LinearDepth, 
                Normal,
                true,
                Sample
            );

            ProbeHeader Headers[4];
            Headers[0] = GetScreenProbeHeader(Sample.Index[0]);
            Headers[1] = GetScreenProbeHeader(Sample.Index[1]);
            Headers[2] = GetScreenProbeHeader(Sample.Index[2]);
            Headers[3] = GetScreenProbeHeader(Sample.Index[3]);
            float3 ProbeTangents[4];
            float3 ProbeBitangents[4];
            for(int i = 0; i < 4; i++) {
                GetOrthoVectors(Headers[i].Normal, ProbeTangents[i], ProbeBitangents[i]);
            }
            // Normalize weights
            Sample.Weights /= max(dot(Sample.Weights, 1.f.xxxx), 0.01f);
            if(dot(Sample.Weights, 1.f.xxxx) > 0.99f) {
				// TODO: SSAO for enhanced visual quality
                float  AO = 1.f;
                float3 ReflectionDirection = calculateGGXSpecularDirection(Normal, ViewDirection, M.Roughness);
                float3 HalfVector_Spec = normalize(ReflectionDirection + ViewDirection);
                float dotSpecHV = saturate(dot(HalfVector_Spec, ViewDirection));
                // Approximate the Fresnel term with the ReflectionDirection as light direction
                // which is the same approximation used by GI1.0
                float3 FresnelTerm = fresnel(M.F0, dotSpecHV);
                float3 DiffuseCompensation = diffuseCompensationTerm(FresnelTerm, dotSpecHV);
                // LowFreq-Diffuse shading
                float3 LowFreq_Diffuse = 0.f.xxx;
                [unroll(4)]
                for(int CornerIndex = 0; CornerIndex < 4; CornerIndex ++) {
                    if(Sample.Weights[CornerIndex] > 0.f) { 
                        float3 Irradiance = ProbeIntegrateBentCone(Normal, AO, Sample.Index[CornerIndex]);
                        float3 WeightedIrradiance = Irradiance * Sample.Weights[CornerIndex];
                        LowFreq_Diffuse += WeightedIrradiance * AO;
                    }
                }
                
                float3 LowFreq_Specular = 0.f.xxx;
                // Use radiance values from probes directly for low frequency specular
                
                float2 LUT = g_ShadingLUTTexture.SampleLevel(g_LinearClampSampler, float2(saturate(dot(Normal, ViewDirection)), M.Roughness), 0.0f).xy;
                float3 SpecularAlbedo = saturate(M.F0 * LUT.x + (1.0f - M.F0) * LUT.y);
                
                for(int CornerIndex = 0; CornerIndex < 4; CornerIndex ++) {
                    if(Sample.Weights[CornerIndex] > 0.f) {
                        float3 LocalReflectionDirection = float3(
                            dot(ProbeTangents[CornerIndex],   ReflectionDirection),
                            dot(ProbeBitangents[CornerIndex], ReflectionDirection),
                            dot(Headers[CornerIndex].Normal, ReflectionDirection)
                        );
                        if(LocalReflectionDirection.z > 0.f) {
                            float4 RadianceDepth = SampleScreenProbeRadianceDepth(Sample.Index[CornerIndex], LocalReflectionDirection);
                            // Fade specular radiance near occlusions to give more accurate reflections
                            float  DistanceFade  = RadianceDepth.w / max(1e-3f, Headers[CornerIndex].LinearDepth);
                            DistanceFade = saturate(DistanceFade * DistanceFade);
                            LowFreq_Specular += RadianceDepth.xyz * DistanceFade * Sample.Weights[CornerIndex];
                        }
                    }
                }
                LowFreq_Specular = SpecularAlbedo * LowFreq_Specular;
                
				
                float3 HighFreq_Diffuse = 0.f.xxx;
                float3 HighFreq_Glossy  = 0.f.xxx;

                // Composite final lighting
                float3 FarFieldIrradiance  = (HighFreq_Diffuse + LowFreq_Diffuse) * DiffuseCompensation;
                float3 NearFieldIrradiance = 0.f;
                // float3 FarFieldGlossySpecular = (HighFreq_Glossy + LowFreq_Specular) * AO;

                // Write to output                
                GetRWIndirectIlluminationTexture(C)[TexCoords] = float4(FarFieldIrradiance + NearFieldIrradiance,  1.f);
                // g_RWGlossySpecularTexture[TexCoords] = float4(FarFieldGlossySpecular, 1.f);
            } else {
                GetRWIndirectIlluminationTexture(C)[TexCoords] = 0.f.xxxx;
                // g_RWGlossySpecularTexture[TexCoords] = float4(0.f, 0.f, 0.f, 0.f);
            }
        } else {
            GetRWIndirectIlluminationTexture(C)[TexCoords] = 0.f.xxxx;
            // g_RWGlossySpecularTexture[TexCoords] = float4(0.f, 0.f, 0.f, 0.f);
        }
    }
}

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void TemporalDenoiseLighting (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	int2 PixelCoords = int2(DispatchID);
	Material M = FetchMaterial(C, PixelCoords);
	if(M.Alpha < UB.OpaqueThreshold) {
		return;
	}
	float PixelZDepth = GetZDepthTexture(C).Load(int3(PixelCoords, 0)).x;
	float2 ScreenPosition = PixelCoords + 0.5f.xx;
	float3 NDC = float3(ScreenToNDC2(ScreenPosition), PixelZDepth);
	float3 PreviousNDC  = ReprojectToPreviousNDCFromNDC(C, NDC);
	float3 ViewDirection = NDC2ToCameraDirection(C, NDC.xy);
	float4 NewDirectIllumination_C  = GetDirectIlluminationTexture(C).Load(int3(PixelCoords, 0));
	float4 NewIndirectIllumination_Diffuse_C = GetIndirectIlluminationTexture(C).Load(int3(PixelCoords, 0));
	// TODO: the normal should be a low frequency one.
	// here the normal is not denoised. Maybe we should use the denoised normal.
	float3 GeometryNormal = normalize(GetNormalTexture(C).Load(int3(PixelCoords, 0)).xyz - 0.5);
	float4 DenoisedDI = NewDirectIllumination_C;
	float4 DenoisedII_Diffuse = NewIndirectIllumination_Diffuse_C;
	if(all(PreviousNDC.xy >= -1) && all(PreviousNDC.xy <= 1)) {
		float2 PreviousScreenPosition = NDC2ToScreen(PreviousNDC.xy);
		// Make sure the billinear weights are consistent with gathered texels
		float2 HistoryBillinearPos = PreviousScreenPosition - 0.5f;
		float2 HistoryBillinearSubPixel = frac(HistoryBillinearPos);
		float2 HistoryBillinearPixel = floor(HistoryBillinearPos);
		float2 HistoryGatherUV = (HistoryBillinearPixel + 1.f) * C.InvFilmDimensions;
		float4 HistoryZDepths = GetHistoryZDepthTexture(C).GatherRed(g_PointClampSampler, HistoryGatherUV).wzxy;
		float  PrevLinearDepth = ZDepthToLinear(C, PreviousNDC.z);
		float4 HistoryLinearDepths = float4(
			ZDepthToLinear(C, HistoryZDepths.x),
			ZDepthToLinear(C, HistoryZDepths.y),
			ZDepthToLinear(C, HistoryZDepths.z),
			ZDepthToLinear(C, HistoryZDepths.w)
		);
		float4 DepthDistances = abs(HistoryLinearDepths - PrevLinearDepth);
		float  Noise = InterleavedGradientNoise(NDC2ToUV(NDC.xy), UB.FrameIndex);
		float4 DepthThresholds = UB.DI_Denoiser_DepthThreshold * lerp(0.5, 1.5, Noise);
		// UE's resolution for disocclusion misses on geometry edges
		DepthThresholds /= clamp(saturate(dot(ViewDirection, GeometryNormal)), .1f, 1.0f); 
		float4 OcclusionWeights   = select(DepthDistances < PrevLinearDepth * DepthThresholds, 1, 0);
		float4 BillinearWeights = float4(
			(1.f - HistoryBillinearSubPixel.x) * (1.f - HistoryBillinearSubPixel.y),
			HistoryBillinearSubPixel.x * (1.f - HistoryBillinearSubPixel.y),
			(1.f - HistoryBillinearSubPixel.x) * HistoryBillinearSubPixel.y,
			HistoryBillinearSubPixel.x * HistoryBillinearSubPixel.y
		);
		float4 Weights = OcclusionWeights * BillinearWeights;
		Weights = Weights / max(dot(Weights, 1), 1e-6f);

		float3 OldDirectIllumination = 0.f;
		float3 OldIndirectIllumination_Diffuse = 0.f;
		Texture2D<float4> HistoryDI = GetHistoryDirectIlluminationTexture(C);
		Texture2D<float4> HistoryII_Diffuse = GetHistoryIndirectIlluminationTexture(C);
		{
			float2 BaseUV = ScreenToUV(HistoryBillinearPixel + 0.5f);
			float3 R00 = HistoryDI.SampleLevel(g_PointClampSampler, BaseUV, 0).rgb;
			float3 R10 = HistoryDI.SampleLevel(g_PointClampSampler, BaseUV + float2(C.FilmTexelSize.x, 0), 0).rgb;
			float3 R01 = HistoryDI.SampleLevel(g_PointClampSampler, BaseUV + float2(0, C.FilmTexelSize.y), 0).rgb;
			float3 R11 = HistoryDI.SampleLevel(g_PointClampSampler, BaseUV + C.FilmTexelSize, 0).rgb;
			OldDirectIllumination = R00 * Weights.x + R10 * Weights.y + R01 * Weights.z + R11 * Weights.w;
		}
		{
			float2 BaseUV = ScreenToUV(HistoryBillinearPixel + 0.5f);
			float3 R00 = HistoryII_Diffuse.SampleLevel(g_PointClampSampler, BaseUV, 0).rgb;
			float3 R10 = HistoryII_Diffuse.SampleLevel(g_PointClampSampler, BaseUV + float2(C.FilmTexelSize.x, 0), 0).rgb;
			float3 R01 = HistoryII_Diffuse.SampleLevel(g_PointClampSampler, BaseUV + float2(0, C.FilmTexelSize.y), 0).rgb;
			float3 R11 = HistoryII_Diffuse.SampleLevel(g_PointClampSampler, BaseUV + C.FilmTexelSize, 0).rgb;
			OldIndirectIllumination_Diffuse = R00 * Weights.x + R10 * Weights.y + R01 * Weights.z + R11 * Weights.w;
		}

		float4 HistorySampleCounts_DI = HistoryDI.GatherAlpha(g_PointClampSampler, HistoryGatherUV).wzxy;
		float4 HistorySampleCounts_II_Diffuse = HistoryII_Diffuse.GatherAlpha(g_PointClampSampler, HistoryGatherUV).wzxy;
		{
			float NewSampleCount_DI = NewDirectIllumination_C.a;
			float OldSampleCount = dot(HistorySampleCounts_DI * Weights, 1.f.xxxx);
			if(UB.DI_NoTemporalDenoising) {
				OldSampleCount = 0;
			}
			float ClampedOldSampleCount = min(OldSampleCount, max(UB.DI_Denoiser_TargetNumSamples - NewSampleCount_DI, 0));
			float SampleCount = ClampedOldSampleCount + NewSampleCount_DI;
			float BlendingFactor = ClampedOldSampleCount / max(SampleCount, 1e-4f);
			DenoisedDI = float4(
				lerp(NewDirectIllumination_C.rgb, OldDirectIllumination, BlendingFactor),
				SampleCount
			);
		}
		{
			float NewSampleCount_II_Diffuse = NewIndirectIllumination_Diffuse_C.a;
			float OldSampleCount = dot(HistorySampleCounts_II_Diffuse * Weights, 1.f.xxxx);
			if(UB.II_NoTemporalDenoising) {
				OldSampleCount = 0;
			}
			float ClampedOldSampleCount = min(OldSampleCount, max(UB.II_Denoiser_TargetNumSamples - NewSampleCount_II_Diffuse, 0));
			float SampleCount = ClampedOldSampleCount + NewSampleCount_II_Diffuse;
			float BlendingFactor = ClampedOldSampleCount / max(SampleCount, 1e-4f);
			DenoisedII_Diffuse = float4(
				lerp(NewIndirectIllumination_Diffuse_C.rgb, OldIndirectIllumination_Diffuse, BlendingFactor),
				SampleCount
			);
		}
	}
	// Store the results back to the direct illumination buffer
	GetRWFilteredDirectIlluminationTexture(C)[PixelCoords] = DenoisedDI;
	GetRWFilteredIndirectIlluminationTexture(C)[PixelCoords] = DenoisedII_Diffuse;
}

// Temporal denoised DI and II are copied back to the DI & II buffers

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void FinalComposition (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	float3 DirectIllumination   = GetDirectIlluminationTexture(C).Load(int3(DispatchID, 0)).rgb;
	float3 IndirectIllumination = GetIndirectIlluminationTexture(C).Load(int3(DispatchID, 0)).rgb;
	float4 RadianceW = 0;

	// Alpha
	// Slightly increases the alpha value to prevent skylight leaking from the background
	RadianceW.w = saturate(g_GColorTexture.Load(int3(DispatchID, 0)).a + 0.03f);
	float4 VisualizeRadianceW = RadianceW;

	// 1. Direct illumination
	Material M = FetchMaterial(C, DispatchID);
	RadianceW.rgb += DirectIllumination * M.Albedo;	
	if(!UB.NoDirectIllumination) {
		VisualizeRadianceW.rgb += DirectIllumination * M.Albedo;
	}
	// 2. Indirect illumination 
	RadianceW.rgb += IndirectIllumination * M.Albedo;
	if(!UB.NoIndirectIllumination) {
		VisualizeRadianceW.rgb += IndirectIllumination * M.Albedo;
	}
	// Store intermediate result.
	g_RW_HistoryRadianceWithoutEmission[DispatchID] = RadianceW;

	// 3. Emission
	float3 Emission = GetEmissionAlphaTexture(C).Load(int3(DispatchID, 0)).rgb;
	RadianceW.rgb += Emission;
	VisualizeRadianceW.rgb += Emission;

	// RadianceW.rgb = g_RWProbeColorTexture.Load(int3(DispatchID / 2, 0)).rgb;

	float3 ViewDirection = -NDC2ToCameraDirection(C, FilmToNDC2(C, DispatchID + 0.5f.xx));
	float3 SkyRadiance = EvaluateSkyRadiance(ViewDirection);
	RadianceW.rgb += SkyRadiance * (1.f - RadianceW.w);
	VisualizeRadianceW.rgb += SkyRadiance * (1.f - RadianceW.w);
	GetRWRadianceTexture(C)[DispatchID] = float4(
		VisualizeRadianceW.rgb,
		1
	);
}

// Card kernels
[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void ClearCard (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	int2 TexelCoords = MCUB.CardAtlasBaseCoords.xy + int2(DispatchID);
	int3 AtlasCoords = int3(TexelCoords, MCUB.CardAtlasBaseCoords.z);
	g_RWCardAtlas_ColorTexture[AtlasCoords] = 0;
	g_RWCardAtlas_AlphaTexture[AtlasCoords] = 0;
	g_RWCardAtlas_NormalTexture[AtlasCoords] = 0;
	g_RWCardAtlas_LinearDepthTexture[AtlasCoords] = 0;
	g_RWCardAtlas_DirectIlluminationTexture[AtlasCoords] = 0;
	g_RWCardAtlas_IndirectIlluminationTexture[AtlasCoords] = 0;
	g_RWCardAtlas_LightingTexture[AtlasCoords] = 0;
}

[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void CopyCardToAtlas(uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	int2 TexelCoords = MCUB.CardAtlasBaseCoords.xy + int2(DispatchID);
	int3 AtlasCoords = int3(TexelCoords, MCUB.CardAtlasBaseCoords.z);
	int2 ScreenCoords = int2(DispatchID);
	g_RWCardAtlas_ColorTexture[AtlasCoords].rgb = GetRWColorTexture(C)[ScreenCoords].rgb;
	g_RWCardAtlas_AlphaTexture[AtlasCoords].r = GetRWColorTexture(C)[ScreenCoords].a;
	g_RWCardAtlas_NormalTexture[AtlasCoords].rgb = GetRWNormalTexture(C)[ScreenCoords].rgb;
	g_RWCardAtlas_LinearDepthTexture[AtlasCoords].r = GetRWDepthTexture(C)[ScreenCoords].r;
}

#ifndef NDEBUG
[numthreads(1, 1, 1)]
void Debug_PrepareVisualizeDIRay () {
	int2 PixelCoords = UB.Debug_CursorPixelCoords;
	Material M = FetchMaterial(GetCameraDescription(), PixelCoords);
	if(!IsMaterialValid(M)) {
		// No rays to visualize
		g_Debug_VisualizeRayCountBuffer[0] = 0;
		return ;
	}
	int RayIndex = g_Debug_DirectIlluminationPixelRayIndexBuffer[PixelCoords.x + PixelCoords.y * UB.ScreenDimensions.x];
	if(RayIndex == 0xffffffffu) {
		// No rays to visualize
		g_Debug_VisualizeRayCountBuffer[0] = 0;
		return ;
	}
	g_Debug_VisualizeRayCountBuffer[0] = 1;
	RayToTrace Ray = FetchRayToTrace(RayIndex, UB.RT_MaxTraceDistance, false);
	float LinearDepth = GetFilteredDepthTexture(GetCameraDescription()).Load(int3(PixelCoords, 0)).r;
	float3 Origin = RecoverWorldSpacePosition(GetCameraDescription(), PixelCoords, LinearDepth);
	g_Debug_VisualizeRayVertexBuffer[0] = Origin;
	g_Debug_VisualizeRayVertexBuffer[1] = Origin + Ray.Direction * Ray.RayTMin;
	g_Debug_VisualizeRayRayIndexBuffer[0]  = RayIndex;
}
#endif

// Spawn rays starting from the camera
// For 3DGS HWRT testing purposes only.
// Dispatched 1 group per a small tile
[numthreads(WAVE_SIZE, 1, 1)]
void SpawnCameraRays (uint GroupID : SV_GroupID, uint LocalID : SV_GroupThreadID) {
	if(GroupID == 0 && LocalID == 0) {
		g_RWRayToTraceCountBuffer[0] = UB.ScreenDimensions.x * UB.ScreenDimensions.y;
	}
	// Pack rays in 8x8 small tiles for better cache coherence when tracing a
	// bunch of rays
	int2 TileCoords = int2(GroupID % UB.SmallTileDimensions.x, GroupID / UB.SmallTileDimensions.x);
	for(int TileBaseTexelIndex = 0; TileBaseTexelIndex < SMALL_TILE_SIZE * SMALL_TILE_SIZE; TileBaseTexelIndex += WAVE_SIZE) {
		int TileTexelIndex = TileBaseTexelIndex + LocalID;
		int2 TexelCoords = int2(
			TileTexelIndex % SMALL_TILE_SIZE,
			TileTexelIndex / SMALL_TILE_SIZE
		) + TileCoords * SMALL_TILE_SIZE;
		
		float2 ScreenPosition = float2(TexelCoords) + 0.5f;

		RayToTrace Ray = SpawnCameraRay(GetCameraDescription(), ScreenPosition);
		Ray.Seed = UB.HWRT_StochasticRayTracingQuality * BlueNoise_Sample1D(TexelCoords, UB.FrameIndex);
		int RayIndex = TexelCoords.x + TexelCoords.y * UB.ScreenDimensions.x;
		g_RWRayToTraceListBuffer[RayIndex] = RayIndex;
		WriteRayToTrace(RayIndex, Ray);
	}
}

// Display the camera rays trace results on the screen
[numthreads(WAVE_SIZE, 1, 1)]
void DisplayCameraRays (uint GroupID : SV_GroupID, uint LocalID : SV_GroupThreadID) {
	int2 TileCoords = int2(GroupID % UB.SmallTileDimensions.x, GroupID / UB.SmallTileDimensions.x);
	for(int TileBaseTexelIndex = 0; TileBaseTexelIndex < SMALL_TILE_SIZE * SMALL_TILE_SIZE; TileBaseTexelIndex += WAVE_SIZE) {
		int TileTexelIndex = TileBaseTexelIndex + LocalID;
		int2 TexelCoords = int2(
			TileTexelIndex % SMALL_TILE_SIZE,
			TileTexelIndex / SMALL_TILE_SIZE
		) + TileCoords * SMALL_TILE_SIZE;
		
		int RayIndex = TexelCoords.x + TexelCoords.y * UB.ScreenDimensions.x;
		if(UB.VisualizeShadingRays) {
			float4 RayResult = FetchRayTraceResult(RayIndex);
			g_RW_Radiance[TexelCoords] = float4(RayResult.xyz, 1);
		} else {
			float  RayT = FetchRayTraceHitT(RayIndex) * 0.2f;
			g_RW_Radiance[TexelCoords] = float4(RayT.xxx, 1);
		}
	}
}

// Visualize surfaces shaded from mesh cards
[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void VisualizeMeshCardScene (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	int2 PixelCoords = int2(DispatchID);
	float2 UV = PixelCoords / C.FilmDimensions;
	float  LinearDepth = GetFilteredDepthTexture(C).Load(int3(PixelCoords, 0)).r;
	if(LinearDepth > 0) {
		float3 WorldPosition = RecoverWorldSpacePosition(C, PixelCoords, LinearDepth);
		float3 ViewDirection = normalize(WorldPosition - C.Position);

		CardSet Cards = FetchCardSet(UB.Debug_CardSetToVisualize);
		float3x4 WorldToInstanceTransform = g_InstanceInvTransformBuffer[UB.Debug_CardSetToVisualize];
		float3x3 WorldToInstanceNormalTransform = g_InstanceNormalTransformBuffer[UB.Debug_CardSetToVisualize];

		CardSampleAccumulator Accumulator = SampleCardSet(
			Cards,
			WorldToInstanceTransform, 
			WorldToInstanceNormalTransform,
			WorldPosition, 
			ViewDirection
		);

		g_RW_DebugTexture[DispatchID] = float4(Accumulator.SolveRadiance(), 1);
	}
	
}

// Inspect card atlas
[numthreads(TILE_SIZE, TILE_SIZE, 1)]
void VisualizeMeshCardAtlas (uint2 DispatchID : SV_DispatchThreadID) {
	CameraDescription C = GetCameraDescription();
	if(IsOutOfFilm(C, DispatchID)) return;
	int2 PixelCoords = int2(DispatchID);
	float3 AtlasPosition = float3(
		PixelCoords * UB.Debug_VisualizeMeshCardAtlasScale + UB.Debug_VisualizeMeshCardAtlasOffset,
		UB.Debug_VisualizeMeshCardAtlasLayer
	);
	float3 AtlasSamplePosition = float3(AtlasPosition.xy / CARD_ATLAS_RESOLUTION, AtlasPosition.z);
	if(UB.Debug_VisualizeMeshCardAtlasChannel == 0) {
		g_RW_DebugTexture[PixelCoords] = float4(
			g_CardAtlas_ColorTexture.SampleLevel(g_LinearClampSampler, AtlasSamplePosition, 0).rgb, 1);
	} else if(UB.Debug_VisualizeMeshCardAtlasChannel == 1) {
		g_RW_DebugTexture[PixelCoords] = float4(
			g_CardAtlas_AlphaTexture.SampleLevel(g_LinearClampSampler, AtlasSamplePosition, 0).rrr, 1);
	} else if(UB.Debug_VisualizeMeshCardAtlasChannel == 2) {
		g_RW_DebugTexture[PixelCoords] = float4(
			g_CardAtlas_NormalTexture.SampleLevel(g_LinearClampSampler, AtlasSamplePosition, 0).rgb, 1);
	} else if(UB.Debug_VisualizeMeshCardAtlasChannel == 3) {
		g_RW_DebugTexture[PixelCoords] = float4(
			g_CardAtlas_LinearDepthTexture.SampleLevel(g_LinearClampSampler, AtlasSamplePosition, 0).rrr, 1);
	}
}

[numthreads(WAVE_SIZE, 1, 1)]
void GenerateRTMesh (uint DispatchID : SV_DispatchThreadID) {
	int GaussianIndex = DispatchID;
	if(GaussianIndex >= UB.NumGaussians) return ;
	
	Gaussian G = FetchGaussian(GaussianIndex);
	float4x4 ToWorld = 0;
	{
		float3x3 MS = float3x3(
			float3(G.Scale.x, 0, 0),
			float3(0, G.Scale.y, 0),
			float3(0, 0, G.Scale.z)
		);
		float3x3 MR = EvaluateRotationMatrix(G.Rotation);
		float3x3 M = mul(MR, MS);

		ToWorld = float4x4(
			float4(M[0], G.Position.x),
			float4(M[1], G.Position.y),
			float4(M[2], G.Position.z),
			float4(0.xxx, 1)
		);
	}

	// Magic scaling number mentioned in the paper
	float AlphaMin = UB.HWRT_MinAlphaForGaussianEvaluation;
	float Sigma    = UB.GaussianRTProxyGeometrySigma;
	float MagicScale = sqrt(2 * log(Sigma / max(AlphaMin, 0.001f)));

	const float3 IcoVertices[12] = {
		float3(0.000000, -1.000000, 0.000000),
		float3(0.723600, -0.447215, 0.525720),
		float3(-0.276385, -0.447215, 0.850640),
		float3(-0.894425, -0.447215, 0.000000),
		float3(-0.276385, -0.447215, -0.850640),
		float3(0.723600, -0.447215, -0.525720),
		float3(0.276385, 0.447215, 0.850640),
		float3(-0.723600, 0.447215, 0.525720),
		float3(-0.723600, 0.447215, -0.525720),
		float3(0.276385, 0.447215, -0.850640),
		float3(0.894425, 0.447215, 0.000000),
		float3(0.000000, 1.000000, 0.000000)
	};
	const int3 IcoFaces[20] = {
		int3(0, 1, 2),
		int3(1, 0, 5),
		int3(0, 2, 3),
		int3(0, 3, 4),
		int3(0, 4, 5),
		int3(1, 5, 10),
		int3(2, 1, 6),
		int3(3, 2, 7),
		int3(4, 3, 8),
		int3(5, 4, 9),
		int3(1, 10, 6),
		int3(2, 6, 7),
		int3(3, 7, 8),
		int3(4, 8, 9),
		int3(5, 9, 10),
		int3(6, 10, 11),
		int3(7, 6, 11),
		int3(8, 7, 11),
		int3(9, 8, 11),
		int3(10, 9, 11)
	};

	// Emit the vertices
	int VertexBase = GaussianIndex * 12;
	for(int i = 0; i < 12; i++) {
		float3 Vertex = mul(ToWorld, float4(IcoVertices[i] * MagicScale, 1)).xyz;
		g_RW_RTVertexBuffer[VertexBase + i] = Vertex;
	}
	// Emit the indices
	int IndexBase = GaussianIndex * 60;
	int IndexOffset = GaussianIndex * 12;
	for(int i = 0; i < 20; i++) {
		int3 Face = IcoFaces[i];
		g_RW_RTIndexBuffer[IndexBase + i * 3 + 0] = Face.x + IndexOffset;
		g_RW_RTIndexBuffer[IndexBase + i * 3 + 1] = Face.y + IndexOffset;
		g_RW_RTIndexBuffer[IndexBase + i * 3 + 2] = Face.z + IndexOffset;
	}
}
